### ISSUE TITLE
[Accepted with Revisions] SDL 0301 - SDL Device Listener

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1001]
Hello SDL community,

The review of "SDL 0301 - SDL Device Listener"  begins now and runs through April 28 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0301-SDL-device-listener.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1001

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by shiniwat** [comment]
1. Looked into the sample code in Appendix section, and understand that SdlDeviceListener is instantiated after the server socket gets connected. However, it is still unclear who actually opens the server socket. Is that SdlBroadcastReceiver?

2. Related with the question #1, in order to save the SPP resource, only one app at a time should actually listen/open the server socket when ACL_CONNECTED has been broadcasted. How do you prevent multiple apps from listening/opening server socket?

3. In "Which apps create the SDLDeviceListener?" section:
> only the app that has the service to be started will be the one to instantiate an SDLDeviceListener instance. All other apps will simply return out of that logic block.

How the app knows "I am the app that actually has the service to be started"?

4. In "Potential downsides" section:
> There is a chance that the first time a user connects their mobile device to an SDL enabled IVI system the router service will not connect. Subsequent connections, however, should be very likely.

Suppose the router service failed to connect to IVI system at the first time, how to initiate subsequent connection? Does user need to unpair the Android device, and then re-pairing?

**Comment by joeygrover** [comment]
1\. Per the proposal `[SDLDeviceListener] will be a small, scoped class that will be instantiated into the SdlBroadcastReceiver code base.` So the `SdlBroadcastReceiver` will be responsible for creating an instance of the `SDLDeviceListener` and starting it. Therefore the SPP server socket will be created in the `SdlBroadcastReciever`. 
2\. Per the proposal `[...] each app will use the same logic it does now to start an SdlRouterService, but instead of each app starting the service, only the app that has the service to be started will be the one to instantiate an SDLDeviceListener instance. ` Which means only one app will start an `SDLDeviceListener` and only one RFCOMM channel will be used.
3\. Per the proposal `[...] each app will use the same logic it does now to start an SdlRouterService, but instead of each app starting the service, only the app that has the service to be started will be the one to instantiate an SDLDeviceListener instance.` See the code in the `SdlBroadcastReciever` already that calls the method [`querySdlAppInfo`](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java#L103). If the package name that is at the front of the list matches that of the app executing the code it knows that it is the app to start the router service.
4\. No, per the proposal if the `SDLDeviceListener` has connected previously it will continue to start the `SdlRourterService`. If you are referring to if the `SDLDeviceListener` doesn't connect, the proposal also states that it will still attempt to listen just for a shorter duration. 
![image](https://user-images.githubusercontent.com/6579474/80497931-1c59a680-8939-11ea-967c-7b6e5939b625.png)

**Comment by shiniwat** [comment]
> 1. Therefore the SPP server socket will be created in the SdlBroadcastReciever

Understood.

> 2. and 3. 
each app will use the same logic it does now to start an `SdlRouterService`, but instead of each app starting the service, only the app that has the service to be started will be the one to instantiate an SDLDeviceListener instance.

Understood that `SdlBroadcastReceiver` uses the existing logic to invoke `SdlDeviceListener` instance.  

In terms of SPP resource consumption, however, I suspect the proposed approach consumes two SPP resources, while only one in current library. We might as well confirm the number of SPP resources of proposed solution, and describe about it in potential downsides section if the number of SPP resource consumption is increased.

> 4. if the SDLDeviceListener has connected previously it will continue to start the SdlRourterService

Understood that SdlRouterService will continue listening the BT connection. Because SDLCore transport adapter will retry the connection, the attempt of next connection (from SDLCore) will likely be successful. However I was not able to recognize about that with the following statement:

> There is a chance that the first time a user connects their mobile device to an SDL enabled IVI system the router service will not connect. Subsequent connections, however, should be very likely.

Thanks for explaining about that, anyway.

**Comment by joeygrover** [comment]
2\. & 3\.

Per the proposal `This will keep the RFCOMM channels used to only 1 per bluetooth connection`. There is only one channel consumed at a time. The listener will consume one channel as it waits for an SDL connection. If one is made, it will close its socket, releasing the channel, and then starts the `SdlRouterService` which then creates its bluetooth server socket consuming one channel. Since these operations are synchronous, it will not consume more than one channel at a time.

**Comment by shiniwat** [comment]
When BluetoothAdapter is listened and accepted, system assigns RFCOMM channel automatically. With my experience, the RFCOMM channel will be consumed even after the server socket is closed. AFAIK, there's no explicit release method in BluetoothAdapter, and sdptool shows the SDP record untill the process ends. This could be a bug of sdptool, but I am afraid that RFCOMM channel won't be released even after the socket#close, and hence subsequent listening/accepting the server socket will end up with another RFCOMM channel consumed. If you know the explicit release method of BluetoothAdapter, that's fine, but I am afraid if that indeed works.

**Comment by joeygrover** [comment]
Since it is likely there is going to be different bluetooth stacks it is likely to differ in behavior then. However even if there is a lag in between RFCOMM channel releasing, this feature will only happen one time where both RFCOMM channels will be needed. After the `SDLDeviceListener` successfully connects, it will remember that device and never start again for that device. 

This feature is important for app developers to not be starting a foreground service for nonSDL devices while still allowing things to happen without user interaction. I'm open to other suggestions, but found this to be the best case for moving forward.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will be to add a potential downside regarding the potential lag in between RFCOMM channels releasing.  It was also acknowledged that if during implementation/testing, the issue with RFCOMM channels is present, a proposal to revise SDL 0301 can be submitted.  Additionally, if an issue is found in production after the feature is implemented, the library can be updated to remove the feature and functionality can return to its previous state.

**Comment by theresalech** [comment]
@joeygrover please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the Java Suite repository for implementation. Thanks!

**Comment by theresalech** [comment]
The author has updated the proposal to include the agreed upon revisions, and an implementation issue has been entered: [[SDL 0301] SDL Device Listener](https://github.com/smartdevicelink/sdl_java_suite/issues/1348).
