### ISSUE TITLE
[Deferred] SDL 0302 - SDL System Structure for Middle/Low-end Class Model of Powered Two Wheeler

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1004]
Hello SDL community,

The review of "SDL 0302 - SDL System Structure for Middle/Low-end Class Model of Powered Two Wheeler"  begins now and runs through May 12, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0302-SDL-System-Structure-for-MiddleLow-end-Class-Model-of-Powered-Two-Wheeler.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1004

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I have many significant problems with this proposal.

1\. SDL Evolution is not a place for "policy proposals." This proposal includes few technical details about how this would be accomplished, and it needs to include those details. If the author wants to break down the proposal into "stages," that's fine, but every proposal should be able to stand alone, and be able to be implemented by an engineer. All proposals must be "technical proposals" in that sense. I don't believe that this proposal fits that requirement and should be revised or rejected.

2\. I could not more strongly disagree with the idea of forking SDL Core into a similar but less capable version as described in this proposal. To do so would introduce tremendous technical debt. It would exponentially increase integration, tooling, and testing work for all platforms, and it would come with difficult technical decisions – such as how do mobile libraries restrict features for this "SDL Lite," how does the RPC spec and protocol spec have to change, what is the "new lightweight communication protocol," and more. I strongly urge the author to revisit how to approach this concept and come up with a new plan. I believe this proposal should be rejected.

**Comment by Shohei-Kawano** [comment]
@joeljfischer -san
2. I understand your concerns. However, the two-wheeled vehicle MultiMedia hardware is arguably weaker than the four-wheeled vehicle. In order to realize SDL for the two-wheeled vehicle within this limit, we believe that it is necessary to keep the minimum functions and to reduce the weight of communication itself.
It would be great if you could advise me if there is a solution within this limitation while still having similar features.

**Comment by Takuya-kuriyama** [comment]
@joeljfischer -san
1. We have already discussed the policy at SDL board meeting. The decision of the meeting is that Suzuki and supporting Japanese OEMs needs to follow the established process of defining the feature through SDL Evolution proposals for steering committee to review development details. So we think we can post this proposal.

**Comment by joeljfischer** [comment]
Hi @Shohei-Kawano, @Takuya-kuriyama, thanks you for the responses.

1\. I'm not objecting to your posting of the proposal, after all, anybody can propose something with or without board of director approval. That's why this is an open process. I also think that it's a good thing for SDL to appear on smaller vehicles. This objection is that the form of this proposal is not appropriate. You state in the proposal, for example:

> Note that this proposal is only a policy proposal. We will provide a separate proposal for function according to the use case of PTW after this proposal is accepted.

The SDL evolution process is not a place for "policy proposals." Every proposal should be able to be implemented by an engineer of reasonable skill based on the content provided in the document. This proposal does not meet that standard. That is why I ask that this proposal be withdrawn or returned for revisions to make it "implementable" and contain technical details. It's impossible for this technical committee to accept a proposal like this one without technical details.

2\. I think there are a few things incorrect about this response, and I have a few additional points:

> However, the two-wheeled vehicle MultiMedia hardware is arguably weaker than the four-wheeled vehicle. In order to realize SDL for the two-wheeled vehicle within this limit, we believe that it is necessary to keep the minimum functions and to reduce the weight of communication itself.

a. This proposal doesn't state what the "minimum functions" are to allow the SDLC to determine the need and feasibility of this proposal.

b. This proposal doesn't state what the "lightweight communication protocol" will be (BLE seems to be suggested), why it will improve the situation, nor does it discuss the downsides of supporting multiple communication protocols within SDL Core, HMI, and all app libraries, nor the downsides of trying to support BLE on iOS, for example, which would require the app in use to be in the foreground.

> It would be great if you could advise me if there is a solution within this limitation while still having similar features.

c. You note in the proposal:

> (The binary size is 177MB when built with x86_64.)

This is not correct for the latest release of Core. One of Livio's engineers found that for Core v6.1 the default (DEBUG) build is 900mb, but the RELEASE build is only 55mb. It could probably be even smaller by turning off build flags for things like remote control, vehicle data, or policies. I would advise to investigate how big release builds of the latest version of Core are with various flags on / off and to report those results in your proposal and why they're not sufficient. You could then suggest additional build feature flags to reduce the binary size.

Additional potential avenues could be adding additional feature flags to disable or modify features that use a lot of RAM / etc.

I would strongly recommend that you abandon the BLE / new communication protocol avenue. It will introduce a tremendous amount of technical debt for only a little gain. I would strongly recommend that you stick to adding build flags / improving SDL Core as it exists now (for example, if you find a way to reduce RAM, that's helpful in larger vehicles too) instead of forking Core. That introduces a huge amount of technical debt and will slow down development a _lot_, and I would strongly oppose any such proposal.

> Due to the changes proposed, there may be a huge difference with the existing SDL.

I am grateful for the honesty of this statement, and I commend you for including it in this proposal. However, I will remain strongly in opposition to any proposal that requires the SDLC and maintainers to develop and support the technical debt of a fork of SDL that creates "a huge difference with the existing SDL."

Based on the above, I recommend rejecting this proposal to allow you to go back and investigate other possible avenues and re-submit a new "implementable" technical proposal that will not double the SDL Core, app library, and HMI development and testing workload.

**Comment by JackLivio** [comment]
Continuing Joel's comment for 2 c.

2c. Refer to the possible build options [in SDL Core here](https://github.com/smartdevicelink/sdl_core/blob/master/CMakeLists.txt#L111)

Building Core with option `Release` will greatly reduce the size of the binaries.

> cmake  ../sdl_core -DCMAKE_BUILD_TYPE=Release

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow the authors time to discuss internally the comments from the Project Maintainer, and respond on the review issue with more information.  The Project Maintainer also asked the author to comment on the review issue with the current hardware specs they are working with, as that will aid in the discussion of possible solutions.

**Comment by Shohei-Kawano** [comment]
@joeljfischer -san, @JackLivio -san,
2c : 
The following are specific examples of the two-wheeled vehicle hardware.
 ROM : 1024KB
 RAM : 64KB

Of course not all can be used with SDL.
Perhaps it can only use a few hundred KB for ROM.
In other words, the binary size needs to be a few hundred KB.

**Comment by JackLivio** [comment]
@Shohei-Kawano Thank you for the requirements. These limitations will likely require a new SDL Core application to be created from scratch that only supports a limited set of features.

**Comment by JackLivio** [comment]
Sorry i did not mean to close the issue, that was an accident.

**Comment by joeygrover** [comment]
2c\. What are the exact minimum hardware specs that this should support? There needs to be some guidelines on the size of this project and the functionality it can support within those guidelines.

3\. Extending Jack's questions, of the current SDL functionality, what specifically does this need to support? For example, functionality that is supported through the “Show” RPC seems necessary, but things like policies, video streaming, etc do not.

4\. What language do you plan to use for this project on the “core/HMI” side? Potentially some version of C?

5\. Can you share the “SDL Command Protocol” that was stated in the proposal? If not, do you have an example of what you believe it would look like? Is it the intention to continue using JSON or BSON as the message format? Or does the proposal imply something new entirely be created?

**Comment by Shohei-Kawano** [comment]
@joeygrover -san
2c. I would like to organize according to the items of Requirement of the current SDL.
I think it is probably written in the link below, but I could not refer to it.
"SDL-Core Requirements" on https://www.smartdevicelink.com/en/docs/sdl-core/master/atf/solution-background/#62-requirements-coverage
Can you give me the permission or tell me the contents?

**Comment by joeygrover** [comment]
2c\. That link is not related to the overall requirements. The SDLC had voted to remove general "requirements" from SDL so I don't have information to give. The idea was that if an OEM could make it work for their system, we as the consortium shouldn't restrict that. However, with this specific type of proposal the author is explicitly asking to create a new SDL feature that is for low powered devices. Therefore, we need to understand how low powered the ask is so we can identify what could be a reasonable solution.

**Comment by Takuya-kuriyama** [comment]
@joeljfischer  san and @joeygrover san @JackLivio  san

We think your questions are too detail at this time. 
This is first step. This proposal is written about only basic concept of PTW.

At this step, could you judge only basic concept?

If you could judge this proposal is appropriate, we will be able to move to next step.

We will have to have meeting with other motorcycle OEM members. And I have to take their opinion into consideration to decide final answer to your detail questions.

Of course, we will answer and report at next step.

Would you mind letting know what level we have to answer for your judgement?

**Comment by joeygrover** [comment]
The purpose of the evolution process is not for agreeing to high level concepts or policies. Therefore without the additional technical details attached to this idea, it is not possible to accurately judge or provide a vote of acceptance on such a proposal. While the SDLC can see benefit in pursuing SDL for Motorcycles, it is not possible to give an open ended approval on such a feature until all the information is provided and properly reviewed. However, because of the commonly seen benefits through the SDLC, it should be possible for the author to move forward on what they see as their next steps. I would ask for a vote to defer this proposal and the previously mentioned group should meet to find all technical details and information such as hardware requirements, protocols, languages, and other information to provide a technical proposed solution on how this feature would be implemented. Once the author has compiled all that information it would be possible for the SDLC to bring this proposal back into review. At that time, the concept along with the technical details can be judged and voted on as a whole proposal.

**Comment by theresalech** [comment]
Per the author's request, the Steering Committee voted to keep this proposal in review.  The author will review the latest comment from the Project Maintainer internally and respond on the issue with any details that can be provided.  It was noted that during the next Steering Committee meeting, pending discussions on this issue prior, we can ask to defer the proposal in favor of a separate meeting among motorcycle OEMs to discuss technical details and requirements for feature implementation.  Once that meeting has taken place, the author can provide their proposed solution on this issue, and we can bring the proposal back into Steering Committee review to decide on revisions.

**Comment by Shohei-Kawano** [comment]
4. Many are developed in C, so it will be C.
5. We will not use JSON etc. to make it lightweight. I think we create something new.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal.  The author will meet internally to secure answers to the technical questions posed on the review issue.  Once the author is able to answer the remaining technical questions, he can email SDLC@smartdevicelink.com, and the proposal can be brought back under Steering Committee review.

**Comment by theresalech** [comment]
Closing as inactive. The issue will remain in a `deferred` status and unlocked so the author can notify the Project Maintainer when it is ready to be revisited.
