### ISSUE TITLE
[Withdrawn] SDL 0307 - Get Input Screen

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1026]
Hello SDL community,

The review of "SDL 0307 - Get Input Screen" begins now and runs through September 29, 2020. Previous reviews of this proposal took place June 2 - 16, 2020 and July 22 - August 18, 2020. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0307-GetInputScreen.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1026

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. These are traditionally called `Form`s. Would `DisplayForm` or `PerformFormInput` be better? Then replace `Field` with `FormField` or `FormRow`?

2\. `type="Common.Field"` is in the MOBILE_API but it's specific to the HMI_API. The `Common` part should be removed from all MOBILE_API XML APIs.

3\. `<param name="errorMessage"` and `<param name="error" type="Boolean" mandatory="false">` This is odd. It would have to be set when the screen first appears. I don't see how the screen could later be updated to show it based on the input. Would the developer have to present the screen again to show the error message? That doesn't seem obvious to me. Some flowcharts showing how app developers are intended to use this API would be helpful.

4\. There are no additions to `TextFieldName` nor `ImageFieldName`. Is this intended to be required for HMIs to support? If not, how does HMI / Core declare that there's no support for this RPC? How does an HMI declare how many fields / soft buttons are supported?

5\. One of your screens shows `isPrivate=true` but there's no `isPrivate` in the XML API.

6\. There are no additions to the HMI_API.

7\. One of your screens shows `Field.errorMessage` but there's no `errorMessage` in the XML API.

8\. One of your screens shows `description` (where the ? goes) but there's no `description` in the XML API.

9\. One of your screens references `graphic` but there's no `graphic` in the XML API.

10\. Instead of `maskInputCharacters`, it would seem that `KeyboardProperties` (see [SDL-0238](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0238-Keyboard-Enhancements.md)) would be better (outside of `KeyboardProperties.keypressMode` and `KeyboardProperties. autoCompleteList` since that only works if you get per-key responses). 

Perhaps it would be better to provide per-key input for form fields, by telling the developer which form field keyboard was activated. That way, the developer could provide autocomplete information by updating `SetGlobalProperties`. This would certainly be a more complicated solution, I'm just trying to not duplicate APIs and provide for autocomplete. If we just used `KeyboardProperties` (even if some properties didn't work), that would give you `language`, `customizable keys`, etc.

11\. I think additional field types are possible, e.g. a `Switch`, and `Date / Time input`. This would complicate the response.

12\. I don't like how the response works. It requires the dev to compare the array they sent with the array they receive and the responses to be in the same places in the array. Corresponding the response value with the field name would be preferred.

13\. How does a `COMBO_BOX` type `Field` work with the initial `text` input? Does the text have to match a `comboBoxChoices` option? What happens if they don't match?

14\. This is a minor point, but I think showing an example screen like how Netflix / Hulu / other video providers tie to a pre-existing account by having the user go to a URL to get a code and punch it in would be helpful. That's a better solution for devs who can implement it than punching in a username / password. This is similar but reversing Alternative 1 (though it is not numbered).

15\. This is a minor point, but I'm unsure how this would be implemented with 3rd-party sign-in like Apple, Google, Facebook, etc. sign in. Is there any idea about how OAuth would be implemented here (which requires the user to navigate to a URL). I understand if that's outside the scope of this proposal, but would request that be at least a downside, e.g. "This form process does not support OAuth logins like Google, Apple, or Facebook).

16\. This is a larger point. Because this is implemented as a series of modal screens, I think this could provide a poor UI to the user. For example, the user punches in their information, and presses submit. The modal disappears, then 5 seconds later (due to network timing), a new dialog pops up with an error. After the user punches that in, 5 seconds later, the next screen appears. There isn't even a loading indicator while waiting. That kind of pop-up/down would be rather awkward in the best circumstances.

More ideally this would be implemented as a template or something persistent. That becomes trickier, however, because there would then have to be some sort of RPC to display that information on a template, which wouldn't work on other templates.

17\. Is there intended to be an app library manager-level API for developers to use when implementing this?

**Comment by MichaelCrimando** [comment]
@joeljfischer ok I opened up PR #1032 with my running changes

1. Agree with that, changed from GetInpuit to DisplayForm.
2. Ok done.
3. Yea thats currently how I planned it. Do you have any ideas on how to do a more live update version?
4. I don't know what you're talking about here tbh
5. Fixed screenshot
6. Added HMI API
7. Fixed screenshot
8. Fixed screenshot
9. Fixed screenshots
10. I did use that SDL proposal for this... unless I'm missing somethin
11. Can you elaborate a bit?
12. See others were thinking that they didn't like the response either but didn't come up with any better solutions. What if we have a CMDid for everything?
13. Here's what I'm thinkin: they can have an inital text of whatever and it would be up to the app to decide what to do if it stays the same. Some apps might see it as an optional field and not care. Or some might do an error message
14. Yea that would definitley be helpful. But we could do something like that with a `ScrollableMessage`. That said, if an app partner can't hook that up for some reason, we would like to have the login possible.
15. Added downside
16. That's a solid point. Now remember that we have the NextRPCIndicator that we can use. So the HMI could show a loading screen until the next RPC comes up. Even if the next RPC is expected to be something else but the user entered their info wrong and a new Displayform comes up.
 https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0250-NextRpcIndication.md
17. I was thinking no. What do you think?

**Comment by joeljfischer** [comment]
1-2\. 👍 

3\. You could use an additional RPC to update a currently presented `Form`. However, to do this dynamically (e.g. the dev would need to know the present input of every Form). I think the way you have it is fine, but I'd ask for a flowchart (with RPCs being sent and the state of the screen) to explain how this is intended to work. As I said above, I think that the current proposal doesn't make it clear that new screens are at work here.

4\. There are enums in the MOBILE_API spec called [`TextFieldName`](https://github.com/smartdevicelink/rpc_spec/blob/develop/MOBILE_API.xml#L753) and [`ImageFieldName`](https://github.com/smartdevicelink/rpc_spec/blob/develop/MOBILE_API.xml#L872) that are intended to help HMIs declare what text and image fields are supported (e.g. if a primary `graphic` can be displayed on screen.

The issue is that this proposal has no capability support for HMIs to declare if they support this or not, or parts of it, etc.

5-9\. 👍 

10\. You did with the `KeyboardInputMask`, I'm asking for a more extensive implementation that allows additional capabilities with the keyboard since it seems to be important here. However, remember that SDL-0238 is not currently implemented, so any dependence upon it requires that this proposal not be implemented until simultaneously or after that proposal is.

11\. Upon further consideration, I think that the current form inputs adequately cover the use cases I was going to bring up.

12\. I don't think that's necessary. I think you should just return with `Field` structs with only `label`, `type`, and `text` filled. It's not great, but the alternative is to create _another_ struct that duplicates only those properties.

13\. I think that's fine but should be explained in the description.

14\. I think that you should maybe include that in an alternative 2, and / or state that it should be documented in any guides as an option.

15\. 👍 

16\. I don't think that that works because it would (1) require a parameter that pre-defines what the next RPC will be, and (2) the dev doesn't necessarily know what the next RPC will be until after the user has submitted the form and the dev has potentially sent the info to a remote server and received a response (e.g. will it be another form because the input was invalid or will it be a change template because it was valid).

17\. I think it would be a giant pain to implement as a dev if there isn't one. It's okay if you choose no, but realize that devs can currently implement 80%+ of what they do with SDL with the manager layer and more is coming. If you _don't_ include a manager layer now, you will want to later, and it will reduce the ability of devs to implement it who are used to the manager system.

**Comment by joeljfischer** [comment]
18\. I think this needs to support [cancellation](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0184-cancel-interaction.md).

**Comment by MichaelCrimando** [comment]
@joelfischer 
Remaining open points:
_3. Still open, will work on it_
4. Added section for `TextFieldName` and `ImageFieldName`
10. Noted in impact on code
_12. Still open, will work on it_
13. Noted OAuth and potential to use a PIN to login in the downsides and alternatives
14. Noted OAuth and potential to use a PIN to login in the downsides and alternatives
17. Added section for SDLFormManager 
18. Added

**Comment by MichaelCrimando** [comment]
@joeljfischer can you give PR #1032 a review? I think I addressed everything you asked

@theresalech I'm out of the office till next Wednesday and Joel is out of the office for a few days. Should we delay this for review a week?

**Comment by theresalech** [comment]
@MichaelCrimando if you've confirmed the changes needed for all of the comments, we can ask the Steering Committee to vote to return this proposal for revisions.  It would be helpful if you could leave a summarizing comment here of what those revisions should contain (answers to the 18 points discussed above).  Otherwise, we can ask the Steering Committee to vote to defer this proposal, and bring it back into review when you're available to continue the discussion about changes needed.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal until the author is able to respond to the latest comments, and summarize the desired revisions.  The author should email sdlc@smartdevicelink.com when they're able to do so.

**Comment by theresalech** [comment]
The author has advised that this proposal is ready to be brought back into review, pending Steering Committee vote.

**Comment by theresalech** [comment]
The Steering Committee voted to bring this proposal back into review, as the author (@MichaelCrimando) is able to respond to the latest comments and summarize desired revisions.  This proposal will remain in review until July 28, 2020.

**Comment by joeljfischer** [comment]
@MichaelCrimando I think that what we're looking for before we can return for revisions are the exact changes. I'll try to lay out the status here.

1. Author to revise `GetInput` to `DisplayForm` for the RPC and associated changes.
2. Author to revise to remove `Common` from MOBILE_API.
3. Author to revise to add a sequence diagram explaining how a mobile developer displays additional screens when errors occur.
4. Author must provide here the changes for review of `TextFieldName` / `ImageFieldName`.
5. Author to revise to fix diagram.
6. Author must provide here the changes for review of HMI_API changes.
7-9. Author to revise to fix diagram.
10. I'm looking to understand how this is supposed to work with 0238. Is the parameter, `inputMask` supposed to override `KeyboardProperties.maskInputCharacters` in `SetGlobalProperties` as 0238 describes? Are any other new properties from `KeyboardProperties` relevant? If you're intending to use `SetGlobalProperties` instead, how would that work with the different fields? So I think you just need to clarify there (I think the first question is probably the one that gets answered "yes"?), as well as indicate in the impact that it requires 0238 to be implemented before this proposal can be implemented.
11. Nothing to do here.
12. Author must provide here the changes for review of the response updates.
13. Author to revise to update description about combo boxes that don't change and what a developer should do.
14. Author to revise to note OAuth as an alternative solution.
15. Author to revise to add a downside regarding 3rd party login solutions.
16. Author to respond.
17. Author must provide here the changes for iOS / Java Suite / JavaScript Suite screen manager updates for review and discussion.
18. Author to revise to add a `cancelId` parameter to the `GetInput` RPC.

So, I think there's some confirmation to do on 4, 6, 10, 12, 16, 17,

**Comment by MichaelCrimando** [comment]
@joeljfischer 
everything done in #1032 
To answer 7- Yes it would override the global properties. No other things from the Keyboard Enhancements was considered for this. We're just kinda leveraging an existing enum to help us out

**Comment by joeljfischer** [comment]
Hi @MichaelCrimando, having it in a PR isn't enough. Please respond to comments here to keep them in the flow of comments. Having to reference a changeable source like a PR will only lead to confusion.

**Comment by MichaelCrimando** [comment]
@joeljfischer 

1. Agree with that, changed from GetInpuit to DisplayForm.
2. done.
3. added sequence diagram
4. Added section for TextFieldName and ImageFieldName
5. Fixed screenshot
6. Added HMI API
7. Fixed screenshot
8. Fixed screenshot
9. Fixed screenshots
10. Noted in impact on code
11. Nothing needed
12. Ok changed the response
13. Noted OAuth and potential to use a PIN to login in the downsides and alternatives
14. Noted OAuth and potential to use a PIN to login in the downsides and alternatives
17. Added section for SDLFormManager
18. Added

**Comment by joeljfischer** [comment]
@MichaelCrimando, stating things like "fixed screenshot" and "noted in impact" isn't good enough. _Please post your exact changes for review and discussion_.

**Comment by MichaelCrimando** [comment]
@joeljfischer honestly with this many changes, itd probably just be easier for everyone to look at the newest PR and start from there. Whats the official way to do that?

**Comment by joeljfischer** [comment]
@MichaelCrimando You have two options: (1) discuss them in this forum as I've asked, (2) request that your proposal be rejected and start from scratch with a new proposal.

**Comment by MichaelCrimando** [comment]
@joeljfischer ok updated comment above

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow time for the PM to respond to the most recent comment from the author in order to finalize the summary of desired revisions.

**Comment by joeljfischer** [comment]
3\. The diagram that @MichaelCrimando is referencing is:
![sequence diagram](https://github.com/smartdevicelink/sdl_evolution/blob/2d23aca6e6fa74b9ad8f8792f89acc244b0684b8/assets/proposals/NNNN-GetInput/GetInput-ErrorFlow.PNG?raw=true)

5,7,8,9\. This is the new wireframe @MichaelCrimando  is referencing:
![wireframe](https://github.com/smartdevicelink/sdl_evolution/blob/2d23aca6e6fa74b9ad8f8792f89acc244b0684b8/assets/proposals/NNNN-GetInput/GetInput-3-2.PNG?raw=true)

11\. The new language is: `This form process does not support OAuth logins like Google, Apple, or Facebook).`

12\. The new language is: `It's a new parameter so this would not affect older SDL versions. It would be a minor version change for affected mobile libraries. This is dependent on 0238-Keyboard-Enhancements`

13\. The new alternatives language is: `If an app desires, they can give the user a PIN number via an on-screen alert instead and have the user go to their website and enter the PIN there as a login.`

**Comment by joeljfischer** [comment]
3\. LGTM

4\. Thank you for providing that. The only question that I'm wondering is if we need four separate texts here. I'm thinking about how difficult it would be, for example, for an app to support head units that both do and don't support format or what kind of an experience it would give for a head unit to not support the label argument. 

Here's my thinking, we only provide a `TextFieldName` for `formFieldLabel` with a description that includes text like "If this is not present, the app may assume that `DisplayForm` is unsupported. If it is present, it is assumed that all features other than `image` are supported." Then in the proposal, there would need to be text like, "If the HMI intends to support `DisplayForm`, it must support the `label`, `text`, `format`, `additionalInfo`, `error`, `comboBoxChoices`, and `inputMask` parameters." Without any of those, the usability of this feature for end users suffers, and the ability for an app to provide a consistent experience becomes much more difficult. The image, I think, should remain optional though.

5, 7-9\. LGTM

6\. I think you missed adding the `DisplayForm` updates in your comment above? I think your `DisplayForm` update in the PR is missing the namespace (probably `UI.`?)

10\. If that's your position, comment should be added stating that the keyboard global properties will be ignored. However, ignoring things like language is obviously not desired. So I think your statement has to be explicit about which `SetGlobalProperites` are going to be ignored (including those from 0238 since this is dependent on it) and which will not be ignored.

12\. Remember that all responses have the same basic parameters. You don't have to include those, but you should have a comment noting that you're assuming the existence of those parameters (`success`, `info`, etc.). Additionally, we usually try to avoid array `mandatory=true` parameters with `minSize=0`. We usually make it optional instead with a `minSize=1`. I think that's the better way to go here (think about if there's an error).

13\. This seems to be different than what we agreed to and I don't think this is the right approach; additionally, I think that putting this in the parameter description is better than the proposal text in this case. The approach we'd agreed to was to simply send it back to the app and let it do what it wants. For example, if the field is optional, the app can ignore it. Or, if the default value is one of the options, the app can use that option. Or, the app could view it as an error. As you've phrased it, it sounds like Core or the HMI has to throw an error at the user until they make a selection.

14-16\. 👍 

17\. This seems to be missing a class name and the screen manager changes.

18\. 👍

**Comment by MichaelCrimando** [comment]
@joeljfischer 
4. Agreed. Updated in PR with "If this is not present, the app may assume that `DisplayForm` is unsupported. If it is present, it is assumed that all features other than `image` are supported." 
6. Hmm what do you mean? I don't see a UI namespace anywhere in the Mobile api or HMI Api
10. Added a line
`The main goal of this is to leverage an existing enum to help us out. `maskInputCharacters` mask will override `KeyboardProperties.maskInputCharacters` in `SetGlobalProperties`.`
12. Fixed all cases of minsize=0 to minsize =1.  I'm not sure what you mean here about `success`, `info` etc
13. Ah ok, reverted the mention of "If a combo box is requested, the user is required to pick something besides the default value." and changed it to "If a combo box is requested, and the user doesn't pick anything, the HMI will send back the field.text and then it's up to the app on what to do."
17. In objc isn't the classname just the filename.h?  I don't think I can honestly provide the `ScreenManager` changes that's getting significantly over my head but I feel like someone well versed on `ScreenManager` could reasonably figure out the intent we're going for here

**Comment by joeljfischer** [comment]
4\. 👍 
6\. We usually put `UI.Alert` in proposals, for example, to specify that it's in the [`UI` namespace](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L5003)
10\. Looks good, but maybe add one additional sentence to clarify the status of the other `SetGlobalProperties`? Like:

> The main goal of this is to leverage an existing enum to help us out. `maskInputCharacters` will override `KeyboardProperties.maskInputCharacters` in `SetGlobalProperties`. All other keyboard-related items in `SetGlobalProperties` will work normally.

12\. If you look at [any RPC response](https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L4687), you'll see that they all include three items: `success`, `resultCode`, and `info`. The `resultCode` description contains the information about which codes are valid for this RPC. I'm just asking you make it clear that those items are included in the response you are proposing.

13\. 👍 

17\. No, they often match, but aren't required to, and you don't specify the filename anyway. You declare a class this way:

```objc
@interface SDLClassName : SuperclassName

@end
```

You don't have to provide manager changes, but understand that without them, most developers will neither know that this feature exists, nor are likely to want to use the raw RPCs. Ford must have people familiar with the screen manager system that would be willing to help you. There's also [good documentation](https://smartdevicelink.com/en/guides/iOS/displaying-a-user-interface/template-text/) for each platform if you want to get an idea of how it works. I would recommend coming up with at least one platform's screen manager interface and giving the project maintainer the explicit latitude to create the other platforms' based on that first platform. I apologize that I cannot help further at this time.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, so that the author can respond to the remaining open items (6, 10, 12, and 17) on the review issue.

**Comment by MichaelCrimando** [comment]
@joeljfischer 

6. Do you have an example? I abused Github search anyway I could and never found anything with `UI.` in it
10. Ok done, added that change
12. Ok added fields to response
```xml
<param name="success" type="Boolean" platform="documentation" mandatory="true">
    <description> true if successful; false, if failed.</description>
</param>

<param name="info" type="String" maxlength="1000" mandatory="false" platform="documentation">
    <description>Provides additional human readable info regarding the result.</description>
</param>

<param name="resultCode" type="Result" platform="documentation" mandatory="true">
    <description>See Result</description>
    <element name="SUCCESS"/>
    <element name="REJECTED"/>
    <element name="INVALID_DATA"/>
    <element name="INVALID_ID"/>
    <element name="DUPLICATE_NAME"/>
    <element name="DISALLOWED"/>
    <element name="OUT_OF_MEMORY"/>
    <element name="TOO_MANY_PENDING_REQUESTS"/>
    <element name="APPLICATION_NOT_REGISTERED"/>
    <element name="GENERIC_ERROR"/>
</param>
```

17. ok ill look into it

**Comment by joeljfischer** [comment]
6\. https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0242-alert-style-subtle.md#hmi_api-changes
10\. 👍 
12\. 👍

**Comment by MichaelCrimando** [comment]
Ok added the UI. to the function name in the HMI_API 
```xml
<function name="UI.DisplayForm" functionID="DisplayFormID" messagetype="request">
```

**Comment by theresalech** [comment]
It appears the author and PM have come to a resolution on all items in discussion.  I've summarized the agreed upon revisions below.  It's the PM's recommendation that the Steering Committee vote to return this proposal for these revisions.

1\. Revise `GetInput` to `DisplayForm` for the RPC and associated changes.

2\. Revise to remove `Common` from MOBILE_API.

3\. Add "Error Message Flow" diagram to `Proposed solution` section.

4\. Update `TextFieldName` to include `formFieldLabel` with a description similar to "If this is not present, the app may assume that `DisplayForm` is unsupported. If it is present, it is assumed that all features other than image are supported." Update `ImageFieldName` to include `formFieldImage`. Include the following language in proposal:
>If this is not present, the app may assume that `DisplayForm` is unsupported. If it is present, it is assumed that all features other than `image` are supported.

5, 7, 8, 9\. Add wireframe included in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1026#issuecomment-666637651) 

6\. Include the HMI API Changes outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1026#issuecomment-665205753), with `DisplayForm` and `UI.DisplayForm` included.

10\. Add the following to `Proposed solution` section:
>The main goal of this is to leverage an existing enum to help us out. `maskInputCharacters` will override `KeyboardProperties.maskInputCharacters` in `SetGlobalProperties`. All other keyboard-related items in `SetGlobalProperties` will work normally.

12\. In MOBILE_API, update `GetInput` to `DisplayForm`, with the following:
```
<function name="DisplayForm" messagetype="response">
  <param name="success" type="Boolean" platform="documentation" mandatory="true">
    <description> true if successful; false, if failed.</description>
  </param>
  <param name="info" type="String" maxlength="1000" mandatory="false" platform="documentation">
    <description>Provides additional human readable info regarding the result.</description>
  </param>
  <param name="resultCode" type="Result" platform="documentation" mandatory="true">
    <description>See Result</description>
    <element name="SUCCESS"/>
    <element name="REJECTED"/>
    <element name="INVALID_DATA"/>
    <element name="INVALID_ID"/>
    <element name="DUPLICATE_NAME"/>
    <element name="DISALLOWED"/>
    <element name="OUT_OF_MEMORY"/>
    <element name="TOO_MANY_PENDING_REQUESTS"/>
    <element name="APPLICATION_NOT_REGISTERED"/>
    <element name="GENERIC_ERROR"/>
  </param>
  <param name="fields" type="Field" maxlength="500" array="true" minsize="1" maxsize="100" mandatory="false">
    <description>
      This will return an array of Fields that have the same type and label as requested, but with the text field populated.
    </description>
  </param>
</function>
```

13\. Include the following to `Proposed solution` section:
> If a combo box is requested, and the user doesn't pick anything, the HMI will send back the field.text and then it's up to the app on what to do.

14\. Add the following to `Potential downsides` section:
> This form process does not support OAuth logins like Google, Apple, or Facebook).

15\. Update `Impact on existing code` section to the following:
>It's a new parameter so this would not affect older SDL versions. It would be a minor version change for affected mobile libraries. This is dependent on 0238-Keyboard-Enhancements.

16\. Update `Alternatives considered` section to the following:
>If an app desires, they can give the user a PIN number via an on-screen alert instead and have the user go to their website and enter the PIN there as a login.

17\. Specify that this proposal doesn't include manager changes.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for the revisions included in [this comment]( https://github.com/smartdevicelink/sdl_evolution/issues/1026#issuecomment-675680436).

**Comment by theresalech** [comment]
The author has updated this proposal based on the Steering Committee's agreed upon revisions, and the revised proposal is now in review until September 29, 2020.

The specific items that were updated since the last review can be found from this merged pull request: https://github.com/smartdevicelink/sdl_evolution/pull/1079.

**Comment by joeljfischer** [comment]
I'm going to restart numbering:

1\. The proposed solution states: `Add a new RPC for an input screen. This screen would use RPC encryption which is handled by policies. It contains a title, and an array of InputLines`. I believe that "InputLines" should be "Fields".

2\. Based on the sentence I quoted in (1) and elsewhere, it sounds like this is required to use RPC encryption. We either need to add a new mechanism to force RPCs to use RPC encryption in Core and policies (in which case this proposal needs to be expanded), or we will need to add Core certification tests that need to be specified in this proposal, or this line needs to be changed to say "should". I don't know that we have another mechanism to require something like this at this time.

I understand the need because credit card details and passwords ought to be encrypted, I'm just saying we don't have a mechanism to require that. Without encryption though, especially on Java Suite, credit card details will be able to be read by other apps via the router service, which is extremely bad.

I would be in favor of adding a new XML attribute like `encryptionRequired = true`, but again, that would require larger Core changes.

3\. For relevant `TextField`s, we should include one mandatory text field (to have an indicator if the feature itself is supported), and every optional text field / image field (so that developers know if they need to use an alternate way of using the feature). 

So for the first part, I think you're good with `formFieldLabel`, though I think that `FormInitialText` would be better to know if the feature itself is supported. But I think you're missing optional text fields: `FormErrorMessage`, `FormFieldText`, `FormFieldFormat`, `FormFieldAdditionalInfo`, `FormFieldError`, and `FormFieldComboBoxChoice`. If this is not included, I think there needs to be a note stating that it needs to be added to the HMI Integration guidelines that _all_ features and fields for `Form`s must be implemented if _any_ are. In other words, the whole feature needs to be implemented if it's going to be implemented at all.

4\. I think descriptions need to be added to every parameter, struct, and function because that documentation is used to generate the app library documentation. `Field.type` is missing, for example.

5\. The proposed solution is difficult to follow. I would appreciate if it were broken up further by sub-headings like "response", "fields", etc.

6\. `TextFieldName` changes seem to be missing from the `HMI_API`.

7\. I think potential downside 3 can be expanded to say "Soft button ids managed by the screen manager may conflict with soft button ids managed by the developer for this RPC and may lead to app bugs. This can be worked around by the developer using large soft button ids that are unlikely to conflict with the screen manager's soft button ids."

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow the author time to respond to the comment provided on the review issue.

**Comment by MichaelCrimando** [comment]
Still workin just gotta checkpoint
1. Agreed, fixed in PR #1081 
2. Hmm agreed that we need encryption and imo it should be required for this, so what do you suggest we do on the proposal?
3. 
4. Agreed, updated in the PR to have a quick description for everything
5. Ok reorganized a bit so there's a "Request", "Response" and "Declaring Support" section
6. 
7. Ok added that text

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow for further discussion on the review issue. The following open items were also discussed during the call:

2\. The PM stated that since the feature would need a new mechanism to require encryption, a new proposal should be submitted to add the mechanism. This proposal would include a new XML attribute in the RPC Spec as well as SDL Core changes. The author noted he would investigate this further.

3\. The PM advised that there's currently no way for the developer to know if the optional `TextFields` are available, so would recommend specifying within this proposal that the HMI Integration Guidelines should be updated to state that if this feature is implemented, it must be implemented in its entirety (with all fields supported). The other option would be to add extra `TextFieldNames` to allow an OEM to declare what they support, but this would require more effort on the developer and/or managers to work around systems with different levels of support. The author agreed with the PM's recommendation to update the HMI Integration Guidelines.

**Comment by MichaelCrimando** [comment]
2. Alright figured out a way to ensure this using the technology we already have.  In policies, we would have a new permission group that requires encryption by setting the flag `Encryption_Required = true` . This `DisplayForm` RPC would be in that permission group. SDL Core will make sure that only encrypted `DisplayForm` RPCs will be accepted and processed. Unencrypted `DisplayForm` RPCs will be rejected. The response sent back to the app will also be encrypted.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for the following revisions:

1. In the following section, change "InputLines" to "Fields":
>Add a new RPC for an input screen. This screen would use RPC encryption which is handled by policies. It contains a title, and an array of InputLines
2. Note that this feature will require using RPC encryption, and therefore will be dependent upon a separate proposal that introduces a mechanism to force RPCs to use RPC encryption in Core and policies. This proposal cannot be accepted until that separate proposal is reviewed and accepted.
3. In `Proposed solution` section, add "Declaring Support" subsection, with the following text:
>Apps need this RPC to be consistent across all OEMs so that they don't have to make different implementations per OEM. So the HMI Integration Guidelines need to be updated to state that if this feature is implemented, it must be implemented in its entirety with all fields supported. Images are the only optional component.
4. Add descriptions to each parameter, struct, and function provided within the proposal.
5. Add "Request", "Response", and "Declaring Support" subsections within `Proposed solution` section.
6. Add `TextFieldName` to `HMI_API` changes, as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1026#issuecomment-704268593).
7. In the `Potential downsides` section, add the following text to item 3:
>Soft button ids managed by the screen manager may conflict with soft button ids managed by the developer for this RPC and may lead to app bugs. This can be worked around by the developer using large soft button ids that are unlikely to conflict with the screen manager's soft button ids. 

Before the Steering Committee vote, additional discussion took place regarding item 2. It was noted that changes to Core and the RPC Spec (Mobile API XML) would need to be described in the separate proposal, and suggested adding an attribute like `encryptionRequired = true` as a starting point. There would then be a check within Core to see if an RPC is sent encrypted, and the RPC would be discarded for features (like Get Input Screen) where RPC encryption is required.

Regarding next steps for acceptance of this proposal, the new proposal (described in item 2) will first need to be submitted, reviewed, and accepted. We can then bring this revised proposal (SDL 0307) back into review, and look to "Accept with Revisions", where the revisions would include adding a link to the newly accepted proposal that describes the RPC encryption requirement mechanism.

**Comment by theresalech** [comment]
This proposal has been withdrawn per the author's request.
