### ISSUE TITLE
[Accepted with Revisions] SDL 0033 - Streaming Media Manager 5.0

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#103]
Hello SDL community,

The review of "Streaming Media Manager 5.0" begins now and runs through March 14, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0033-streaming-media-manager-update.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/103

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by Toyota-Sbetts** [comment]
> This should be built as a non-customizable screen, so that we can rely on consistent behavior among streaming applications for the time being. The current idea is to have a black screen with the text “Please re-open <#App Name#>”.

Any way we can provide additional options for handling this situation?  This suggestion may not be acceptable to all OEM's HMI guidelines and we feel the HMI should have the ability to determine how to notify the user to re-open the app.

**Comment by asm09fsu** [comment]
@Toyota-Sbetts You are welcome to come up with and propose additional options alongside this.

**Comment by Toyota-Sbetts** [comment]
@asm09fsu Thanks for the feedback and we understand this stance.  Overall our recommendation would be to separate this portion out from this proposal into it's own proposal as we think this needs to be discussed and considered more.  First and foremost, Toyota cannot accept any recommendation for the user to operate their handset while driving which is necessary to re-open the app so at the very least we would need to modify the suggested message.  When we consider the applicable laws, rules and regulations for every region SDL might be utilized in a catch all behavior may not cover all cases so it needs to either comply with the strictest rules or be customizable.

**Comment by asm09fsu** [comment]
@Toyota-Sbetts There are multiple solutions that can be used here:

1. In protocol version 4, the core and mobile sides both accept for the mobile side to send an HMI status of the connected phone. You can see that function [here](https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLProxy.m#L394) and [here](https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLProxy.m#L145). Because of this, core would know the state of the mobile side, and when the mobile side informs core that it has gone into BACKGROUND, Toyota (and all other OEMs) could show their own HMI relating to this, and ignore any frames sent over at this time.

2. We allow for a customizable string parameter in `SDLLifecycleConfiguration` that allows the developer to specify the text they would like to display on the HMI. We would need to provide a maximum string size for this, as larger displays can allocate for more text vs smaller sizes. 

3. There is a more definitive string that complies with the strictest rules and laws that we would like to be in accordance with.

Regardless, we must solve this solution for both existing and future implementations of Mobile Navigation (so, protocol version 3 that does not support onHMIStatus notifications from mobile->core).

**Comment by pelsila** [comment]
Review is extended until 3/21/2017

**Comment by joeljfischer** [comment]
@Toyota-Sbetts @asm09fsu I believe that option 1 that Alex listed above is the best option here, because it provides the OEM the power to show whatever screen they want if a nav app goes into the background. The biggest downside is that it requires Core changes to accommodate this solution, and would therefore require more time and money to actually roll that portion of this proposal out, and then what do we do in the meantime.

The second best option here is option 3, in which the committee unilaterally decides on the best string for use. We must then consider localization as well.

The worst option here is option 2, I don't think we want app developers to have to specify this text.

**Comment by Toyota-Sbetts** [comment]
@joeljfischer From the SDLC meeting, my understanding is that option 1 was already planned/implemented for protocol v4, is this not the case?  If not, I agree that in future version we should support this option.

Option 3 was in regards on how to best handle the legacy (current) implementation.  We agree that some default is necessary but we need to be very careful about what the decided option is.

@All Toyota is still discussing internally on our recommendation for the string and due to many members being out of office we weren't able to come to a conclusion. I need to ensure whatever we recommend here is vetted through our HMI team and possibly legal.  In order to unblock the rest of this proposal, we still think this topic should be removed and made into it's own proposal.

**Comment by joeljfischer** [comment]
@Toyota-Sbetts Regarding 1, not in core. It is not even planned. It would have to be part of that separate proposal, I think.

I do want to note that Option 2 / 3 will work without SDL Core changes, while Option 1 would require an SDL Core update. For that reason Options 2 / 3 should be preferred, at least as a temporary measure. I agree that the two segments of this proposal should be separated.

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal, with the following text removed from the “Sending video data when iPhone is moving to background” section: “Please re-open <#App Name#>”.  For now, the screen will default to black, as the committee has not yet agreed upon the text that should be displayed.  Toyota will submit a separate proposal for this text once they’ve confirmed their recommendation with their appropriate teams internally.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0033] Streaming Media Manager 5.0](https://github.com/smartdevicelink/sdl_ios/issues/583)
