### ISSUE TITLE
[Withdrawn] SDL 0314 - Clarification of SDL app icon display sequence and display order

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1065]
Hello SDL community,

The review of "SDL 0314 - Clarification of SDL app icon display sequence and display order"  begins now and runs through August 11, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0314-Clarification-of-SDL-App-Icon-display-sequence-and-display-order.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1065

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
1\. I don't believe this is just a clarification of how SDL Apps on displayed on the HMI. This proposal is adding a new feature and it should be updated to reflect that.
2\. I'm not sure if deciding app order based on HMI type is the best way to accomplish this. If I'm reading the proposal correctly it appears the author would like a way to dynamically order the apps that can be updated via the policy table. Maybe it makes sense to give weight/priority directly to the individual app entries in the policy table so that if an OEM wanted to promote a specific app or apps they could bring them to the start of the list. 
3\. Has the author thought about user defined sort order where the user can decide which apps should be at the start of the list? Does it make sense to include such a feature in this proposal?
4\. I believe the sort rules should include one rule that if the HMI priority is not present the list is either not sorted or sorted how it was previously sorted.

**Comment by Akihiro-Miyazaki** [comment]
@joeygrover -san,
1.
> This proposal is adding a new feature

A new feature what you say is app sorting order base on HMI type?
Is our understanding correct?
If correct, we will replace the sentence from "Clarification of rule of the icon display order" to "Set icon display order rules".
If wrong, could you please teach us  what is a new feature.

2.
👍

3.

> about user defined sort order

We have not thought it in this proposal.
Because we think that the users prefer to be free to move rather than sort order.
In addition, I think that the point of discussion will change because processing such as user operation methods will be added.

4.
Thank you for your advice.
We think so.
Therefore, we will add that if the HMI priority is not present the list is sorted how it was previously sorted.

**Comment by joeljfischer** [comment]
5\. Could you please clarify the need for this proposal? Doesn't Core provide the HMI with the list of apps and cannot the HMI then make its own decision on sorting the apps (for example, in alphabetical order). I don't believe that we need to enforce _any_ rules over display order but should provide the HMI with enough information to make its own decisions (e.g. user sort, alphabetical, install date, category, etc.). If we need to provide the HMI that's displaying apps for the user with additional information to be able to sort them in these various ways, we should do that, but I'm not happy with how this proposal is currently framed.

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,
In this proposal, I think that SDL Core will send the list of apps using `BasicCommunication.UpdateAppList`, as written between the RPC Service and the SDL Manager in Figure 1.
Also, this proposal adds only a sorting method to the current SDL Core software.
Therefore, if OEMs want to make an unique sort, they can do it in the HMI as it is.

**Comment by joeljfischer** [comment]
5\. Then based on your last comment, I don't believe this proposal is necessary. HMI developers should sort the applications as they desire based on the information in `BasicCommunication.UpdateAppList`. I see no need for Core to sort the applications in various ways.

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,
5.
What we propose is to provide the display sorting rule of SDL apps icon using the `appHMIType`.
Also, each OEM can decide the sorting order themselves by changing the `appHMIType` priority list in the policy table.
In addition, if the OEMs need to additional change, they will be able to implement on the HMI.
Because the SDL Core provides the same list as before.
We believe this proposal will help reduce the OEM implementation cost.

**Comment by joeljfischer** [comment]
5\. But this work seems needless. What is the point of that display sorting rule if most HMIs are simply going to display it in a different order? This seems to be placing the work to implement your preferred order in Core instead of your HMI where it belongs. This may reduce your OEM implementation cost, but it won't reduce it for any other OEM that has a different preferred order. Your HMI seems to have all the information necessary to display the apps in this preferred order. This logic, therefore, seems to be misplaced. The work to implement, review, and maintain this code therefore seems unnecessary to me.

**Comment by theresalech** [comment]
Hi @Akihiro-Miyazaki, I've summarized the comments on the issue below for visibility.  Please let us know your thoughts, thanks!

**Agreed upon Revisions**
2\. Give weight/priority directly to the individual app entries in the policy table
4\. If the HMI priority is not present, the list is sorted how it was previously sorted.


**Open Items**
1\. A new feature is an added component to any project.  Clarifying language is moreso explaining functionality (in the form of documentation) that is already present.  We'd therefore define adding the ability to sort applications order base on HMI type as a new feature.  We'd recommend updating the proposal name to `Dynamic App List Sorting`.

3\. Since this would be a feature that some OEMs would want, it would be helpful to include it as a way to sort applications along with the proposed and suggested ways. Since this specific sorting method would only be part of the HMI and have no other SDL component integration, we believe it could just be included into the HMI Integration Guidelines and Core Guides documentation update along with the updates that come from this proposal.

5\. See Joel's response above (https://github.com/smartdevicelink/sdl_evolution/issues/1065#issuecomment-673024846).

**Comment by Shohei-Kawano** [comment]
@joeljfischer -san, @theresalech -san
5.
I don't think that the individual should judge whether the proposal is useful or not. 
I think it's good to have OEM members vote on whether these suggestions are value it, what do you think?
At that time, I think it is good to get an opinion if there is content to be strengthened for the proposal.

**Comment by joeljfischer** [comment]
5\. OEM members and all Steering Committee representatives will vote on this proposal, and we'd certainly welcome any feedback they can provide during the meeting or on this review issue beforehand. We're simply providing our review of the feature, as we do all proposals, given our background and experience as the project maintainer.
To summarize this objection:
- The HMI should be responsible for sorting applications because (a) there are domains of sorting that are difficult for Core to address, such as user sort, (b) if we address sorting in Core, we will necessarily privilege one sort over others, (c) if we address sorting in Core, we must address all potential sorting options, maintain and continue to update that feature.
- The question of sorting in the HMI seems not to have been addressed in this proposal. It is said that it is "unclear" if this is HMI's responsibility and much time was spent to describe why Core's default ordering isn't fine as-is, but this could simply be confirmed that it is the HMI's responsibility to sort the apps based on the information given and then addressed in documentation.
- The question of adding additional capabilities to the policy server that modify ordering is an interesting and good point, but seems to be incidental to the rest of the proposal.
Therefore we believe the feature being proposed is something that should be handled on the HMI side, and is not advantageous for the SDLC to add to SDL Core, as preferred orders may likely vary from OEM to OEM implementation.

**Comment by Shohei-Kawano** [comment]
@joeljfischer -san
Our proposal is to sort the HMI List from Core based on certain rules.
OEMs may use the sorted products as they are, or they may further customize them.
I think it is better to avoid the current behavior of List changing every time. This is because OEM will always have to implement HMI sorting.

**Comment by joeljfischer** [comment]
@Shohei-Kawano I can understand that case, though I still believe it's unnecessary. However, I think that your proposed solution isn't a good one for that use-case since it's more specialized and complex. I think that a good, basic, general use-case would be to simply alphabetize the list. This would probably be only a few lines of code for the HMI, but if the steering committee wants the default ordering to be more comprehensible, I think that simple alphabetization is easy and general enough to work.

**Comment by Shohei-Kawano** [comment]
We will revisit the proposed policy.
So let me withdrawn this suggestion.

**Comment by theresalech** [comment]
This proposal has been withdrawn per the author's request.
