### ISSUE TITLE
[Deferred] SDL 0316 - Clarification of transport switching rules and improvement of UX

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1069]
Hello SDL community,

The review of the revised "SDL 0316 - Clarification of transport switching rules and improvement of UX" proposal begins now and runs through October 27, 2020. The review of the original proposal took place August 19 - September 8, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0316-Clarification-of-transport-switching-rules-and-improvement-of-UX.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1069

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. It's not made clear in the proposal, but it appears that this proposal is about switching _primary_ transports, not secondary ones. This should be made explicit.

2\. The proposal states:

> If the HU has recognized that current BT and new USB are connected to same device, SDL transport will switch to USB.

The diagram is a good start, but I think more details will be needed, for example, a configuration file is referenced in the diagram but the specification is nowhere in the proposal.

3\. The second set of footnotes (*1 and *2) don't seem to be linked to anything? I couldn't find what they were referencing.

4\. A note says:

> With the current SDL standard specification, the device cannot identify whether it is the same device or not. Therefore, device identification by the HU must be a prerequisite.

This proposal cannot be accepted without the prerequisites being a part of this proposal or previously accepted.

5\. A note says:

> The switching from BT to USB logic in the same device transport of iOS is already approved and implemented by the SDLC in SDL 0053 - Connectivity via iAP-BT and Transport Switch.

Therefore this proposal seems to be related to Android only. However, I believe many additional details are necessary. The Android library is also going to need to be able to switch primary transports, etc.

6\. Stating that there are no downsides seems a bit disingenuous. For example, the current system for Android devices where it will unregister and reregister doesn't seem to be too bad and this is a very complex addition. Additionally, the motivation doesn't seem to describe the current state of Android "transport switching", just how hard it is to implement this specific kind of transport switching (without an unregister / reregister).

**Comment by JackLivio** [comment]
7. The flowchart given in the proposal does not really match the flowchart depicted in the original iap transport switching proposal. My understanding of the proposal is that the switching process does not change with the exception of adding the new HMI notification, "OnDeviceSwitchStatus"?

8. The flow chart does not include the success case fo OnDeviceSwitchStatus when the app registers before the timer expires.

9. Flow chart is using misleading function calls such as "User app operations()", "HMI RPC communication()", "Apps Registered()".

10. If this proposal is intended for android too, then the connection process will be slightly different since Core's transports adapters handle the connections with the apps directly.

11. I think the proposal needs more details around the case of switching from bt+wifi to usb. This case is more complex because it involves switching from two active transports (primary+secondary) to one active transport (only primary). This case is not covered by the either of the transport switching or multiple transport proposals.

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,
1.
Yes. We think so.
Therefore, we will modify the word from "transport" to "primary transport".

2.
In this part, we do not propose the solution.
We clarify the only rule to switch the primary transport.
And, we will add the rule of switching the primary transport to the SDL Core document.

3.
We will add the referencing on the sequence diagram.

4.
We assume that the same device identification will be performed by the HMI.

5.
That's wrong.
In this proposal, it does not propose the switching mechanism, it is to notify the term which the user can not use the communication. If anything, it is a suggestion for iOS that has a switching mechanism.

6.
In this proposal, since it is to notify the term which the user can not use the communication, we think there is no downsides about this matter.

@JackLivio -san,
7.
Thank you for your comment.
That's right.
In this proposal, we think  that the switching process does not change with the exception of adding the new HMI notification, "OnDeviceSwitchStatus". Could you please teach us the difference points.
We will modify them.

8.
Due to switch the transport, the user can not use the communication.
The "OnDeviceSwitchStatus" is to notify the term which the user can not use the communication. It is not to notify the result of the switching transport.

9.
Could you please teach us the suitable names?
We will modify them.

10. 11.
In this proposal, it does not propose the switching mechanism, it is to notify the term which the user can not use the communication. Therefore, we think that the switching process is not need in this proposal.

**Comment by JackLivio** [comment]
7 & 9. I would suggest making a copy of the original [flow chart](https://cloud.githubusercontent.com/assets/11158516/26067529/3f428434-39a3-11e7-910b-6cc4069e0be3.png) and add the new notification usage to that copy.

8. I would suggest using this notification for success cases in addition to failures. Using the "FINISHED" enum to mark only a failure is not intuitive. My first thought was that "FINISHED" means the switch was successful. There should be a seperate enum for a failed switch.

```
<enum name="SwitchStatus">
   <element name="STARTED"/>
   <element name="FINISHED"/>
   <element name="FAILED"/>
</enum>
```

10 & 11. The proposal should include some language that this does not impact android and is only for the existing ios transport switching feature. The impact on existing code section should be updated with more detail since it does not say which parts of the proposal will impact the code.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review until our next meeting, to allow for additional time for discussion on the review issue.

**Comment by Akihiro-Miyazaki** [comment]
@JackLivio -san,
7 & 9.
We will add the new notification usage.

8.
Thank you for your comment.
We will modify the RPC and parameter like below.

```xml
<function name="OnDeviceSwitchStatus" messagetype="notification">
    <description> Notify HMI of the current state of the transport switch </description>
    <param name="status" type="Common.SwitchStatus" mandatory="true"/>
    <param name="switchingTransportResult" type="Common.SwitchingTransportResult" mandatory="false"/>
</function>

<struct name="SwitchingTransportResult" mandatory="false"/>
   <param name="switchingResult" type="SwitchResult" mandatory="true"/>
   <param name="failReason" type="Strings" mandatory="false"/>
</struct>

<enum name="SwitchStatus">
   <element name="STARTED"/>
   <element name="FINISHED"/>
</enum>

<enum name="SwitchResult">
   <element name="PASSED"/>
   <element name="FAILED"/>
</enum>
```

10 & 11.
We will modify like below on the part of introduction.
This proposal is to improve transport switching in the same device for Transport switching of iOS approved by "SDL 0053-Connectivity via iAP-BT and Transport Switch".

Also, we will modify like below on the part of Impact on existing code.
Since this proposal adds a new RPC and some parameter, the following existing code are affected.
- RPC : Add a new RPC and some parameters.
- SDL Core : Add the process to send a new RPC to HMI.
- HMI : Add the process of receiving a new RPC.

By the way, we have a question about your comment.
What does this word "some language" show? Program language, platform or other?

**Comment by JackLivio** [comment]
7&9. 👍 Looking forward to the change.

8. 👍 I agree with these hmi api revisions.

10&11. 

Thank you. "Some langauge" meaning a statement or description. What you have proposed addresses my issue. One extra change would be to remove RPC from impacted platforms. The HMI API is seperate from the Mobile API (RPC Spec).

**Comment by joeljfischer** [comment]
1\. 👍 
2\. 👍 
3\. 👍 
4\. Are you saying that you want the HMI to display a message to the user while the transport is being switched? This is also unclear in the proposal.
5\. 👍

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,
4.
Thank you for your comment.
To display a message to the user is one of the method. (Other example: gray out all buttons, display something icon and so on.) 
We think the OEMs(HMI) can consider them.
However, if there is no information, the OEMs can not do anything.
Therefore, we proposed this solution.

@JackLivio -san,
10 & 11.
Thank you for your comment.
We understood.
We will remove the word "RPC" from impacted platforms.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review to allow commenting members to summarize a list of the agreed upon revisions.

**Comment by theresalech** [comment]
Please find below a summary of the items that have been in discussion on this review issue. The PM recommends returning this proposal for the agreed upon revisions.

**Agreed upon Revisions**
1\. Change "transport" to "primary transport" throughout proposal.

7 and 9\. Replace Figure 1 with "iAP2 BT-USB Switching - Sequence Diagram" to proposal, with new notification usage of `OnDeviceSwitchStatus`.

8\. Update `OnDeviceSwitchStatus` function to match the following:
```xml
<function name="OnDeviceSwitchStatus" messagetype="notification">
    <description> Notify HMI of the current state of the transport switch </description>
    <param name="status" type="Common.SwitchStatus" mandatory="true"/>
    <param name="switchingTransportResult" type="Common.SwitchingTransportResult" mandatory="false"/>
</function>

<struct name="SwitchingTransportResult" mandatory="false"/>
   <param name="switchingResult" type="SwitchResult" mandatory="true"/>
   <param name="failReason" type="Strings" mandatory="false"/>
</struct>

<enum name="SwitchStatus">
   <element name="STARTED"/>
   <element name="FINISHED"/>
</enum>

<enum name="SwitchResult">
   <element name="PASSED"/>
   <element name="FAILED"/>
</enum>
```

10 and 11\. Update `Introduction` section to the following:
>This proposal is to improve transport switching in the same device for Transport switching of iOS approved by "SDL 0053-Connectivity via iAP-BT and Transport Switch".

Update `Impact on existing code` section to the following:
>SDL Core : Add the process to send a new RPC to HMI.
HMI : Add the process of receiving a new RPC.

**Resolved, No Action Required**
2, 3, 4, and 5\. These items are no longer applicable, based on the agreement in items 7 and 9.
6\. Understood, no action required.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions. The author will revise the proposal to incorporate the items listed under “Agreed upon Revisions” in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1069#issuecomment-689107562).

**Comment by theresalech** [comment]
The author has updated this proposal based on the Steering Committee's agreed upon revisions, and the revised proposal is now in review until October 27, 2020.

The specific items that were updated since the last review can be found in this merged pull request: #1078

**Comment by joeljfischer** [comment]
Restarting numbering.

1\.

> *1 : If the HU recognizes that current BT and new USB are connected to the same device, SDL primary transport will switch to USB.

I think this may be a change to the Android library and not how it works today (which breaks with the "clarification" that this proposal is supposed to be). I believe that Android has USB as a secondary transport compared for BT's primary; can @joeygrover confirm?

2\.

> *3 : The USB connection is prioritized, even if both primary transports are connected to the same device.

This chart and footnote seems to be saying that WiFi won't activate if the primary transport is USB. This is not how it works today.

3\. Having a "current connection" of WiFi is not possible. WiFi cannot be the primary transport.

4\. *1 and *4 are the same thing. Also see (1) here.

In sum, this chart seems to be completely incorrect. Can @JackLivio please confirm?

5\. Given the second *2 (which is confusing by the way, because the first time the *2 is a footnote for the first chart and the second *2 isn't a footnote), it seems like this proposal cannot be approved until a proposal implementing that feature is approved. Can @theresalech or @joeygrover confirm that for me?

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,

1.
We are very sorry while contacting @joeygrover -san, but I have a question .
In the SDL Core Guides, it is described that the USB and WiFi can apply for the secondary transport.
Example : USB and WiFi against BT(BT+USB/WiFi), WiFi against USB(USB+WiFi).
Is the SDL Core implemented a mechanism which the USB and WiFi  will become to secondary transport? 

2.
The correct behavior is to become "USB+WiFi"?

3.
Thank you for your review.
I understood.
I will modify to remove the WiFi line from the current connection in the table.

**Comment by joeljfischer** [comment]
1\. I think we need to clarify what this table is. This table is intended to be a chart of what the current primary connection is and what should happen if a new transport becomes available, correct? If that is the case, I think the chart is incorrect for iOS and Android. I also think that there needs to be multiple tables because iOS and Android handle this differently.

I believe that WiFi should be removed from the chart entirely. It's not a primary transport.

For iOS if BT is connected and USB becomes available, it should switch to USB. If USB is connected and BT becomes available, USB should remain connected.

For Android, there are two separate cases:

a. If the app is not yet registered: If BT is connected and USB becomes available, it will switch to USB. If USB is connected and BT becomes available, USB should remain connected.

b. If the app is already registered: If BT is connected and USB becomes available, it will stay connected to BT and use USB as a secondary transport if possible. If USB is connected and BT becomes available, USB should remain connected.

2\. This relates to (1), and I don't think that WiFi should be in this chart at all.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow for further discussion on the review issue.

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,
1. & 2.
Thank you for your comments.
I understood to need at least 3 tables for the description of transport connection status.
So, I will talk about internally and determine whether to remove the description or to add some tables.

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,

1. & 2.
We talked about this matter internally.
As a result, since we could not find out these tables in the SDL specification document, we determined the modification to add three transport connection status tables to this proposal.

**Comment by joeljfischer** [comment]
1\2. That's not at all what I said. I didn't say these tables existed. I said the tables as you defined them are wrong.

**Comment by Shohei-Kawano** [comment]
1/2. 
@joeljfischer -san,
If the table doesn't exist, we think it's a good idea to add the table to the documentation with your advice as well.
Perhaps it is explained in sentences, but I think that it is easier to understand if there is a table.
In fact, we find the table easier to understand.

**Comment by joeljfischer** [comment]
@Shohei-Kawano You are not responding to what I've said. Please re-read my previous comment.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow for additional discussion on the review issue. It was clarified during the meeting that, regarding Item 1/2, the Project Maintainer's concern is that the table present within the proposal does not contain correct information (for example, WiFi cannot be a primary transport). The current ask of the author is to specify the intention of the table (what is supposed to be showing), and then to ensure the information displayed is accurate. Once that's been resolved, the other open items on this review issue can be revisited.

**Comment by Akihiro-Miyazaki** [comment]
@joeljfischer -san,
1.& 2.
We will clarify for your comment.
> I think we need to clarify what this table is. This table is intended to be a chart of what the current primary connection is and what should happen if a new transport becomes available, correct?

We think what you described is correct.
The purpose of this table is to be a table of what the current primary connection is and what should happen if a new transport becomes available.
However, as you know, the table of my proposal is wrong. This table is mixed the case of iOS and Android.

Therefore, I would like to modify to use three tables for iOS and Android like below.
The current status is to confirm to joey-san, if it is possible, we would like to ask him to be confirmed with these tables. 

![Transport_connection_status_for_iOS](https://user-images.githubusercontent.com/60722633/98335852-21ff1a00-2049-11eb-8098-9507087eb14d.PNG)
![Transport_connection_status_for_Android1](https://user-images.githubusercontent.com/60722633/98335858-2592a100-2049-11eb-98a3-097dbcdf0698.PNG)
![Transport_connection_status_for_Android2](https://user-images.githubusercontent.com/60722633/98335875-2aefeb80-2049-11eb-9daf-5f54e58157e1.PNG)

**Comment by jordynmackool** [comment]
The Steering Committee voted to keep this proposal in review to allow further discussion on the review issue.

**Comment by joeljfischer** [comment]
1\/2\. I still don't think these charts are correct. I'm not sure that WiFi needs to be in these charts _at all_, even as a secondary transport. They seem to be irrelevant to the proposal and just confuse the chart. It's also incorrect: for example, for iOS, if BT+WiFi is being used and USB is connected, USB+WiFi will be used.

I think the third row of Android1 is also incorrect. @joeygrover can you please look over those charts?

5\. This is still waiting for a response.

**Comment by joeygrover** [comment]
1/2\. 
The charts provided are closer, but still incorrect.

I want to clarify the understanding regarding primary and secondary transports:

Primary transports are only BT and USB. For iOS these are combined into the iAP transport and the library can only reference it as such. The head unit can move the iAP connection from BT to USB, but the library will not have insight into this process. 

Android **NEVER** switches primary transports, secondary transports, or disconnects secondary transports when new transports connect. Bluetooth and USB (AOA) are distinct transports and once one is selected as primary transport it stays the primary transport for the entire session. The developer supplies a list of primary transports in an ordered list into their `SdlManager` through the transport configuration. The library will select which transport to connect with or use based on the order of that list against the currently connected transports. The default list is [AOA, BT]. 

Secondary transports are independent of primary transports. The head unit defines which transports are to be used as a secondary transport and in what priority the audio and video services should use in respect to being started on primary or secondary transports. When a primary transport is connected, the StartServiceACK sent back to the app has the definitions of transports are to be used as secondary transports and the transport priority of audio and video services. See [here](https://github.com/smartdevicelink/protocol_spec#31322-start-service-ack) for more information.

There is not a requirement that each app have the same transport priority as the other. Since this information is unique to each app it is possible that the head unit tries to handle the bandwidth requirements by spreading apps across different transports. For example, App1 could have primary transport BT with secondary transport USB, while App2 has a primary transport BT with secondary transport TCP. 


With these items it should be clear that there are a multitude of different scenarios between primary and secondary transports. The charts provided are incorrect but are also too limited in their scope of possibilities. This is why there are no charts available at this time. I would refer back to the original proposal regarding secondary transports as well as the protocol spec itself.

5\. There is still no answer to this question and I find it as an absolute requirement before this proposal can move forward. I believe we should defer this proposal for the time being and wait for the prerequisite proposal to be submitted, reviewed, and if accepted we revisit this proposal.

**Comment by jordynmackool** [comment]
The Steering Committee voted to defer this proposal due to item number 5 in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1069#issuecomment-716740461) stating that a prerequisite proposal is needed for “device identification by the HU”. Once the prerequisite proposal is submitted, reviewed, and if accepted we can bring this review issue back under review to continue discussing the remaining open items 1/2.

**Comment by jordynmackool** [comment]
The author of this proposal has requested via email to withdraw this proposal on 2021-01-07. They provided the below explanation: 

>The reason is that we found that there is a Secondary mechanism for connections, and we have determined that notifications to the HMI are less necessary for Secondary connections.
