### ISSUE TITLE
[Deferred] SDL 0322 - Improve starting streaming services

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#1091]
Hello SDL community,

The review of "SDL 0322 - Improve starting streaming services" begins now and runs through November 17, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0322-improve-starting-streaming-services.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1091

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool 

Program Manager - Livio
Jordyn@livio.io

**Comment by Sohei-Suzuki-Nexty** [comment]
1.
Is this issue related to the version of SDL Core? If so, please tell us which Core version is relevant.

2.
What is the reason for fixing the app library instead of Core?

**Comment by kshala-ford** [comment]
@Sohei-Suzuki-Nexty thank you for your feedback. 

1\. No it's not related to a core version. They all behave the same. The issue is that in certain situations, Core's security manager would disallow starting a secured video or audio service. A missing certificate that is downloaded in a policy table update is one reason. Lack of gps reception to verify certificate expiration date is another. There is no API for the app to know that starting a protected Service would be possible. This is why repeat trying is the only chance. 

2\. Extending protocol or rpc spec is a good addition but won't cover the head units on the road. Failing to start the service can still happen and depends on how core is configured and what conditions must be met  to start a service. The Limitation of starting only one service at a time is due to the fact that verification/handshake is transport session dependent. The biggest issue is that the security manager must be restarted to reset SSL context.

3\. This proposal is dependent on the proposal 0304. Tests showed that starting the service during a policy table update can cause issues on Ford IVIs. Processing the PTU and performing a handshake can cause race conditions leading to Core crash. This is a Core 4.2/policy handler issue and wasn't visible on Core 5.0 assuming future versions won't be affected either. Waiting for the PTU process to complete makes sense to avoid unnecessary load. It'll als make the procedure faster as all resources are available to process the PTU and then the TLS handshake.

**Comment by Sohei-Suzuki-Nexty** [comment]
@kshala-ford -san,
Thanks for your reply.

1. We understood that it is not related to the SDL Core version.

2. We understood that the library fix is good. Regarding the correction of Core, it would be nice if you could describe the contents of your reply in the alternative considered.

We would like to confirm, what Core settings should we check to see if the HU could have this problem?
We are concerned about whether this issue can occur on all OEM HUs and under what conditions. In some cases it may be better to treat it as a bug.

**Comment by kshala-ford** [comment]
thank you for the response @Sohei-Suzuki-Nexty -san,


2\. By design of SDL, the SDL security can be seen as a limited resource as one and the same underlying TLS connection is used for any active protected Service on the connected transport data session. The security APIs are actually critical code sections which need to be synchronized when called/executed concurrently. The security APIs are called concurrently by the audio and video manager but it's not synchronized. A semaphore or more intelligent methods like queuing StartService requests in the Protocol layer are options to deal with SDL security as a limited resource and provide synchronous execution.

4\.

> We would like to confirm, what Core settings should we check to see if the HU could have this problem?

To be honest I have to look it up. We use `ForceProtectedServices=0xA, 0xB`. Every application and also our IVis have individual certificates that are used for mutual TLS, however these certificates rely on a policy table update on the IVI otherwise our IVIs can't verify the application certificate. If an app tries to Start 0xA before the policy table update it will fail. Furthermore the certificate expiration must be verified which is done based on the GPS signal timestamp. The reason is because a system clock/RTC can be tampered easily. 

5\.

> We are concerned about whether this issue can occur on all OEM HUs and under what conditions. In some cases it may be better to treat it as a bug.

The issue can occur on any Ford/Lincoln HU but the behavior varies for other OEM depending on the decision which services are force protected. I have a few other proposals open to improve the situation regarding security and protection. Fixing 4\. only can be considered as a bug however, repeatedly send StartService requires a proposal.

**Comment by Sohei-Suzuki-Nexty** [comment]
Thanks for your reply. We understood overall.
Lastly, we would like to confirm one thing.
4. We found ForceProtectedServices in smartDeviceLink.ini. Is this correct?

**Comment by kshala-ford** [comment]
4\. This is correct, @Sohei-Suzuki-Nexty -san. The ini file dictates service protection levels.

**Comment by joeljfischer** [comment]
3\. If this proposal is dependent on 0304, it must be deferred until 0304 is accepted. It should not have been brought into review.

5\. On initial reading of this proposal I thought that this could be considered a bug, but you're right, the behavior change here is large enough that it probably requires a proposal for clarity and visibility.

6\. I would like to be sure I understand for clarity. The 2 second timeout _only_ starts after the `StartServiceNAK` is received by the app library? There is no protection for if Core never responds with a NAK at all, right?

7\. The note about needed changes to `SDLStreamingMediaManager` and refactoring the Java Suite library code makes me a bit nervous. That would be public API changes. I think we'd need to go into this expecting that we'll need to revise this proposal before implementation is complete if there are any public API changes.

8\. I believe that Java Suite allows the developer to manually start these services whereas iOS does not. How would that affect this proposal?

I think that the overall idea is good here. The implementation may be a bit tricky, but it seems overall like it would be a good stability upgrade.

**Comment by joeygrover** [comment]
6\. Adding to Joel's question: Is there anything we can infer about permissions being updated that could force the library to retry sending a StartService if no response is received? 

7\. I'm also a little nervous here. We essentially know there will be some public API changes, but we don't know what they will be at this time. That's not something we've been comfortable with in the past so it would be making an exception for this specific proposal. I think we need at least some base idea what would change and then I agree with Joel that we can expect that some of it is likely to change with implementation and revisions.

8\. This actually might no longer be possible with Java Suite 5.0, or at least it would be very difficult to accomplish. I can confirm that there are no public APIs in the `SdlManager` that would allow this to happen. 

9\. I believe this proposal also needs to take into account the RPC service that needs to be encrypted. While the RPC service is started unencrypted to start, subsequent start requests with the encryption flag set  should also be queued just as the audio service start is. And if this is the case, then making the changes to a streaming manager doesn't make sense and the change should be pushed down into the protocol layer.

10\. This should likely also be included in the actual protocol spec. This proposal is stating that starting encrypted services needs to be synchronized and therefore any implementation of the protocol would need to take that into account to properly work as this proposal is expecting. Though this will likely be defined as a major change because the behavior in the protocol spec does not currently have this requirement.

**Comment by jordynmackool** [comment]
The Steering Committee voted to defer this proposal due to the author's comment [here](https://github.com/smartdevicelink/sdl_evolution/issues/1091#issuecomment-727007061) stating that “This proposal is dependent on the proposal 0304”. Once the prerequisite proposal [SDL 0304 - Stream With OnTouchEvent Permission](https://github.com/smartdevicelink/sdl_evolution/issues/1014) is reviewed and if accepted we can bring this review issue back under review to continue discussing the remaining open items.

**Comment by jordynmackool** [comment]
Ford has advised that they are not able to update the `returned for revision` proposal SDL 0304 - Stream With OnTouchEvent Permission (review issue: https://github.com/smartdevicelink/sdl_evolution/issues/1014) at this time. Due to this proposal being dependent on the outcome of SDL 0304 - Stream With OnTouchEvent Permission, this issue will be closed and remain in a `deferred` state until the status of SDL 0304 is finalized.
