### ISSUE TITLE
[Deferred] SDL 0327 - App Library Remote Control Manager

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#1100]
Hello SDL community,

The review of the revised proposal "SDL 0327 - App Library Remote Control Manager" began on February 02, 2021, and continues through February 23, 2021. The proposal is available here:

- The original review of this proposal took place from November 25, 2020, to December 08, 2020. 

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0327-app-lib-remote-control-manager.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1100

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool 

Program Manager - Livio
Jordyn@livio.io

**Comment by joeygrover** [comment]
1\.

```
public interface RemoteControlCompletionListener {
    void onComplete(boolean success, String errorInfo);
}
```

Why are we adding a new, specific completion listener for this manager? I don't believe other managers have unique completion listeners. 


2\.

```
public Object getModuleData(ModuleType moduleType, String moduleId);
```

Does it make sense here to return a base class like `ModuleData` that each specific module data class would extend?

3\.

```
public interface OnRemoteControlDataListener {
    void onRemoteControlDataChanged(@NonNull ModuleType type, @NonNull ModuleId moduleId, @NonNull RemoteControlManager manager);
    void onRemoteControlDataError(@NonNull String info);
}
```

I don't think we need to be so verbose on the method names. Simply `onChanged` or `onUpdated` and `onError`. The interface name implies the scope of the methods and therefore it is not necessary for the full, qualified name a second time.

4\.

```
public void addModuleDataObserver(ModuleData type, ModuleId moduleId, OnRemoteControlDataListener dataListener);
public void removeModuleDataObserver(OnRemoteControlDataListener listener)
```

I understand the desire to try and maintain parity between platforms but using the observer keyword in the method name is a bit odd when passing in a listener. It might be better to make the names match between the method name and the listener/observer. 

5\. It might be helpful to see how a developer would use all of these code snippets and public APIs together. While I can see the individual APIs for their merit, judging the entire system as a whole is difficult. 

6\. I think the overall idea is a good one and takes care of a lot of the overhead that comes with trying to use remote control. I would really like to see some additional abstraction that provides easier to understand APIs for developers. One of the goals of managers is to reduce the knowledge a developer has to have of the RPC spec in order to properly use features within SDL. I would really like to see data structures set up that depart from the RPC and simply form the messages when needed. For example, creating a `Radio` module that has APIs like `tuneUp` and `directTune` where the class knew that the first could be accomplished via a `ButtonPress` RPC and the second a `SetInteriorVehicleData` request. Including these types of abstractions are important to do from the start so that's why I feel they are in scope of this proposal.

**Comment by jordynmackool** [comment]
The Steering Committee voted to keep this proposal in review on 2020-12-01 to allow for the author to respond to [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1100#issuecomment-736755165).

**Comment by joeljfischer** [comment]
1\. Some do, in order to pass back an error string. I can add a new generic listener that handles this better:

```java
public interface ErrorCompletionListener {
    void onComplete(boolean success, SdlError error);
}

public class SdlError {
    public Int getErrorCode();
    public String getErrorDomain();
    public HashMap<String, Object> getContext();
}
```

2\. With the current design, that would monkey with RPC classes, which I would be hesitant to do. It could return `RPCStruct` or `ModuleData`, but the first doesn't help a ton, and the second still requires the developer to pull the data out, which defeats the purpose of passing the module data / module id.

3\. 👍  I can update that.

4\. This was a mistake. I try to keep to the `Listener` nomenclature for Java Suite.

```java
public void addOnRemoteControlDataListener(ModuleData type, ModuleId moduleId, OnRemoteControlDataListener dataListener);
public void removeOnRemoteControlDataListener(OnRemoteControlDataListener listener)
```

5\. I understand that. This is a difficult thing to do quickly, so perhaps a return for revision so I can spend some time on it would be helpful.

6\. I understand that this discussion would be in the scope of the proposal. I considered adding APIs like you mention and decided against it because I didn't want to have to necessarily update the remote control manager every time remote control APIs changed. I tried to design a remote control manager API that papered over a lot of the hard work of implementing remote control but still worked with the existing remote control types so that if simple remote control updates happened no changes would be needed.

We could go in a different direction and add some complexity to the manager by implementing additional convenience APIs like you suggested for each of the different remote control data types and functions.

**Comment by joeygrover** [comment]
1\. I think that's better in a sense. However it will introduce a strange paradigm where sometimes you just supply a normal completion listener and other times it's one that contains the new error param. I'm not sure if this proposal should aim to solve that problem though, as I think it will take on a separate discussion by itself

A side note, context is an important Android class type and shouldn't be used for method naming. Something like extra is more widely used for this type of thing. 

2\. The extra work/structure is at a cost. I think if we don't create more abstract APIs like in point 6, then this might become a little more necessary. We could extend `RPCStruct` into a new class `RemoteControlModule` and have the RC module data structs implement that class. Even if it's just an empty class it might make the API to the developer more straightforward. However, the generic Object return isn't unheard of in Android; it's usually just a little more specific. 

3\. 👍 

4\. 👍 

5\. I'm good with that, I think it will be worth the exercise especially when we go to implement the feature across the platforms.

6\. My preference is to see more intuitive designs for developers away from the RPC spec, but that's just my opinion so I don't want to hold this proposal up for that. Maybe this can be revisited after the revision to show how the current proposal's APIs work together. That way it's a little easier to compare.

**Comment by jordynmackool** [comment]
Livio requests that the Steering Committee votes to return this proposal for the revisions on items 3, 4, and 5. Once this proposal is back in review, the discussion on open items of 1, 2, and 6 in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1100#issuecomment-740808184) can continue.

**Agreed upon revisions:** 

3\. Revision requests in this [comment](https://github.com/smartdevicelink/sdl_evolution/issues/1100#issuecomment-736755165).

4\. Make the names match between the method name and the listener/observer.

5\. Create sample code of how a developer would use all of these code snippets and public APIs together.

**Comment by jordynmackool** [comment]
The Steering Committee voted to return this proposal for revision on 2020-12-08. The summary of the revisions for items 3,4 and 5 are provided in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1100#issuecomment-740973742). Once the revisions are made and this proposal is back in review, the conversation can continue on open items 1,2, and 6.

**Comment by jordynmackool** [comment]
The author has updated this proposal based on the Steering Committee's agreed-upon revisions. The revisions of the proposal are now in review until February 02, 2021.

The specific items that were updated since the last review can be found in this merged pull request: https://github.com/smartdevicelink/sdl_evolution/pull/1107

**Comment by jordynmackool** [comment]
The Steering Committee voted to keep this proposal in review on 2021-02-02 to allow for additional time to review the revised proposal.

**Comment by joeygrover** [comment]
1\. I believe we are still in a conversation about this point. There might be a way to create some inheritance cleverness that we could setup the use of a new completion listener with an error in the same places we use the current completion listener without the error. Some way that it can be made to allow the developer to choose which. Though as I mentioned before, this still seems a little outside the scope of this proposal.

2\. Still waiting for feedback again here. 

6\. I still believe in something more intuitive for the developer that doesn't involve the learning curve of the RPC layer for SDL. Though I do recognize this proposal as a much better step than what exists today. The different API that I suggest would take some time to create though, and I'm not sure if the remote control feature would even be that useable without some form of manager layer like the author proposed. So unless another member would like to see such an API that I suggest, I will agree to drop this point.

**Comment by jordynmackool** [comment]
The Steering Committee voted to keep this proposal in review on 2021-02-09 to allow additional time for the author to respond to the [last comment](https://github.com/smartdevicelink/sdl_evolution/issues/1100#issuecomment-776230655) left on the review issue.

**Comment by joeljfischer** [comment]
1\. I apologize, I thought that we had agreed to use the more specialized version and to not include the generic version. I think that the generic version would be a really helpful addition for the Java Suite library, but I understand that deprecating and replacing everything necessary would be a huge change.

2\. I don't like using RPC classes to build non-RPC spec related features because I've seen that when it's happened in the past, it has caused confusion. We could change this to be more like the iOS / JavaScript Suite versions and have individual getters if the `Object` return is a big objection. That would be my preferred solution, though it would be different from the Java-Suite version of the `SystemCapabilityManager`, which I based this API on.

**Comment by joeljfischer** [comment]
6\. I have an idea here to improve this while still being scalable. I would request that this remain in review so that I can work out if it will work well. If it doesn't I think that the currently proposed system is enough of an improvement that I would like to move forward with that.

**Comment by jordynmackool** [comment]
The Steering Committee voted on 2021-02-16 to keep this proposal in review to allow for conversation to continue on open items 1, 2, and 6.

**Comment by joeljfischer** [comment]
I'm very sorry, but I have not had time to further explore a potential change. This change would be to use generics to create data objects that can be subscribed to while exposing the internal data. Due to the upcoming release, I will not have time to explore the feasibility of this option for quite some time. Therefore, I would like to defer this proposal.

**Comment by jordynmackool** [comment]
The Steering Committee voted on 2021-02-24 to defer this proposal at the request of the author in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1100#issuecomment-784339232).

The proposal will remain deferred until the author has acknowledged (via email to sdlc@smartdevicelink.com) that they are able to continue the conversation on the review issue.

**Comment by theresalech** [comment]
Closing as inactive. The issue will remain in a `deferred` status and unlocked so the author can notify the Project Maintainer when it is ready to be revisited.
