### ISSUE TITLE
[Accepted] SDL 0342 - Remove Policy Mode Option From SDL Core

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1172]
Hello SDL community,

The review of "SDL 0342 - Remove Policy Mode Option From SDL Core" begins now and runs through August 10, 2021.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0342-remove-policy-mode-option-from-sdl-core.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1172

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow for additional time for members to review and leave any feedback on the review issue.

**Comment by GauravPandey321** [comment]
I would suggest keeping support for the PROPRIETARY mode as suggested in the proposal as a possible alternative.

**Comment by jacobkeeler** [comment]
@GauravPandey321 Is there a specific reason that you need support for this older mode? For clarification, removing PROPRIETARY mode would not break older versions of SDL Core, it would only affect systems updating to a new major version of Core (which normally involves in-depth changes in any case). The changes required to move to EXTERNAL_PROPRIETARY should be fairly small overall, and a guide would be provided to assist with this transition as part of this proposal.

Ideally, all systems would be using EXTERNAL_PROPRIETARY, since (as mentioned in the proposal) the other modes only support a subset of the policy features in EXTERNAL_PROPRIETARY. I would only suggest keeping support for the PROPRIETARY flow if there was a significant concern with being able to transition existing systems to the EXTERNAL_PROPRIETARY flow when upgrading to a new major version of SDL Core.

**Comment by GauravPandey321** [comment]
@jacobkeeler Thank you for clarifying my doubts regarding this proposal.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.
