### ISSUE TITLE
[Deferred] SDL 0057 - Add zeroconf capability to WiFi transport

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#169]
Hello SDL community,

The review of "Add zeroconf capability to WiFi transport" begins now and runs through May 9, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0057-add-zeroconf-capability.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/169

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I have concerns about this proposal.
1. It takes as an underlying assumption that wi-fi should become a production use case, but I do not believe it should be. On iOS, and likely soon on android with recent changes, it is impossible to run in the background for any length of time, and it is impossible to start an app in the background without iAP. Therefore, wi-fi is not a production use case on iOS at a minimum, and likely not on Android in the near future.
2. This proposal is inadequate for the proposed functionality. It describes a single high-level mobile API to use zeroconf but this API is outdated and deprecated (since v4.3), does not describe if this is a replacement for the current IAP or if both are active, does not describe any of the lower level mobile changes necessary, only describes iOS, puts the burden on app developers to specify parameters they do not know and should not care about, does not speak of UI challenges when multiple found devices are present, requires the app to be in the foreground and does not describe the background challenges, and does not describe how this would be accomplished on Android or Core.

If this proposal is not useful for production capabilities, can this proposal also be useful in development? I do not think so. In development, you will often have a number of devices around that you may want to connect to, having a zeroconf setup instead of manually entering the IP / port may not be ideal. Furthermore, it would be incompatible with manticore. You would have to manually name the device and we would have to, on iOS and Android, build a UI system for presenting these names and allowing a developer to select one.

I strongly do not believe that this proposal should be accepted.

**Comment by madhuy** [comment]
@joeljfischer 
Thank you for the feed back. 
#1 
We have a use case in some countries in which the HU's do not have BT but only supports Wifi. Our use case needs to  use SDL with Wifi to run a few apps with Wifi Transport. We understand the app will need to be foreground.  We are working on enabling zeroconf and recommend that this is a standard for other SDL implementations to utilize ,  rather than custom.

#2 
 The API we mention is an example based on SDLProxy(V4.3) , we will change to latest Version API’s.
Regarding the burden to developer, Xevo is also planning a proposal to select transport dynamically by SDLproxy without developer involvement. We are working on the details now.

**Comment by theresalech** [comment]
The Steering Committee has agreed to collaborate on revising this proposal, and will plan to meet to talk through the design and strategic direction on how to approach production WiFi from an SDL perspective.  The proposal will be deferred until that time.

**Comment by theresalech** [comment]
@madhuy do you have any update on this proposal?

**Comment by shoamano83** [comment]
Hi @theresalech,

I double checked with the author and we are fine to close this deferred ticket.
As you may know, we have newer proposal document (reference: https://github.com/smartdevicelink/sdl_evolution/issues/407) that was based on the idea of this one. If we continue discussion, I think we should use the proposal https://github.com/smartdevicelink/sdl_evolution/issues/407 instead.

Thanks.

**Comment by joeljfischer** [comment]
@shoamano83 Can we also close #181?

**Comment by shoamano83** [comment]
Hi @joeljfischer , yes we can close that PR too.

**Comment by theresalech** [comment]
Proposal has been withdrawn per the author's request, in favor of #407.  

Additional information for future reference: #407 has been rejected as it doesn't align with the agreed upon revisions to #405.  However, a proposal can be entered if the Steering Committee decides to enable WiFi as a primary transport in the future.  In this case, a proposal similar to #407 will also be relevant.
