### ISSUE TITLE
[Rejected] SDL 0066 - Steering wheel location

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#191]
Hello SDL community,

The review of "Steering wheel location" begins now and runs through May 30, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0066-steering-wheel-location.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/191

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
While I don't think included this information into the RPC spec is a bad idea, I don't beleive it correctly solves the problem it's set out to handle. 

> Some apps want to use different templates based on the steering wheel location. As an example TEXT_WITH_BUTTONS_AND_GRAPHIC works great for left handed drives as buttons are closer to the driver. [...]

As you reference in the motivation section, the problem is actually that app developers would like to know where the head unit is located in respect to the driver. Merely stating steering wheel position doesn't give the app develop 100% certainty on that information. For example, `CENTER` position gives no information on the relative position. 

I believe the better solution to this problem would be providing infotainment system location relative to the primary user, in most cases the driver.

**Comment by joeljfischer** [comment]
I have concerns about this proposal:

1. In the proposed solution, it notes that `null` is an option for the enum, but this isn't technically correct. We don't provide `null` in the JSON for any resource. What I believe the proposal intends to convey is if the parameter is missing.

2. There is a `.` in front of the enum names in the proposal, but this is not technically correct. SDL enums do not have a `.` at the front.

3. Is this the right way to solve this problem? Would it be better for the head unit to handle this automatically? The solution option that Joey presents above is another option.

**Comment by kshala-ford** [comment]
@joeygrover that's a good point. The issue we would want to solve expects the head unit to be centered. Still the information of the steering wheel location is properly delivered to the app. Right? Rather than the relative position we should provide the head unit position as well. This way an app knows the steering wheel location and the relative position to the driver. This could be added in another proposal.

@joeljfischer regarding 1. and 2. I wrote the proposal from the app developers perspective in some sort of pseudo code. Not in json. Of course `null` means the parameter does not exist in the json data.

Regarding 3. I disagree to an automatic handling from the core side. The abstraction of UI related RPCs (e.g. the proposed view manager for Android) could provide automatic template selection but the app should be able to override it. Anyhow this would be not in scope of this proposal.

**Comment by theresalech** [comment]
The Steering Committee is returning for revisions due to the proposal not completely solving the problem it was set out to solve.  Revisions will include considering other use cases, multiple steering wheels, location of primary user in relation to screen, etc.

**Comment by theresalech** [comment]
The author has advised that they are not planning to move forward with this proposal and requested that it be rejected.  The Steering Committee agreed to reject, based on the author's recommendation.
