### ISSUE TITLE
[Accepted] SDL 0068 - Idea To Implementation

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#197]
Hello SDL community,

The review of "Idea To Implementation" begins now and runs through June 20, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0068-idea_to_implementation.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/197

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by Toyota-Sbetts** [comment]
Overall this flow covers the idea at a high level, but we wanted to clarify some points on the flow:

1. Are pull requests that require RPC spec changes and ones that do not separate flows or should they merge at some point before the next release? After the RPC spec is voted on is it then mandatory for those changes to make it to the next release? How is priority determined for a proposal and will changes affecting the RPC spec always have higher priority?

2. Does this flow assume one party is making the changes? I think we should additionally clarify how to assign/take responsibility for a proposal.

3. After an RPC spec is voted on, if additional issue or changes are found that affect the RPC spec how is that handled?  Can an advanced study or investigation on implementation begin before the RPC spec is confirmed?

**Comment by joeygrover** [comment]
1. The diagram has non-RPC changes slated as completed based on priority for the next release.  (See the "RPC Spec Change?" block) Yes, after an RPC spec is voted on, a project must support the full RPC spec. Proposals affecting the RPC spec will not guarantee higher priority; all features should be considered when determining what should be included in the next RPC spec version in relation to the available workload for the next release of the projects. When we are planning the next release of projects that is when proposal priority should be addressed so that we can properly plan out what can be included.
2. This flow doesn't contain how each feature is completed. While voting on the RPC spec version it will have to be determined how much can be contained by the project maintainer, who has offered to accomplish a feature, and if we need to assign a feature to someone if we wish to include it in the next release. 
3. Hot fixes can happen to the RPC spec after voting if at some point during the implementation it is found to be incorrect or in need of alteration. No new features can be added after the initial RPC spec vote however. Theoretically, we would have until the first project is released with supporting a specific RPC spec version to make alterations if necessary, but introducing new functionality is not allowed as it can create error prone implementations.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.  As this doesn't change any code within the SmartDeviceLink project, the output of this proposal will be to vote on what should be included in the next version of the RPC Spec, per the flow described in this proposal.
