### ISSUE TITLE
[Accepted with Revisions] SDL 0078 - Control Frame Payloads v1.0.0

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#222]
Hello SDL community,

The review of "Control Frame Payloads v1.0.0" begins now and runs through July 18, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0078-control_frame_payloads_v1_0_0.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/222

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
A few questions:

* It's not explicitly stated, but the lowest of the two `controlVersion`s is the one that will be used? How will that happen if major (breaking) changes occur in the control frame payload spec?
* HashID is already used outside of this proposal. This proposal replaces that usage as of protocol spec v5 because these replace the payload, correct?
* The `VideoProtocol` and `VideoCodec` have to match the strings from the enums of `VideoStreamingProtocol` and `VideoStreamingCodec`? (Aside: `VideoProtocol` is used twice in the `rejectedParams` of `Start Service NAK`.

**Comment by joeygrover** [comment]
> It's not explicitly stated, but the lowest of the two `controlVersion`s is the one that will be used? How will that happen if major (breaking) changes occur in the control frame payload spec?

Yes, lower version of the two would be the negotiated version. As far as breaking changes, both the core and proxy projects have always maintained complete backwards compatibility. However, with the understanding that ALL parameters are optional, it gives us a good start on not having to make breaking changes. If we needed to change a param type we would just add a new param and deprecate the old. The only foreseeable breaking change that would be possible would be if we changed from BSON to a different type of payload.  

> HashID is already used outside of this proposal. This proposal replaces that usage as of protocol spec v5 because these replace the payload, correct?

If I understand correctly, the HashID is just moving into being part of the constructed payload. It already existed in the `StartServiceACK` as a non-constructed payload.

> The `VideoProtocol` and `VideoCodec` have to match the strings from the enums of `VideoStreamingProtocol` and `VideoStreamingCodec`? (Aside: `VideoProtocol` is used twice in the `rejectedParams` of `Start Service NAK`.

Yes. Since we are using BSON it makes sense to just use the same values of the enums defined in the RPC spec. That is a typo, it should be `[videoProtocol, videoCodec]`

**Comment by theresalech** [comment]
The Steering Committee agreed to accept this proposal, with the following change: Change from introducing a new `controlVersion` parameter to changing the protocol header to have an extended version for headers, as described in the "Alternatives considered" section.

**Comment by theresalech** [comment]
@joeygrover please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions.  I'll then merge the PR so the proposal is up to date, and enter issues in respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
PR including revisions has been merged.  Issues have been entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1684)
[Android](https://github.com/smartdevicelink/sdl_android/issues/567)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/663)
