### ISSUE TITLE
[Accepted with Revisions] SDL 0089 - Mobile API versioning

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#269]
Hello SDL community,

The review of the revised proposal "SDL 0089 - Mobile API versioning" begins now and runs through September 19, 2017.  The original review of "Mobile API versioning" occurred August 29 through September 5, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0089-mobile-api-versioning.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/269

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I have a few notes:
1. I'm not sure that the `minVersion` attribute on the spec as a whole is necessary as the spec is under semantic versioning; therefore, the spec *should* always be backward compatible to the last major version change. This hasn't really been the case until v4.0, but it is at this point.

2. Do params that are introduced with an RPC need the `added` tag or if it's missing can it be assumed to have been added when the RPC is added? It's not a big deal to add the version to everything, just wondering if anyone thinks it might be cleaner. (I just now noticed this in the alternatives as well)

3. You note in the section "Parameter element signature" that _any_ change would be to cause a new parameter to be added with an "added / removed" pair. I think this should only occur in the case of a breaking change, but not in a minor / widening change. You give the example:

```xml
<struct name="Choice">
  <param name="vrCommands" type="String" minsize="1" maxsize="100" maxlength="99" array="true" removed="4.5.0" /> <!-- implicitly mandatory -->
  <param name="vrCommands" type="String" minsize="1" maxsize="100" maxlength="99" array="true" mandatory="false" added="4.5.0" /> <!-- explicitly optional -->
</struct>
```

Because this "widens" the parameter, instead of narrowing it, this should merely change the parameter instead of removing / adding. However, if it were to narrow the parameter, e.g. by making an optional parameter mandatory, then it would require something like the above.

**Comment by kshala-ford** [comment]
Hey @joeljfischer thank you for your comments. Let me try provide some explanation to your notes:

1. `minVersion` is not about backward compatibility. Its about the SDL library which implements the mobile API if it supports all the RPCs and parameters down to the specified min version although the target version does not support those RPCs anymore. 

An example is `Show.mediaClock` which was added with the very first version of AppLink. With AppLink 2.0 it was replaced by `SetMediaClockTimer` RPC. Today `Show.mediaClock` is obsolete and could be removed from the mobile API. The question is should it be removed from the SDL libraries as well?

The SDL libraries should be supporting older versions to a certain extend so app developers can still use older head. Effort to resolve or work around breaking changes may be required by the app developer or by the library managers (if version > x.y.z). Mention the min version in the mobile API clearly points out how far the SDL library provides old APIs.

2. Sub-elements should inherit the attributes from the parent. The alternative requires every attribute to be repeated for sub-elements. Personally I prefer inheritance as I believe it's more human readible and it might reduce the risk of mistakes.

3. Changing the min-/maxsize, maxlength or the mandatory flag woud require a removed/added pair. In the above case `Choice.vrCommands` was changed from mandatory to optional.

**Comment by joeygrover** [comment]
Overall I support this proposal. 

I do think the `minVersion` is misplaced/confusing though. The semantic version takes care of "removing" RPCs that aren't necessary anymore. However, we will never actually be able to remove these from the RPC spec as it is necessary to be clear about what RPCs have existed and to what version. From my understanding, `minVersion` is essentially trying to to state how far back each of the projects should support back to. For your example, `Show.mediaClock` can be tagged as `removed` in the RPC spec, but the libraries should still support it until this `minVersion` is upped past its inception version. 

I think the `Parameter element signature` section has potential to get very unruly. I believe someone from the `SdlCore`( @JackLivio, @jacobkeeler)  team should comment on how this would affect that project specifically as it builds off the RPC spec dynamically. This seems better suited to be placed inside the param description as a changelog or as a new section similar to your `warnings` tag.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions, so that there could be more information about parameter changes with regards to backwards compatibility.  Specifically, the committee is looking for something similar to the warning element section of the proposal, with information about attributes for parameters that have changed.  This should include what the parameter was changed from, what it changed to, and at what version the change occurred.  This would be similar to a changelog for each RPC.  While these changes should be rare, the changelog will allow us to make breaking changes in the future and still let a parser know how it should act based on version.

Example of what this change would include, reviewed during the Steering Committee call:
```<enum name="ButtonName">
</element>
  <element name="OK">
    <description>
      The button name for the physical OK button.
      It is not related to the Play/Pause button.
      Please use the physical `PLAY_PAUSE` button.
    </description>
    <changes>
      <change changeCategory="added" changeVersion="1.0.0" />
      <change changeCategory="attribute" attribute="mandatory" from="true" to="false" changedVersion="4.5.0" />
      <change changeCategory="deprecated" changeVersion="4.5.2" />
      <change changeCategory="deleted" changeVersion="4.6.0" />
    </changes>     
  </element>
</enum>```

Project Maintainer’s suggestion for change, after further review:
```<enum name="ButtonName">
</element>
  <element name="OK" mandatory="false" deleted="true" from="4.6.0">
    <description>
      The button name for the physical OK button.
      It is not related to the Play/Pause button.
      Please use the physical `PLAY_PAUSE` button.
    </description>
    <previousVersions>
      <element name="OK" mandatory="true" from="1.0.0" until="4.5.0">
      <element name="OK" mandatory="false" from="4.5.0" until="4.5.2">
      <element name="OK" mandatory="false" deprecated="true" from="4.5.2" until="4.6.0">
    </previousVersions>     
  </element>
</enum>```

**Comment by theresalech** [comment]
Proposal has been revised to include requested changes, and the revised proposal is now ready for review.

**Comment by theresalech** [comment]
This revised proposal has now moved into review.  The Steering Committee will vote on this proposal during the September 19, 2017 meeting.

**Comment by joeljfischer** [comment]
After reviewing the revised proposal, I stand by the maintainer's suggestion above over against the provided revisions. The proposal suggests essentially the following for what we had above:

```xml
<enum name="ButtonName">
</element>
  <element name="OK" mandatory="false" deleted="4.6.0">
    <description>
      The button name for the physical OK button.
      It is not related to the Play/Pause button.
      Please use the physical `PLAY_PAUSE` button.
    </description>
    <previousVersions>
      <element name="OK" mandatory="true" since="1.0.0" removed="4.5.0"/>
      <element name="OK" mandatory="false" since="4.5.0" deprecated="4.5.2"/>
      <element name="OK" mandatory="false" deprecated="4.5.2" removed="4.6.0"/>
    </previousVersions>     
  </element>
</enum>
```

I think this is much more confusing and difficult to write a parser for than the maintainer suggestion above. The maintainer suggestion provides only two version parameters: `from` and `until` (though these could be different, such as `since`). Then, all the other parameters become booleans, including `deprecated` and `removed` or `deleted` (whichever wording is chosen). To me, this seems easy to read and easy to parse. In particular, the mandatory change in the revised version seems very confusing.

The maintainer's version allows the history to be exactly the same as it was in previous versions, with the addition of an `until` when it has been changed.

Additionally, the revised proposal appears to suggest description changes make history changes. I don't think this is necessary and clutters up the XML spec. The description itself, if necessary, could include additional paragraphs about previous versions. If necessary, a developer could go to a previous version of the spec to look at the previous documentation.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will be based on the Project Maintainer's suggested code sample provided in the comment on September 6 (2017-09-06).  This suggested code will solve the same problem, while making parsing easier.

**Comment by theresalech** [comment]
@kshala-ford please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions.  I'll then merge the PR so the proposal is up to date, and enter an issue in the RPC Spec repository for implementation.  Thanks!

**Comment by kshala-ford** [comment]
@theresalech With all the respect I'm going to compile a paper to argument against the decision of the steering comittee. I'm afraid the requested change has unseen issues and causes much more complexity we are not aware of. 

I would like to have the chance to have a conversation about this proposal as I had no chance to reply to the last comment that was posted soon before the last meeting.

**Comment by theresalech** [comment]
Proposal has been revised to include agreed upon changes and issue has been entered: [[SDL 0089] Mobile API versioning](https://github.com/smartdevicelink/rpc_spec/issues/59)

**Comment by theresalech** [comment]
Determined changes will also be required to Core. 
 Issue has been entered: [[SDL 0089] Mobile API versioning](https://github.com/smartdevicelink/sdl_core/issues/2248)
