### ISSUE TITLE
[Accepted] SDL 0093 - Haptic Projection

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#279]
Hello SDL community,

The review of "Haptic Projection" begins now and runs through September 12, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0093-haptic-projection.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/279

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
I believe the code here is best suited to be in a class of it's own, similar to the HapticInterfaceManager that was proposed to iOS. We want to ensure these modules are useable outside of the larger module that we create. I also would like to see the finished code/logic if possible.

The `RPCRequestFactory` class is honestly worthless and we should move to deprecate it. Each RPC should just have a constructor that takes in the required params and one that takes in all. Therefore, I would suggest not even adding it to this class.

I have the same feelings over the "helper" methods in the proxy. They create a minimally helpful layer of abstraction while causing more confusion if the developers need to access the actual RPC. I feel all those helper methods should be deprecated as well, and again I don't feel that the helper method should be added. The correlation ID is also hardcoded to `200` but I'm sure that's not what the author intended.

There was a conscious effort to not include a reference of the proxy object inside the VirtualDisplayEncoder. The `VirtualDisplayEncoder` only needs a few methods that access the proxy and as discussed in our VPM workshop, it's better suited to create a proxy layer interface that has these methods rather than passing around the proxy object itself. Then all that would be needed would be a method to send an RPC as really there is no need to create helper methods and use them to do the same thing.

I would recommend this proposal be sent back for revisions that reflect creating a new haptic manager class, removing the additions of redundant helper methods, removing the proxy instance saved in `VirtualDisplayEncoder`, create a first pass at the proxy interface layer that includes a `OnRpcToSend` method, and finally actually include more of the code that would be required for this feature to work.

**Comment by Toyota-BSalahat** [comment]
One additional comment, this proposal seems to draw heavily from the iOS haptic manager. That approach made the most sense in the scope of what iOS offers in its native SDK. Generally speaking when it comes to things like this Android generally has better support, this is something we are still investigating however.

There is one alternative considered that uses the built in game pad support, which seems interesting. If possible, if Android has better support for this concept than iOS, I think we should try to use that under-the-hood.

**Comment by drewd** [comment]
@joeygrover I'd like to discuss your thoughts with you.

I agree some of the "boiler plate helper methods" are useless. I only included them to keep up with the design pattern of the project. If this is the item that diverges from that design principal, that works for me.

As with the `HapticInterfaceManager` class, I am struggling to see the point. Who would instantiates this class? Is it static or a singleton? My thoughts were the `VirtualDisplayEncoder` will be the only place this feature is used. `SdlPresentation` is aware of the Views being displayed by the developer, therefore that class is the only object that needs to about this RPC. Of course, a developer can build their own `HapticRect`s and send them to the `Proxy` out-of-band.

Do you envision `HapticInterfaceManager` to just contain the methods to traverse the a View on behalf of the developer?

Regarding `VirtualDisplayEncoder` storing the `Proxy` reference, I assumed that was done on purpose. With the design pattern I thought of, I could not see how to get the `SdlPresentation` to automatically send the RPC without saving this reference. I am open to doing this a different way but in this design, I do not see how. Depending on what `HapticInterfaceManager` looks like, I believe we'll have the same issue there as well.

I did not include the code of `findHapticRects` as that is an implementation detail that might have to change with testing. Currently, this is what it looks like:
```
private void findHapticRects(View view, final List<HapticRect> list) {
    if (view.isFocusable()) {
        int[] location = new int[2];
        view.getLocationOnScreen(location);
        Rectangle rect = new Rectangle();
        rect.setX((float) location[0]);
        rect.setY((float) location[1]);
        rect.setHeight((float) view.getHeight());
        rect.setWidth((float) view.getWidth());
        HapticRect hapticRect = new HapticRect();
        hapticRect.setId(view.getId());
        hapticRect.setRect(rect);
        list.add(hapticRect);
    }
    if (view instanceof ViewGroup) {
        final ViewGroup viewGroup = (ViewGroup) view;
        int childCount = viewGroup.getChildCount();
        for (int i = 0; i < childCount; i++) {
            findHapticRects(viewGroup.getChildAt(i), list);
        }
    }
}
```

**Comment by Toyota-Sbetts** [comment]
@drewd Have you have a chance to look into gamepad support like @Toyota-BSalahat mentioned or other alternatives?  Toyota is investigating this and other alternatives but may not be done by tomorrow and if you have already investigated and dismissed others we would appreciate the insight.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review until the 2017-09-19 meeting, so that additional time could be spent investigating gamepad support and other alternatives.

**Comment by vladneculoiu** [comment]
Hello,

More details about supporting game controllers can be found here: https://developer.android.com/training/game-controllers/index.html
Android provides an API for gamepad and joystick.

**Comment by mfoedisch** [comment]
Regarding findHapticRects sample code

In our experience this code might not work well with all types of Views. In a scenario where for example ViewPager is used, a couple of issues would occur: besides some general inconsistencies with regards to child elements being found, the visibility of child elements seems to be always VISIBLE. This means, we would extract the geometry of elements that are not visible (because it is on a different Fragment) to the user. Also, the parent element ViewPager is considered "focusable" but with a geometry that covers the "whole area" as opposed to the clickable "tab area". 

So, following the proposed approach would definitely require more logic to handle certain situations like the one described.

**Comment by Toyota-BSalahat** [comment]
@mfoedisch, @drewd, @joeygrover This is not production-ready code, but we did some testing internally, and the below code seems to be able to navigate ViewPager and other containers, so long as it is called after the view tree is loaded. It may still require some of the additional logic Mike mentioned, but seemed to handle the test cases that we experimented with.

We are also finishing up investigation into a couple of other alternative approaches, and hopefully will have something conclusive to share on those before the meeting tomorrow.

```java
public void checkFocusUi(View v) {
    ConstraintLayout mTopView = (ConstraintLayout) v.findViewById(R.id.root_contraint);
    List<View> viewArrayListGrp = getAllChildren(mTopView);
    Log(TAG," Checking focussable views");
    for(View vi:viewArrayListGrp) {
        Log(TAG,"View trans name "+ vi.getTransitionName() + " to string " + vi.toString() + " \n v is focussable " + vi.isFocusable() + " is Focussable in touch mode "
                + vi.isFocusableInTouchMode() + " v is clickable " + vi.isClickable());
        if(vi.isFocusable() || vi.isClickable()) {
            vi.setBackgroundColor(getResources().getColor(R.color.colorAccent));
        }
    }
}

private ArrayList<View> getAllChildren(View v) {
    Log(TAG," getAllChildren"  + v.toString());
    if (!(v instanceof ViewGroup)) {
        ArrayList<View> viewArrayList = new ArrayList<View>();
        viewArrayList.add(v);
        Log(TAG," retunring arrayList");
        return viewArrayList;
    }

    ArrayList<View> result = new ArrayList<View>();

    ViewGroup vg = (ViewGroup) v;
    for (int i = 0; i < vg.getChildCount(); i++) {

        View child = vg.getChildAt(i);
        Log(TAG," Child name "  + child.toString());
        ArrayList<View> viewArrayList = new ArrayList<View>();
        viewArrayList.addAll(getAllChildren(child));
        result.addAll(viewArrayList);
    }
    return result;
}
```

Additionally we would also like to suggest that regardless of the internal implementation details the Android Manager follow the interface pattern that we used for the iOS implementation, and if possible support the functionality that was added to the iOS manager inside the HapticHitTester protocol proposal.

**Comment by madhuy** [comment]
@Toyota-BSalahat @drewd @Toyota-Sbetts 
We don't need to walkthrough the view hierarchy to get focusable or touchable items in android.
We can use **addTouchables** on ViewGroup. 

Here is pseudo code.

```
public void sendHapticData(@Nullable ViewGroup rootView) {
        ArrayList<View> touchableViews = new ArrayList<>();
        if (rootView != null && (rootView.getChildCount() > 0)) {
            rootView.addTouchables(touchableViews);
        }

        int[] location = new int[2];
        List<Rect> viewRects = new ArrayList<>();
        if (touchableViews != null) {
            for (View touchableView : touchableViews) {
                int w = touchableView.getWidth();
                int h = touchableView.getHeight();
                touchableView.getLocationOnScreen(location);

                Rect viewBounds = new Rect(location[0], location[1], w, h);
                rects.add(bounds);
                // send  this rects to SDL core by using sendHapticData() API.

            }
        }
    }
```
@Toyota-BSalahat 
**Regarding Game Pad Support investigation**
Do we need to investigate for this proposal ?
This proposal is to send Focusable View coordinates  to SDL core by using sendHapticData() API not for handling Motionevents, Keyevents, touch events .  Please let me if i misunderstand the proposal.

**Comment by Toyota-BSalahat** [comment]
@madhuy 

This looks fine based on the documentation for addTouchables. Will addTouchables have the same behavior for more complex views, such as container views and listviews?

The documentation also suggested that addTouchables could return the root view as well. I think we may need to think through that case (and just in general what to do if a parent view reports touchable, as well as its children). ie, we probably wouldn't want an entire list to be focusable, if its items are also focusable.

**Comment by theresalech** [comment]
After considering possible alternatives, it was determined that the route identified in this proposal is best, and the Steering Committee voted to accept this proposal.  It was noted that Toyota's example code provided in their comment on September 18 (2017-09-18) will be referenced in implementation.  When abstracting into an interface, we should allow a similar API to that of the iOS manager.  If possible, we'll support the functionality that was added to the iOS manager inside the HapticHitTester protocol proposal.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0093] Haptic Projection](https://github.com/smartdevicelink/sdl_android/issues/612)
