### ISSUE TITLE
[Accepted] SDL 0098 - SDL Localization

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#295]
Hello SDL community,

The review of "SDL Localization" begins now and runs through September 26, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0098-localization.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/295

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I apologize for not reviewing this earlier. A few questions on the iOS side, but I generally support the aim of this proposal:

1. The "localizable files" are the same as those used by `NSLocalizedString`, or a custom file? (It appears the former from the code, but this isn't explicitly stated)
2. What does `defaultLocalization` method load? Is it the same as the localization instance created by the `SDLManager`?
3. If so, would it be better to provide a macro such as `SDLLocalizedString` that uses `defaultLocalization`?
4. Does the localization manager automatically correlate and pull from the SDL's head unit language? Does it watch for the RAIR to know the language? (Doesn't appear to in the code)

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until the next meeting on October 3, 2017 (2017-10-03), so that there is additional time to discuss the questions posted here.  Additionally, another question about this proposal was brought up in the Steering Committee meeting which will be formally posted here by the SDLC Member as well.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal one more week, so that there is additional time for these questions and others to be answered by the author of the proposal.  We will plan to vote on this proposal during our meeting on October 10, 2017 (2017-10-10).

**Comment by shengbi** [comment]
I am not sure how the language/locale setting is pre-set when the car is sold, but I think we should consider using customer's preferred localization setting on the smartphone instead of the one on the HMI. Phones are more personal and close to customer's day-to-day life. One of the edge cases is that driver and passenger have different preferred language settings, e.g. English and Spanish, then depends on whose phone is connected, the SDL app would display the proper language for that customer.

**Comment by kshala-ford** [comment]
@joeljfischer `defaultLocalization` points to the phone language. It was planned to be used as a fallback whenever the head unit language is not supported (avoid unnecessary bundle reloads). I wouldn't propose to add `SDLLocalizedString` to point to this fallback. It might be misunderstood as the default access to SDL localization. I thought of using a macro to point to the head unit language but it might change over time and I didn't figure out how to deal with that. The classes provided don't include any SDL related types on purpose but it doesn't need to stay this way. I don't have any issues with making useful modifications to the classes.

The lifecycle manager should create instances of the localization classes right after the app received RegisterAppInterfaceResponse (the moment the app knows the head unit language). It might be a good idea to have a localization manager who takes care about `OnLanguageChange`, `ChangeRegistration` etc.

@shengbi Agree. The phones language should be used. When an app registers the head unit should use the language desired and setup the head unit components (UI, Voice recognition, TTS engine) to the desired language. However that is not the case. The head unit might not be able to maintain multiple languages (especially due to the voice engine) and can dictate another language as the desired one (told in the register response).

**Comment by tpulatha** [comment]
@shengbi To expand on @kshala-ford comment. There are multiple reasons why it is not practical to follow the app language at the moment:

1. Infotainment headunits usually have a (very) limited set of languages available. 
2. The App language can be different than the phone OS language. (For example if an app is not localized). this would lead to different Apps switching the headunit to different languages.
3. Listening to the App language would trigger a pretty big UI interaction in the headunit (change of language) without special permissions. This is not desirable.

**Comment by theresalech** [comment]
The Steering Committee has voted to defer this proposal and keep it in review until next week's meeting (2017-10-17).  This will allow SDLC Members and the Project Maintainer time to review the author's answers to their questions and ensure thorough review.

**Comment by joeljfischer** [comment]
> `defaultLocalization` points to the phone language. It was planned to be used as a fallback whenever the head unit language is not supported (avoid unnecessary bundle reloads). I wouldn't propose to add SDLLocalizedString to point to this fallback. It might be misunderstood as the default access to SDL localization.

Okay, yes, I believe this naming would be pretty confusing.

> I thought of using a macro to point to the head unit language but it might change over time and I didn't figure out how to deal with that.

I would figure that this would just call a method that pulls whatever the current localization's usage of the word is, like the `NSLocalizedString` macro. I think that could work; I'm not sure why the localization changing over time would make it not work?

> It might be a good idea to have a localization manager who takes care about OnLanguageChange, ChangeRegistration etc.

But, to be clear, that is not contained in this proposal.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, and allow some of the implementation details discussed in the comments on this review issue to be determined by the author and project maintainer upon implementation of the feature.  These details involve cleaning up the interface and making modifications to the classes.

**Comment by theresalech** [comment]
Issues Entered:
[Android](https://github.com/smartdevicelink/sdl_android/issues/635)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/769)
