### ISSUE TITLE
[Accepted with Revisions] SDL 0100 - New data transfer interface in Android Proxy for streaming

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#297]
Hello SDL community,

The review of "New data transfer interface in Android Proxy for streaming" begins now and runs through September 26, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0100-new-data-transfer-interface-for-streaming-android.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/297

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
I believe this proposal is a good addition to the project. However, I would take note of a few minor things.

1. the interface might be confusing for developers who are not familiar with video streaming standards. Most app developers will likely not understand the different streaming formats and we should keep our focus on abstracting away from that.
2. The interface API should not depend on H264 streaming directly. We should generalize `H264StreamFormat`and how the public API takes in the argument to be more general for use with other codecs. 
3. It would be my recommendation that we deprecate the current public methods that use the piped streams. 
4. I would also like the new methods to be more general like `startVideoStream` and `startAudioStream` as the original implementation was directly tied to h.264 and PCM, we have since agreed it is possible to use different formats and the API should reflect that.

**Comment by shoamano83** [comment]
Hi @joeygrover, thank you for your comment.
My intention was to concentrate on existing codecs (H.264 and PCM) to make the changes minimum, but I am happy to extend the API to support more codecs which may be available in future.

> 1. the interface might be confusing for developers who are not familiar with video streaming standards. Most app developers will likely not understand the different streaming formats and we should keep our focus on abstracting away from that.
> 2. The interface API should not depend on H264 streaming directly. We should generalize `H264StreamFormat` and how the public API takes in the argument to be more general for use with other codecs.

I agree on these points. However, designing a generic API that supports every codec and every format is a tough work.
Therefore I propose to make the input video format aligned with Android's `MediaCodec`. Most developers should be happy with this since they can just copy MediaCodec's encoder outputs to the Proxy's API without tweaking any data. Also, this aligns with current `startH264()`'s specification (although it is not documented.)

> 3. It would be my recommendation that we deprecate the current public methods that use the piped streams.

Sounds good to me. Is there anything I should do to deprecate existing APIs, apart from putting `@Deprecated` annotation into the code?

> 4. I would also like the new methods to be more general like `startVideoStream` and `startAudioStream` as the original implementation was directly tied to h.264 and PCM, we have since agreed it is possible to use different formats and the API should reflect that.

OK, I'll update my proposal to accept multiple codecs.
One issue I faced is that some audio codecs (like AAC) have additional information, and I need to make the API flexible. My idea is to introduce `AudioStreamingParams` class and its sub-class for every codec. If you have better idea, please let me know.

**Comment by shoamano83** [comment]
@joeygrover I updated the proposal in this PR: https://github.com/smartdevicelink/sdl_evolution/pull/302

The extension is fairly large so I guess we need another week of review period to make sure everyone is happy on it.

**Comment by shoamano83** [comment]
One more thing which is not directly related to this proposal - I would like to have clarification of the Audio Streaming's default format. Probably @tpulatha knows these?
- How many channels are there in audio stream? i.e. 1 (mono) or 2 (stereo)?
- LPCM data format has some variations. When we say "16 bits", is it signed or unsigned integers? And is it in little endian or big endian?
I guess it's "signed integers, little endian" since that's the majority of LPCM data, but I just want to make sure.

I plan to reflect these information to the doxygen comment of `startAudioStream()` API.

Thanks!

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal with the revisions included in https://github.com/smartdevicelink/sdl_evolution/pull/302.

**Comment by theresalech** [comment]
PR has been merged and issue has been entered: [[SDL 0100] New data transfer interface in Android Proxy for streaming](https://github.com/smartdevicelink/sdl_android/issues/618)
