### ISSUE TITLE
[In Review] SDL 0123 - SendURI

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#365]
Hello SDL community,

The review of "SendURI" begins now and runs through December 19, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0123-SendURI.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/365

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
After reading the proposal, I'm struggling to see the benefit. Assuming a driver was stopped/not driving and was able to safely view a web page, why not just open it up on the phone? Instead of the app sending a URI to the module, why not just have the app open it up on the phone via a button press on the module? Including web browsers into head units themselves will be a challenge as it is not feasible to test every page and every new web element, the inclusion leads to a whole new kind of interoperability testing; SDL would have to be setup to respond correct based on any issues with the OEM's included browsers.  Adding this behavior will introduce a decent size of additional requirements for driver safety as well as new test cases to ensure Core handles all the potential scenarios correctly. I don't believe in adding functionality that we have to maintain if it doesn't provide an observable benefit. Therefore, I would have to reject this proposal until there is evidence that OEMs want this behavior and can demonstrate it will work within the boundaries of current driver distraction guidelines.

**Comment by dportis** [comment]
Our thoughts on the proposal is that this functionality would serve as a part of the foundation for AVs and some use in vehicles today. As it pertains to users using their phone instead of the HMI, we studied current Tesla users. We did this because Tesla has vehicles in production that have a built in web browser. 

[https://teslamotorsclub.com/tmc/threads/what-do-you-use-the-web-browser-for.81694/](url)

We viewed this forum to get an idea of how Tesla drivers use the browser in the vehicle. Some mentioned that they use the browser to check flight status and look up housing prices while in a certain areas and many other uses. People are looking for a full web browser experience on a larger screen that they can't always get on their phones.

In our minds, the driver distraction would be handled by the OEM's web browser. This is because every OEM would have a different level of driver distraction and how they handle it.

Does this make sense?

**Comment by joeygrover** [comment]
If there is a full web browser in the vehicle why does the user need an app on their phone to send a URI for them to navigate to? Why not simply go to that website using the IVI system then? 

OEM's will have their own driver distraction rules but SDL needs to know how to respond to apps when they are enforced as well as knowing how the user will be informed of what is happening. 

Reading the forum posts they mostly seem negative about the browser experience in the vehicle. 

>I don't use the browser for anything. If I want to use a browser, I whip out my iPhone.

>90% is showing folks there is a web browser, the other 10% is checking weather while on trips (and 10% may be too high). Now that the Peacemaker page is no longer available, showing the web browser is not nearly as much fun.

There is a single person who mentions using it to find prices of homes while they drive through neighborhoods. 

I believe this is missing the point of SDL. SDL already has ways to push this information to the screen without relying on a web browsers. I don't believe this feature's introduction has enough potential to warrant its inclusion. I believe time would be better spent on integrating more apps (flight info apps, housing apps, etc) with SDL to use the mechanisms already in place today instead of introducing functionality that circumvents SDL by pushing consumers into websites that are likely not car UI friendly.

**Comment by kshala-ford** [comment]
I don't know if there's a decision yet on that proposal. Not sure if it is visible through the proposal but it could also be used to send a URI to other apps when they say they can accept a specified schema (e.g. a random app could tell a media app to play a song or go to the next song). Don't see that in the proposal actually...

**Comment by joeljfischer** [comment]
@kshala-ford Wouldn't that example you gave be used on-phone though? e.g. telling an app to play a certain song? Wouldn't that more or less just work via the built-in iOS / Android mechanisms?

**Comment by kshala-ford** [comment]
@joeljfischer IPC is very lmited to foreground apps only (at least for iOS). Sending such URLs on iOS would bring the other app to foreground which might not be connected to SDL or it's in HMI_NONE and not allowed to react on the URL...

Bottom line I would not recommend to use SendURL on iOS to communicate between SDL applications. I was hoping to be able to provide some sort of IPC over SDL.

**Comment by theresalech** [comment]
While reviewing this proposal, the project maintainer questioned if there was a plan to include this feature in a future release, as they believe that should have an impact on the vote.  From the project maintainer's perspective, if there is not a plan to include this functionality in members' implementations, the proposal should be rejected to avoid adding and maintaining functionality that isn't used.  The author noted that this proposal is meant to be more forward thinking, and that OEMs would not be obligated to leverage the capability, so the Steering Committee should decide if they want to allow SDL the capability of launching a web browser.  There were then questions about the use cases for this functionality.  The Steering Committee ultimately voted to defer this proposal, keeping it in review until the 2018-01-02 meeting, so that the authors of the proposal can attend the meeting and speak to the use cases of this functionality.

**Comment by theresalech** [comment]
After much discussion, the Steering Committee voted to reject this proposal.  During the Steering Committee meeting, the author of the proposal spoke to the advantages of the concept, notably allowing passengers to use the in-vehicle screen because it's larger than the phone screen, being able to click a bookmark on their phone to bring up content on the vehicle's infotainment system, and bringing a more convenient keyboard for built-in vehicle infotainment controls.  The Project Maintainer and some SDLC Members expressed concerns with potential security vulnerabilities, and wanting to understand a passenger use case experience (instead of hypotheticals) before approving this feature.  They mentioned that there are currently other means to get content on the in-vehicle screen (video out capability to use a phone's web browser and then mirror onto the in-vehicle infotainment system), and these means could be used as a bridge to implement the full solution described here if that's desired by the SDLC in the future.  It was ultimately determined that this proposal should be rejected, and that if in the future there are solid use cases for a feature like this that SDLC members would want to implement, another proposal can be entered with those use cases and additional details included.
