### ISSUE TITLE
[Accepted with Revisions] SDL 0124 - SDLImageUploadManager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#366]
Hello SDL community,

The review of the revised proposal "SDL 0124 - SDLImageUploadManager" begins now and runs through February 6, 2018. The original review of "SDLImageUploadManager" occurred December 13 through December 19, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0124-SDLImageUploadManager.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/366

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
A few questions and notes:

1. In "common developer integration (1)" you note: `If images are no longer present on the head unit between step 2 and when the show request is generated, images no longer display`

I'm curious what would cause this to happen, as unless the developer explicitly removes the image, even a "temporary" image should remain until a new ignition cycle.

2. In "common developer integration (2)" you note: App uploads image using putfile/filemanager using static filename with overwrite always enabled (ie "appname.jpg")
App never knows for sure what image is displayed. Often the wrong image can be displayed on the head unit.

This hasn't been our experience, after all if the developer uploads an overwrite image with the same name, they'll get a callback on whether or not it succeeded, and so they will know which image is displayed. We haven't had issues with not knowing which image is displayed.

#### Additional Notes
I foresee issues with the proposed interface. 

* I'm not sure how the generated naming / comparison with already uploaded / cached images happens. I'm assuming a hash to compare and that we are not actually locally caching images, as I can't think of a reason why that would be helpful.
* This interface won't work well for a media app updating the album art of the currently playing song. All of the uploaded artwork will remain on the system until another ignition cycle as the hash would be different and there's no way to specify that it should overwrite a different UIImage, unless the developer uses the file manager to delete the old one.
* "Overwrite" is pointless as the generated id will be unique unless the UIImage is the same, in which case there's no need to re-upload.
* There is no API for persistent images.
* No indication if the image should be uploaded as a PNG or JPG.

So unless I'm really misunderstanding something about the implementation, I'm not sure that this class is helpful for most cases. 

#### Proposed changes
* I think that an updated version of #268 is the best solution for this, but unfortunately have not had the time to continue work on the proposal yet. I would love to get it into 5.2 if possible as I think it'll fix a lot of the issues this proposal attempts to solve, and I would welcome help to get it updated after the previous workshop on it.

**Comment by Toyota-BSalahat** [comment]
> In "common developer integration (1)" you note: If images are no longer present on the head unit between step 2 and when the show request is generated, images no longer display

@Toyota-Sbetts might be able to speak more to this, but my understanding is that the head unit technically can free up space by clearing out stored images, particularly if the SDL application is no longer in full mode. I know we have seen a lot of issues where a SDL app tries to batch upload a lot of images at launch, and then fails to display any images later because for various reasons they are not actually present on the head unit. 

> In "common developer integration (2)" you note: App uploads image using putfile/filemanager using static filename with overwrite always enabled (ie "appname.jpg")
App never knows for sure what image is displayed. Often the wrong image can be displayed on the head unit.

This has also been an issue that we have observed with multiple production implementations. They often call show pointing at a generic name that is always reused ie "appname.jpg". Not infrequently this results in an imaging being displayed that is stale/not intended, as the show request is processed while the new image is still uploading.

> I'm not sure how the generated naming / comparison with already uploaded / cached images happens. I'm assuming a hash to compare and that we are not actually locally caching images, as I can't think of a reason why that would be helpful.

The actual comparison logic isn't defined in the proposal. A hash would probably make the most sense. I believe the proxy does cache the images already, but I am not sure it would make sense to tap into that for this.

> This interface won't work well for a media app updating the album art of the currently playing song. All of the uploaded artwork will remain on the system until another ignition cycle as the hash would be different and there's no way to specify that it should overwrite a different UIImage, unless the developer uses the file manager to delete the old one.

There would need to be some optimizations for this use case, but I don't think its a show-stopper. Some of this logic would need to be implemented to handle "out of disk space" errors anyways. Additionally, it would not be unusual caching behavior to automatically flush out images that have not been used in a while. 

> There is no API for persistent images.

This may need to be added to the API. It was left out initially because the logic/issues observed with persistent images has been lower than dynamic images. This would just be an additional flag to pass in to the API.

> No indication if the image should be uploaded as a PNG or JPG.

Same note as above.

> I think that an updated version of #268 is the best solution for this, but unfortunately have not had the time to continue work on the proposal yet. I would love to get it into 5.2 if possible as I think it'll fix a lot of the issues this proposal attempts to solve, and I would welcome help to get it updated after the previous workshop on it.

Agree that #268 is a necessary proposal. It will be required for improvements down the road. This proposal is meant to complement that one. One of the items that came out of our discussion over #268 was that it did not address the ins and outs of image uploading. Ideally app developers should not have to worry about image logic beyond passing the proxy a UIImage.

To achieve that interface goal, there will need to be a class that can handle all of the image uploading logic based on taking a UIImage. This proposal attempts to fill that role while also providing some basic optimizations based on issues that we have observed related to image uploading.

**Comment by joeljfischer** [comment]
> @Toyota-Sbetts might be able to speak more to this, but my understanding is that the head unit technically can free up space by clearing out stored images, particularly if the SDL application is no longer in full mode. I know we have seen a lot of issues where a SDL app tries to batch upload a lot of images at launch, and then fails to display any images later because for various reasons they are not actually present on the head unit.

This is interesting, as I was under the impression that it would more or less fill up until an ignition cycle. If this is the case, additional logic could be added to the file manager to refresh the remote files list on HMI FULL.

> This has also been an issue that we have observed with multiple production implementations. They often call show pointing at a generic name that is always reused ie "appname.jpg". Not infrequently this results in an imaging being displayed that is stale/not intended, as the show request is processed while the new image is still uploading.

You're right, I remember there being some module bugs involved with this we had to mitigate in our own app. We had to solve it by using different artwork names. Additionally, we had to work on a Core bug (I believe Toyota reported this bug with ListFiles) that could report non-persistent files as still being on the head unit when they are not. We had to write a little manager that would overwrite "existing" files that don't actually exist.

> The actual comparison logic isn't defined in the proposal. A hash would probably make the most sense. I believe the proxy does cache the images already, but I am not sure it would make sense to tap into that for this.

I can't think of what you're referencing with image caching, I don't think this is happening anywhere...

>> This interface won't work well for a media app updating the album art of the currently playing song. All of the uploaded artwork will remain on the system until another ignition cycle as the hash would be different and there's no way to specify that it should overwrite a different UIImage, unless the developer uses the file manager to delete the old one.

> There would need to be some optimizations for this use case, but I don't think its a show-stopper. Some of this logic would need to be implemented to handle "out of disk space" errors anyways. Additionally, it would not be unusual caching behavior to automatically flush out images that have not been used in a while.

Cache invalidation is very difficult, and rolling our own cache would be quite difficult without using something like [PINCache](https://github.com/pinterest/PINCache). Furthermore, I'm not certain what the behavior is when attempting to delete an image that is in-use with Core HMI. For example, if we reach our size limit on the cache or reach our limit on the head unit, how do we choose which files to delete? It's difficult to know what we need and what we don't, and how we notify the developer what they need to re-create / re-download/upload. I'm concerned about our ability to "do the right thing" all of the time.

I'm also questioning the usefulness of the local cache. The proposed API requires the developer to pass in a `UIImage`, so why would we locally cache if they already have to have the image anyway?

>> There is no API for persistent images.
> This may need to be added to the API. It was left out initially because the logic/issues observed with persistent images has been lower than dynamic images. This would just be an additional flag to pass in to the API.
>> No indication if the image should be uploaded as a PNG or JPG.
> Same note as above.

At this point, this is essentially the API for creating an `SDLArtwork` minus the `name` parameter. We could just use `SDLArtwork` and add an initializer without a name that hashes and sets a name with that, and pass in the `SDLArtwork`. I'm not seeing much of a difference between the proposed API and `SDLArtwork` + `SDLFileManager` minus auto-hashing / generating the name. Can you go into further detail of what the internals of the manager intends to do to help the dev?  I'm still wondering if this is best rolled into the file manager or rolled into the theoretical show manager. I'm not convinced this needs to be a separate API / manager.

**Comment by Toyota-BSalahat** [comment]
> This is interesting, as I was under the impression that it would more or less fill up until an ignition cycle. If this is the case, additional logic could be added to the file manager to refresh the remote files list on HMI FULL.

Agree this could be a partial solution, however my impression is that app developers are simply not using the remote file list most of the time. Most implementations seem to fire and forget images, and our goal was to rework the proxy image API to better support that behaviour.

> I can't think of what you're referencing with image caching, I don't think this is happening anywhere...

There are a few references in SDLArtwork and SDLFileManager about UIImages being stored in temporary files. After reviewing further, I think right now those temporary files/directories are flushed out when the upload completes, or when the proxy disconnects.

> Cache invalidation is very difficult, and rolling our own cache would be quite difficult without using something like PINCache. Furthermore, I'm not certain what the behavior is when attempting to delete an image that is in-use with Core HMI. For example, if we reach our size limit on the cache or reach our limit on the head unit, how do we choose which files to delete? It's difficult to know what we need and what we don't, and how we notify the developer what they need to re-create / re-download/upload. I'm concerned about our ability to "do the right thing" all of the time.

The idea is that any time the app is going to show an image, they always route the UIImage through the image manager. If the image is already on the head unit, then an ID is returned and the app can go about its business, if the image doesn't exist the callback is executed when the image is uploaded and the id is available. In this case, even if the wrong image is dropped because of size constraints, it would just be reuploaded the next time the app tries to use it, without the app developer really needing to worry or perform the check themselves. I think this allows us to stick with relatively simple caching logic, but 

> At this point, this is essentially the API for creating an SDLArtwork minus the name parameter. We could just use SDLArtwork and add an initializer without a name that hashes and sets a name with that, and pass in the SDLArtwork. I'm not seeing much of a difference between the proposed API and SDLArtwork + SDLFileManager minus auto-hashing / generating the name. Can you go into further detail of what the internals of the manager intends to do to help the dev? I'm still wondering if this is best rolled into the file manager or rolled into the theoretical show manager. I'm not convinced this needs to be a separate API / manager.

Yes and no. The proposed API wraps the creation of SDLArtwork and the management of the upload process into one API and tried to cover some of the logic that should be common across most/all implementations. 

Currently the onus is on the app developer to track if an image is currently available on the head unit, to handle managing their space on the head unit, to manage when they can re-use an image id because it is already on the head unit, and when they need to perform an actual upload. It is also up to them to detect upload errors and recover by attempting the upload again at a later time.

For some integrations this level of management may make sense, but from the issues that we have observed it seems like this logic is a burden, and often not implemented well. We think it would be better to try to roll as much of it possible into the proxy, and let app developers just worry about passing in the UIImage they want to display.

This could be done via a new manager as in the current proposal, or by several targeted enhancements to the existing APIs. The local cache could potentially be bypassed if we generate the image name/id from the hash of the image, and replace checking of the local cache with checking of the remote file list.

ie

````
let sdlImage = SDLArtwork(uiImage) //add a SDLArtwork init that generates the ID from a hash of the image.

let existingImage = fileManager.upload(sdlImage) { newImageId in //Add a upload variant that will return the generated ID if the file is reported as existing in the remote file list, or performs the upload and returns the id in a callback block once uploaded. 
    let show = UIShow()
   show.graphic = SDLImage(newImageId)
  //send show
}.map { existingImageId -> SDLImage in
   return SDLImage(existingImageId)
}

existingShowRequest.graphic = existingImage

````


````
let existingImage = fileManager.upload(uiimage) { newImageId in //Add a upload variant that will return the generated ID if the file is reported as existing in the remote file list, or performs the upload and returns the id in a callback block once uploaded. In this case the file manager also handles generation of the SDLArtwork.
    let show = UIShow()
   show.graphic = SDLImage(newImageId)
  //send show
}.map { existingImageId -> SDLImage in
   return SDLImage(existingImageId)
}

existingShowRequest.graphic = existingImage

````

Would be an equally improved interface. The goal is just to bring tracking existing images and some of the boilerplate logic into the proxy so that apps can deal with image logic in a few lines of code, and reasonably expect that the intended image is the image displayed on the HMI.

**Comment by joeljfischer** [comment]
* I think that this really does approach the complexity of API surface as `SDLArtwork`, I think it would be better to re-use `SDLArtwork` but to add a new initializer to auto-generate a `name` based on a hash of the image. I largely am happier with the second-to-last suggestion at the bottom, but it would not work as is, at a minimum we need to know what the format of the image should be when uploaded. The rest can default to non-persistent, non-overwrite, but those options still need to be available as well, which is why I think `SDLArtwork` should be used.
* I've reported the `ListFiles` bug, this would probably fix some of the bad behavior you've seen https://github.com/smartdevicelink/sdl_ios/issues/827
* If we remove images for the developer, I don't know what the behavior would be if the image is still onscreen. That's unlikely, but if it occurs, the developer has no way to fix it. Still, because it is unlikely, the best solution is probably to delete the oldest non-persistant uploads from the remote system until we reach an acceptable level of open space. I don't know what that would be, perhaps 10% or so. This would certainly introduce some new complicated behaviors to the `FileManager`

**Comment by Toyota-BSalahat** [comment]
> I largely am happier with the second-to-last suggestion at the bottom, but it would not work as is, at a minimum we need to know what the format of the image should be when uploaded.

I think the option to specify should remain, but I am not sure it would hurt to have it default to one or the other if not specified, or perhaps let the app just flag the format they want to default to somewhere, since the UIImage object can be used either way. Another option would be to just detect the image type. Are there implementations that frequently toggle between specifying png and jpg? From the logs I have reviewed, it generally seems like they pick one or the other and stick with it.

**Comment by joeljfischer** [comment]
PNGs are better for interface elements and anything requiring transparency while JPGs are better for things like album artwork. So, for example, in the music app we work on the shuffle and repeat artworks for soft buttons are uploaded as PNGs so they can have transparency while album artworks are uploaded as JPGs. We could do something like persistent images are by default PNGs, the rest are JPGs. Detecting the image type [isn't possible with a UIImage](https://stackoverflow.com/a/7217423/1221798). We could have the dev specify a default, but I'm not sure where that would be (create a new file manager configuration?), and it seems kind of odd. I just worry about when we don't "do the right thing".

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for the following revisions agreed upon by the author and project maintainer:

```let sdlImage = SDLArtwork(uiImage) //add a SDLArtwork init that generates the ID from a hash of the image.

let existingImage = fileManager.upload(sdlImage) { newImageId in //Add a upload variant that will return the generated ID if the file is reported as existing in the remote file list, or performs the upload and returns the id in a callback block once uploaded. 
    let show = UIShow()
   show.graphic = SDLImage(newImageId)
  //send show
}.map { existingImageId -> SDLImage in
   return SDLImage(existingImageId)
}

existingShowRequest.graphic = existingImage```

**Comment by theresalech** [comment]
The author has updated this proposal per the agreed upon revisions, and the revised proposal is now review ready.

**Comment by theresalech** [comment]
The revised proposal has now moved into review, and the Steering Committee will vote on this revised proposal during the 2018-02-06 meeting.

**Comment by joeljfischer** [comment]
I approve of the revised proposal (with changes noted below). The goals of the proposal are worthwhile and the implementation seems sound. 

However, there is a minor requested revision to support the code provided in the proposal. The below code is provided by the proposal:

```swift
let sdlImage = SDLArtwork(uiImage) //add a SDLArtwork init that generates the ID from a hash of the image. This could have default arguments for persistence and image type, or could remain verbose as it is currently

let existingImage = fileManager.upload(sdlImage) { newImageId in //Add a upload variant that will return the generated ID if the file is reported as existing in the remote file list, or performs the upload and returns the id in a callback block once uploaded. 
    let show = UIShow()
   show.graphic = SDLImage(newImageId)
  //send show
}.map { existingImageId -> SDLImage in
   return SDLImage(existingImageId)
}

existingShowRequest.graphic = existingImage
```

This code wouldn't work even after the proposed changes, due to `SDLImage` not having an initializer that works like this. The closest equivalent is `SDLImage(name: existingImageId, ofType: .dynamic)`. I would request that the proposal include a revision to add two new initializers: `[SDLImage initWithName:(NSString *)]` and `[SDLImage initWithStaticImageValue:(UInt16)]`. This would get closer to the code in the proposal with a Swift code of `SDLImage(name: existingImageId)`. I'm not sure that we'd want to go further to no label at all, like is in the proposal.

(As an aside, it would be preferable to have most code in proposals in Obj-C, as that is the language sdl_ios is written in)

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions are outlined in the last comment from joeljfischer.  There was also discussion about the relationship between this proposal and [SDL 0133 - Enhanced iOS Proxy Interface](https://github.com/smartdevicelink/sdl_evolution/issues/379).  It was ultimately determined that this proposal could be accepted with revisions as it is relatively low level in comparison with SDL 0133, but the scope of this proposal would also be considered during the Enhanced iOS Proxy Interface workshop.

**Comment by theresalech** [comment]
@Toyota-BSalahat please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the iOS repository for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised to include agreed upon changes and issue has been entered:

[[SDL 0124] SDLImageUploadManager](https://github.com/smartdevicelink/sdl_ios/issues/865)
