### ISSUE TITLE
[Accepted] SDL 0126 - ATF support of additional transports (BT and USB)

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#372]
Hello SDL community,

The review of "ATF support of additional transports (BT and USB)" begins now and runs through January 23, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0126-atf-additional-transports.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/372

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
This is a good test case but i am concerned about maintaining another testing application.

Also wouldn't this ATF mobile application make the current ATF obsolete? I guess the only advantage current ATF would have over this mobile app is the ability to support CI testing.

I would suggest we do some research about leveraging current ATF to support usb or bluetooth instead of making a new application.

I am not sure about faking a AOA connection from a linux device, but I know that it is easy to fake an SDL bluetooth connection.

**Comment by JackLivio** [comment]
Ignore the above comment, I misunderstood that the proposed application would be used in conjunction with existing ATF platform. I approve of this proposal.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0126] ATF support of additional transports (BT and USB)](https://github.com/smartdevicelink/sdl_core/issues/1990)
