### ISSUE TITLE
[Rejected] SDL 0136 - Remote Control - SDL Module

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#388]
Hello SDL community,

The review of "Remote Control - SDL Module" begins now and runs through February 6, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0136-rc-sdl-module.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/388

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm not super familiar with Remote Control, so I apologize for any dumb comments.

**SdlAppControlData**

* `<param name="type" type="AppHMIType" mandatory="false">` Should this be an array?
* `<param name="containsRpc' type="boolean" mandatory="false">` I'm not entirely sure what this struct is supposed to do. Perhaps some parameters need to be manadatory for clarity?

**SDLAppControlCapabilities**

* `<param name="moduleName" type="String" maxlength="100" mandatory="true">`
* `<param name="moduleUUID" type="String" mandatory="false">`
  * Why is the UUID optional and the short name mandatory? No max-length on the UUID? How does the developer generate the UUID?
* `<param name="writeableRPCs" type="FunctionID" array="true" minsize="0" maxsize="10000" mandatory="false">` I feel like we're going to have to give some pretty good guidelines for this. For example, if a media app wants to display what they're playing onto a running app that exposes `SHOW` how do they know that's what they should be putting there as opposed to, say, a weather app that wants to print out the current weather?

**Comment by joeygrover** [comment]
> `<param name="type" type="AppHMIType" mandatory="false">` Should this be an array?

- This is meant to be similar to the type of service the app is offering. If you see the alternatives you'll see comments on this. See [here](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0136-rc-sdl-module.md#new-app-types).


> `<param name="containsRpc' type="boolean" mandatory="false">` I'm not entirely sure what this struct is supposed to do. Perhaps some parameters need to be manadatory for clarity?

- It is a flag to convey that the bulk data that is contained in this packet is in fact an RPC.

>`<param name="moduleName" type="String" maxlength="100" mandatory="true">`
>`<param name="moduleUUID" type="String" mandatory="false">`
>Why is the UUID optional and the short name mandatory? No max-length on the UUID? How does the developer generate the UUID?

- Just following previous control capabilities structs for mandatory. See [Radio's](https://github.com/smartdevicelink/rpc_spec#radiocontrolcapabilities). It likely makes sense to ensure the UUID is mandatory too in this instance. 
- The core module should be responsible for creating the UUID for the virtualized module. As this happens at runtime and will be unique to that head unit's implementation I see no need to create constraints. but if is seen otherwise they can be included.

>`<param name="writeableRPCs" type="FunctionID" array="true" minsize="0" maxsize="10000" mandatory="false">` I feel like we're going to have to give some pretty good guidelines for this. For example, if a media app wants to display what they're playing onto a running app that exposes SHOW how do they know that's what they should be putting there as opposed to, say, a weather app that wants to print out the current weather?

- I think there's a misinterpretation on how this system is intended to work. Apps will not push their `Show` data to be displayed on specific apps, rather apps that want to listen for data can do so, this is where the `Show` function ID would be included into the readable array. One app should never directly tell another app what to `Show`. However, an app can include that rpc in this list and advertise it is willing to accept those requests. This array is specifically for including RPCs that align with features that are published by this app. For example, SendLocation. I agree that we need to create a more extensive guideline, but as discussed in the Steering Committee meeting this was to serve has a decent high level proposal as an alternative to the SendLocation to Mobile Nav proposal (#368) so we can discuss different approaches.

**Comment by yang1070** [comment]
```xml
    <param name="writeableRPCs" type="FunctionID" array="true" minsize="0" maxsize="10000" mandatory="false">
         <description> This array can contain the list of RPCs that another app or module could write to or set in this module/app. If an array is not included, it is assumed all RPCs are supported. </description>
    </param>
    
        <param name="readableRPCs" type="FunctionID" array="true" minsize="0" maxsize="10000" mandatory="false">
         <description> This array can contain the list of RPCs that can be read/requested from this module/app. If an array is not included, it is assumed all RPCs are supported. </description>
    </param>
```
Is there any example of what RPCs are writable/readalbe RPCs? Probably we need to clearly classify all existing RPCs into those categories.

**Comment by yang1070** [comment]
if param `containsRpc` (not mandatory) is present in struct `SdlAppControlData`, param `rpcFunctionId` must also be present. Is that correct?

**Comment by yang1070** [comment]
I agree that <param name="type" type="AppHMIType" mandatory="false"> shall be an array.

**Comment by yang1070** [comment]
The current design allows an app to publish services that receives existing RPCs, what if an app wants to provide a service that does not have a corresponding RPC yet (for example receives an URL and show the webpage). Shall SDL continue adding new RPCs for each new service, or SDL provides a framework to allow the app to define the service (parameters and their types, and expected results, etc. in the capabilities)?

**Comment by yang1070** [comment]
there are two `<function name="SendInterAppRequest" messagetype="request">` in `Alternatives considered` section

**Comment by kshala-ford** [comment]
It's not that easy for me to follow the proposal completely. 

I'm trying to figure out what's the difference for an app to use `SendLocation` directly for an embedded navigation system compared to `SendLocation` over `SetInteriorVehicleData`. Does the app has to identify that and encapsulate the request all manually? 

How would an app subscrbe to waypoints? 

with uuids I understand multiple apps can offer reading and writing the same function ID. How would the app know to which one to send the location request?

**Comment by joeygrover** [comment]
I believe we're looking for a bit higher level feedback more so than the very detailed. As this proposal was put together in a few hours, it serves more of a purpose to give an alternative to #376.

- Yes, as stated previously this needs to be flushed out since this is only the high level alternative. If it is agreed that this is the direction of solution to go, we can fill this out more. In theory, any RPC could be writeable or just readable based on the receiving app's choices.
-  Yes, so the `containsRPC` flag could likely just be omitted and use the `functionID` param as both a flag that the packet contains an RPC in bulk data as well as the function id that is included.
- I don't believe it should be. Each virtualized module should be a specific service type. Again, reusing this enum might just be too confusing and a new one might need to be created.
- In my opinion, the inter-app communication scheme should always be tied directly to the protocol itself. There are plenty of easier ways to perform IAC on the mobile devices themselves. We should only focus on what enhances the SDL experience, not all apps experience. 
- This is just a typo, one should be the return type of that RPC, I believe it is easy to extrapolate out what it should be based on the other included RPCs.
- As stated in the downsides this is a possibility that app developers would have to keep track of these services and send them manually. However, it is possible to take a few different avenues. The most promising I see is the Core module actually does the routing and creation of the `SetInteriorVehicleData`. So  
    1. AppOne would send the `SendLocation` request to Core with no other identifier as to its destination. 
    2. Core recognizes which Nav solution is currently being used, in this example AppTwo.
    3. Core wraps the `SendLocation` request into a `SetInteriorVehicleData` that is then sent to AppTwo.
    4. AppTwo gets the request, parses out the `SendLocation` performs the logic, and returns a `SetInteriorVehicleData` response with the `SendLocation` response as the bulk data.
    5. Core receives the responses, parses out the `SendLocation` response and sends it back to AppOne.
- Similar to the above example, Core would still be responsible for routing the subscription request. 
- Again, I believe Core should be the responsible party for determining where the location requests go. 

 I am very open to suggestions on this proposal and I believe a workshop is better suited to move forward with how we handle IAC. I think this alternative provides a much more exhaustive approach to functionality for IAC, but does present challenges on how to implement.

**Comment by robinmk** [comment]
A workshop would be useful. Some of the use cases we should cover:
SendLocation
WayPoints
DialNumber

Below are a few feedback on the proposal which we can focus for improvement during the workshop:
1. Requesting app should continue to send requests as it does today without having to encapsulate the request in a RC (or any other) RPC. 
2. The requesting app should not need to know to whom it is sending the request - It should send it to core and core should be able to figure out to which service application the request should be forwarded.
(I see that points 1 and 2 are covered in your earlier comment)
3. Handling of policies needs to be considered.
4. Should the RPCs be renamed? Tagging it as RC seems a bit misleading.
5.  Reduction of complexity on app side
6. Weighing various options/alternatives.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, as they agreed that more detailed discussion should occur in a workshop setting to compare the two proposals describing inter-app communication: this proposal and [SDL 0130](https://github.com/smartdevicelink/sdl_evolution/issues/376). This proposal will be deferred until a workshop takes place to determine next steps.

**Comment by theresalech** [comment]
It was determined in the workshop that this proposal may be too generic, and a separate proposal should be entered describing a Pub/Sub Service Model with Custom URI Schemes.  Additional details of the new proposal can be found in the workshop meeting minutes.

**Comment by theresalech** [comment]
The Steering Committee voted to reject this proposal in favor of [SDL 0167 - App Services](https://github.com/smartdevicelink/sdl_evolution/issues/485).
