### ISSUE TITLE
[Accepted] SDL 0138 - Make 'audioPassThruCapabilities' of HMI an array

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#393]
Hello SDL community,

The review of the revised proposal "SDL 0138 - Make 'audioPassThruCapabilities' of HMI an array" begins now and runs through February 20, 2017.  The original review of "Make 'audioPassThruCapabilities' of HMI an array" occurred February 7 through February 13, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0138-hmi-audiopassthru-capability.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/393

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by AndrewRMitchell** [comment]
I guess since we are bumping the XML interface version number, I'd expect some sort of callout in the "Impact on existing code" section around version checks instead of simply stating that OEM's should update their HMI at the same time they update Core. Especially since it's not only not backward compatible but its breaking as both sides must be at the same version. But I'm still trying getting comfortable with the specification, and may be stating something that is obvious on the vehicle side of the world.

**Comment by shoamano83** [comment]
Thank you for your comment @AndrewRMitchell . My understanding is that we should always keep backward compatibility in MOBILE_API.xml since we have "old Proxy connecting to new Core" and "new Proxy connecting to old Core" cases. However I am not sure whether we should do same for HMI_API.xml. In most cases, both Core and HMI should be under control of OEMs and they are likely updated at the same time.

> I guess since we are bumping the XML interface version number, I'd expect some sort of callout in the "Impact on existing code" section around version checks instead of simply stating that OEM's should update their HMI at the same time they update Core.

Please correct me if I'm wrong, but I think we don't have any mechanism to convey the API version Core is using to HMI and vice-versa. I guess version checking is simply not available between Core and HMI.

**Comment by AndrewRMitchell** [comment]
Still learning about all this. I guess I don't see anything now that you mention it. From my past experience being able to check versions between two libraries built and run separately from one another (even if on the same hardware), is a good thing. It doesn't however look like that capability is currently there, and I assume testing would figure this out before it made its was to a customer. I just like having something that explicitly finds version incompatibility rather then hoping either automated testing or human testing is able to discover it. Apologize for not knowing the specification fully yet.

**Comment by joeljfischer** [comment]
> However I am not sure whether we should do same for HMI_API.xml

We do not *necessarily* need to do this, however, I would imagine this would cause a major ("breaking") change to Core and would require a version bump to 5.0 to make it clear that older HMIs are incompatible with the new version of Core.

> I think we don't have any mechanism to convey the API version Core is using to HMI and vice-versa.

We do, as you note in the HMI_API.xml spec
```xml
-<interface name="UI" version="1.2.0" date="2017-09-05">
+<interface name="UI" version="1.3.0" date="2018-01-24">
```

However, your proposed version change is incorrect. According to semantic versioning, this would need to change to `2.0.0` due to the incompatible change. This is a major potential downside.

**Comment by shoamano83** [comment]
Thanks for your comments @AndrewRMitchell , @joeljfischer.

OK, if we should avoid the incompatible change then we should choose another approach.
As I wrote in "Alternatives considered" section, an idea is to append an optional parameter `audioPassThruCapabilities2` (I think I should rename it to something like `audioPassThruCapabilitiesList`). Core checks both old and new parameters. If the new parameter exists, Core uses it instead of the old `audioPassThruCapabilities` param. Otherwise Core uses the old param to keep current behavior. I think this looks confusing, but should work.

**Comment by joeljfischer** [comment]
@shoamano83 That should work to keep backward compatibility, however, it would be pretty confusing due to the old one being mandatory (so it still needs to be set with one of the options), and the other is optional. I think it's still the best option available so documentation will just have to be good.

**Comment by JackLivio** [comment]
The alternative solution will work. Please add parameter descriptions for `audioPassThruCapabilities` and `audioPassThruCapabilitiesList` in the hmi_api.xml. On the next major release of core we can remove `audioPassThruCapabilities` and make `audioPassThruCapabilitiesList` the only parameter.

**Comment by AndrewRMitchell** [comment]
As long as we create an issue to track this so it doesn't get forgotten about, I'm +1 on this idea. And I like the name `audioPassThruCapabilitiesList` better then `audioPassThruCapabilities2` as its more descriptive, and doesn't leave us with `audioPassThruCapabilities2` in the future with no equivalent `audioPassThruCapabilities` leaving newcomers wondering what happened.

**Comment by shoamano83** [comment]
Thanks everybody. So I think we are reaching consensus on using `audioPassThruCapabilitiesList` idea.

I revised the proposal document to align with the idea. If you have time before the SDLC call, please kindly review:
https://github.com/smartdevicelink/sdl_evolution/pull/403

Thanks.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for the revisions included in PR #403.  That PR has now been merged, and the revised proposal has moved into review.  The Steering Committee will vote on this revised proposal during the February 20, 2018 (2018-02-20) meeting.

**Comment by joeljfischer** [comment]
I approve of the update.

**Comment by theresalech** [comment]
The Steering Committee has fully agreed to accept this proposal.  It was noted that issues will be added to the project pages for the next major version releases of Core and the RPC Spec to ensure we remove `audioPassThruCapabilities` and make `audioPassThruCapabilitiesList` the only parameter.

**Comment by theresalech** [comment]
Issues Entered:
- [Core](https://github.com/smartdevicelink/sdl_core/issues/2024)
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/63)
