### ISSUE TITLE
[Accepted] SDL 0139 - Clarification of audio format details of AudioPassThru

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#394]
Hello SDL community,

The review of "Clarification of audio format details of AudioPassThru" begins now and runs through February 13, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0139-apt-clarification.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/394

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by AndrewRMitchell** [comment]
Just one change for clarification, can we mention the fact that Audio is pegged to Channel 1 somewhere in addition to the Alternatives Considered?

i.e. in the Detailed Design can we add something like the following section:

**Audio Channel**

Since the audio format is monaural, it is necessary to pick a channel to default to. This is due to the fact that monaural audio requires a single audio source to avoid requiring mixdown, combined with the fact that most vehicles currently have only a monaural mic. For compatibility with the largest installed base, the channel selection is currently being fixed to channel 1.

**Comment by shoamano83** [comment]
Hi @AndrewRMitchell , thanks for your comment.

> Since the audio format is monaural, it is necessary to pick a channel to default to.

I think I need a clarification. Do you mean "SDL Core should pick channel 1 as the default channel when recording audio" ?

**Comment by AndrewRMitchell** [comment]
No, but the proposal as written implies that is what the SDL Core does in the Alternative Considered section ("Instead of fixing the channel number to 1,"). What I am asking is that if it is supposed to be fixed to Channel 1, that it is documented as such, as well as the reason why the decision is made. If it doesn't matter, then the Alternatives Considered doesn't really make sense and should either be removed or rewritten.

**Comment by shoamano83** [comment]
Thanks, I think I understand your intention. And the confusion came from my bad English.

In Alternatives Considered section, I meant to say:

"Instead of fixing the **number of channels** to 1, ..."

I didn't mean that Core should pick up a specific channel when recording.

So how about updating 'Alternatives Considered' section as follows? Could you review if it makes sense to you?

> Instead of fixing the audio stream to be monaural, extend AudioPassThruCapabilities struct to include information of the number of channels in the audio stream. The author did not investigate whether this change keeps backward compatibility. If such information is required, another proposal can be developed in future.

Thanks!

**Comment by AndrewRMitchell** [comment]
That looks great and addresses my issue.

Thanks for the change (and for bearing with me while I learn this stuff)!

**Comment by theresalech** [comment]
The `Alternatives Considered` section of this proposal has been updated per the comments above, and the Steering Committee has voted to accept this proposal.
