### ISSUE TITLE
[Withdrawn] SDL 0142 - Addition of 'App Instance ID' and 'Core Instance ID'

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#406]
Hello SDL community,

The review of "Addition of 'App Instance ID' and 'Core Instance ID'" begins now and runs through February 20, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0142-mt-instance-ids.md#addition-of-app-instance-id-and-core-instance-id

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/406

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Given [this comment on 0141](https://github.com/smartdevicelink/sdl_evolution/issues/405#issuecomment-366041405). I would prefer a solution that requires a connection over IAP (for iOS, perhaps Bluetooth / USB for Android) as the primary transport, and the Wi-Fi IP / Port given via the Start Service response. This proposal would then be unnecessary.

**Comment by shoamano83** [comment]
Thanks for the comment . I think 'App Instance ID' and 'Core Instance ID' are still necessary for some cases even with your idea written in the comment in SDL 0141.
I guess my explanation wasn't complete so let me clarify.

### App Instance ID

The issue is that when Core accepts an iAP connection from an App, say "App A", and a TCP connection also from "App A", then Core cannot know whether the two transports are initiated from a single app or not. OK, I know that with @joeljfischer 's idea an iOS Proxy will not initiate a TCP connection only. However, we still have such issue when "App A" on an iPhone initiates iAP connection through USB, and "App A" on another iPhone initiates an iAP connection through BT and a Wi-Fi (TCP) connection. In this case Core cannot distinguish to which app TCP connection belongs.

On Android, we may want to switch transports between Bluetooth / Wi-Fi / AOA. So for example, when "App B" is connected to Bluetooth, then USB cabled is plugged and the app also creates AOA connection, then Core has to know whether the two transports are initiated from a single app. (i.e. Somehow Core needs to know a single phone is connected with BT and AOA, or two different Android phones are connected.)

### Core instance ID

This ID is to make sure that Proxy is not connected to two different head units via multiple transports. So in the case of @joeljfischer 's idea, this ID is unnecessary for iOS Proxy; it always know the correct IP address and TCP port number of the head unit that is connecting through iAP.
For Android Proxy, I think the ID is still necessary if we need to support using Bluetooth SPP and AOA transports simultaneously.

**Comment by joeljfischer** [comment]
I disagree, I don't think the App Instance ID is still necessary. Core would still be able to distinguish the TCP connections because the IP / Port would be unique for each application after the IAP connection (whether through USB or BT). 

e.g. Phone 1 App A connects over USB. Start Service ACK returns with 198.1.1.1 port 1234, TCP connects. Phone 2 App A connects over BT. Start Service ACK returns with 198.1.1.1 port 2345, TCP connects. The port would be guaranteed unique for each connection and app.

**Comment by JackLivio** [comment]
@joeljfischer FYI the current TCP transport adapter in core only listens on a single port that is specified at startup (default 12345). There would need to be changes to have core listen on different ports for different apps.

**Comment by joeljfischer** [comment]
@JackLivio That would already be a requirement of the current proposal anyway.

**Comment by robinmk** [comment]
@joeljfischer , the proposal doesn't plan on using separate port numbers. The idea is to connect to a single SDL listener port num (eg 12345).

**Comment by robinmk** [comment]
We will approach SDL-WiFi based on the approach suggested by Joel. We will revise this proposal based on the new the design.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions, per the author's request.  The proposal will be revised based on the new approach described in the revisions for #405.

**Comment by theresalech** [comment]
The author has requested to withdraw this proposal. If another SDLC member would like to continue the efforts of this proposal, they can become the author.
