### ISSUE TITLE
[Accepted] SDL 0144 - Allow clients to specify legacy nicknames

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#410]
Hello SDL community,

The review of the revised proposal "SDL 0144 - Allow clients to specify legacy nicknames" begins now and runs through March 13, 2018. The original review of "Allow clients to specify legacy nicknames" occurred February 21 through March 6, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0144-app-nicknames.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/410

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by AndrewRMitchell** [comment]
Overall, I like this proposal, that being said, I do have several questions. (Oh, and to answer the above questions in my review: Yes, Yes, N/A, and In Depth Study.)

1) In the proposed solution, do you have any specifics on how you'd like to documentation for nicknames unified? I think leaving this ambiguous may lead to a result you're not looking for.

2) In the potential downsides, could this not be mitigated by providing back from the registration call the nickname that was used? This way App vendors could either tailor their UI for the Old Name, or at least alert the user that there is a discrepancy in names and why to hopefully keep confusion to a minimum.

3) In impact on existing code, how does this change affect version numbers. This would I expect require minor version number bump as it does change the interface and since we don't seem to increment the patch number.

4) In Alternatives Considered you may want to mention that the drawback is deemed to large and hence the reason this alternative was not chosen.

Andrew

**Comment by kshala-ford** [comment]
I agree with @AndrewRMitchell. In the past we (Ford Europe) ran into the same issue with a few apps requesting new nicknames.

I think the authors solution looks like as follows (this is just an example to start the discussion of how to solve it):
```xml
<function name="RegisterAppInterface" functionID="RegisterAppInterfaceID" messagetype="request">
  :
  <!-- existing parameter -->
  <param name="appName" type="String" maxlength="100">
     <description> ... </description>
  </param>
  <!-- newly added parameter -->
  <param name="appNicknames" type="String" maxlength="100" minsize="1" maxsize="100" array="true" mandatory="false">
    <description>
      The list of nicknames configured for the app ID. Depending on the head unit's stored policies 
      one of the listed nicknames will be used to register the application. The order of the list should
      be set starting with the most important nickname.
    </description>
  </param>
  :
</function>
```

As far as I understand SDL core should be able to implement the proposed solution as it's responsible for policies. Due to legacy it would start validation with `appName` and if this fails it continues to use `appNicknames` in the order as mentioned in the proposal. Once SDL core found a valid nickname it would tell the HMI that the app is regsitered using `OnAppRegistered`. There should not be any need for an HMI change. Overall this should be a minor version increase for the mobile API. @tvkanters Does this match your expectations?

**Comment by tvkanters** [comment]
Thanks for the feedback!

@AndrewRMitchell
1) I intentionally didn't make this too specific to allow the people with more in-depth knowledge about this topic to fill it in. Mainly, I would like it to be clear to developers how the app name(s) will be used and what the consequences of using/changing them are. E.g., the fact that they're used for validation along with the app ID is not apparent at all from the documentation of [application policies](https://smartdevicelink.com/zh-hans/docs/sdl-server/master/policy-table/application-policies/), [`RegisterAppInterface`](https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/RegisterAppInterface/) or [`SdlProxyALM`](https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/SdlProxyALM/). Even writing this proposal was complicated by the limited explanation of app names, as it wasn't clear to me how they're used and why they're used like that.

2) Having the core return the selected nickname could indeed help mitigate the downside to some extend. I think it won't be sufficient to remove all confusion however, as apps mainly present their name outside of a runtime context. (E.g., on the app stores or in the phone launcher.) An alert is an option, but also not ideal and might cause further confusion. Either way, it could give developers options to deal with the situation, so I would not be opposed to adding this to the proposal.

3) Based on the [versioning document](https://semver.org/) linked from the [process description](https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md), I would indeed expect this to warrant a minor version increment, both in the core and the Android/iOS SDKs. Would be good to clarify this in the proposal itself as well.

4) Would indeed be good to clarify this. This downside is somewhat of an assumption though. Despite efforts of asking around on Slack, I could not find the true motivation for linking the app ID to nicknames.

@kshala-ford 
Yep, something like that is what I had in mind! Would probably be good to include your example in the proposal to clarify it.

**Comment by tvkanters** [comment]
A pull request incorporating this feedback into the proposal has been created: https://github.com/smartdevicelink/sdl_evolution/pull/414

**Comment by theresalech** [comment]
We were unable to vote on this issue during the 2018-02-27 Steering Committee meeting as we did not have a quorum present in the meeting.  Voting will take place during the 2018-03-06 Steering Committee meeting, pending we have a quorum present.

**Comment by NickFromAmazon** [comment]
This looks good to me.
The one suggestion I'd have is to use something more descriptive than `appNicknames` as the param name, as I believe this will be confusing next to the other fields (`ngnMediaScreenAppName`, `appName`.)  If I understand this correctly the this list will specifically contain names that have been deprecated, so something like `legacyAppNames` or `deprecatedAppNames` could clarify the intent.

**Comment by tvkanters** [comment]
@NickFromAmazon Makes sense. I'll include that in the proposal revision.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for the revisions included in PR #414, updating the proposal to reflect the comments left on this review issue.  That PR has now been merged, and the revised proposal has moved into review. The Steering Committee will vote on this revised proposal during the March 13, 2018 (2018-03-13) meeting.

**Comment by theresalech** [comment]
The Steering Committee has fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/895)
[Android](https://github.com/smartdevicelink/sdl_android/issues/713)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2060)
