### ISSUE TITLE
[Accepted with Revisions] SDL 0146 - Updating Mobile Version Dependencies

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#421]
Hello SDL community,

The review of "Updating Mobile Version Dependencies'" begins now and runs through March 13, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0146-updating-mobile-version-dependencies.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/421

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by tpulatha** [comment]
I think creating hard rules for this item might be a problem. Given that the SDLC might have an important partner that supports pretty old OS versions. 
If we want to incorporate a feature into the libraries that requires a new feature which is only available if backwards compatibility is restricted, it might be a better idea to discuss it in the steering committee and decide based on the benefit of the new feature vs. the downside of potentially loosing app partners (or having app partners not updating)

**Comment by kshala-ford** [comment]
I have a question: what happens to the min version of the app if we increase the min version of the libs? To my understanding the app has to follow the highest min version of every included library. Otherwise it wouldn’t compile. I don’t think this would be acceptable for app developers as they would need to increase the app’s min version to the one we demand.

I think the case of a version increase should be reviewed annually depending on the benefits we gain.

**Comment by joeljfischer** [comment]
@kshala-ford That is correct, which is why we are putting an upper limit. Basically a proposal may not even be entered if the new minimum version would not cover 90% of users. The 97% minimum was merely attempting to make sure we are keeping the project current, but that limitation could be removed if OEMs are uncomfortable with that stipulation.

**Comment by theresalech** [comment]
The Steering Committee has voted to accept this proposal with revisions.  The revision will be removing the following requirement: 1. If a platform dependency update would cover 97% of users, that update should occur.

**Comment by theresalech** [comment]
@joeljfischer or @joeygrover please let me know when a PR has been submitted to make requested revisions to the proposal file.  Thanks!
