### ISSUE TITLE
[Accepted with Revisions] SDL 0148 - Template Improvements: Additional SubMenus

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#423]
Hello SDL community,

The review of "Template Improvements: Additional SubMenus'" begins now and runs through March 13, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0148-template-additional-submenus.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/423

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
👍 I believe the DriverDistractionCapability struct will be useful in the future if expanded for other types of limitations in addition to sub menu depth.

**Comment by tpulatha** [comment]
I have three topics for this: 

### Combined proposal

1. Allowing Core to define driver distraction parameters for HMI
2. Allowing Submenu's with parentID's that refer another Submenu

I support both, but wonder if we want to split for clarity.

### Default list item

Secondly, Carplay automatically adds a button to the bottom of the list if the list is restricted due to driver distraction. This button usually initializes some kind of Voice Interaction. I wonder if we want to allow a new flag for `choice` and `addCommand` that is named `truncatedListDefault=yes` or something along these lines. This item would be shown as the last item in a list, if the list is truncated for DD reasons. 

### Bulk addcommands

Currently it is pretty cumbersome to create these menu structures, especially for large list, when doing one addCommand at a time. I wonder if we want make this easier for app developers. Either by having a function in the proxy that accepts a object and sends the single rpc's or by allowing some kind of bulk uploading.

**Comment by joeljfischer** [comment]
Hi @tpulatha a few notes

> Default list item

I think a default list item is a good idea. I do wonder about implementation, however. I think Core / HMI automatically adding a list item at the bottom that starts a voice search for that list might be the best solution than a mobile / developer driven solution. So if you're in a list "Artists" then HMI would automatically have a list item at the bottom "Search Artists" which would start a voice session for the user to speak the name of an item in the list. Alternately, because the VR sequences can take so long to compile, if we don't have VR for that list it would say something like "Truncated for Safety".

> Bulk addCommands

In the latest proxy versions, there will be an addition to send multiple RPCs in one go. You still have to create each of the commands, but then you can pack them up in an array and send them. That will help, I'm not sure what more we can do without a new RPC.

**Comment by kshala-ford** [comment]
When talking about truncate do you mean to limit the list to the first n items? CarPlay shrinks most of the lists to the recently used items.

The additional item added to the end to start VR does that button open a VR session for the app or only for those in the current sub menu?

**Comment by joeljfischer** [comment]
@kshala-ford The idea would be for those in the current sub-menu

**Comment by tpulatha** [comment]
@kshala-ford Carplay does not necessarily only shrink to recently used, they also shrink playlists or artist lists. 

@joeljfischer I think a fixed VR functionality would miss a use case where an App has its own VR engine and might want to start something like an Alexa or Cortana interaction

**Comment by theresalech** [comment]
The Steering Committee has voted to accept this proposal with the following revisions: update proposal to only include details regarding "Allowing Submenu's with parentID's that refer another Submenu."  A separate proposal will be entered to discuss "Allowing Core to define driver distraction parameters for HMI."

When discussing submenus, a few additional points were made:
- Right now, this is only considered for submenus, but driver distraction guidelines could be extended to include choice sets for interactions as well (including list length)
- Proposal outlines the same behavior as is currently in place for submenus, but extends to allow a submenu to have a submenu

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!
