### ISSUE TITLE
[Accepted] SDL 0149 - Add capability to disable resumption based on app type and transport type

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#428]
Hello SDL community,

The review of the revised proposal "SDL 0149 - Add capability to disable resumption based on app type and transport type" begins now and runs through April 10, 2018.  The original review of "Add capability to disable resumption based on app type and transport type" took place March 21 - March 27, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0149-mt-registration-limitation.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/428

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by shoamano83** [comment]
Reflecting internal feedback.

> : section, resumption is enabled for an app with the AppHMIType.

This is typo, the first char should be ";" instead of ":".

> ; On the other hand, if you want to disable resumption and always keep an app in NONE and
> ; NOT_AUDIBLE state after registration, specify an empty value for the AppHMIType.

Here I meant an empty value is something like:
```ini
NAVIGATION =
```

(FYI, current Core code does not offer a handy way to distinguish between an empty value and the item being not found. But I think we can implement it.)

> Which means, when they are connected only with Bluetooth transport, their HMILevels are kept in NONE and they are put in NOT_AUDIBLE state.

The .ini file does not (and will not) explain the fact that iOS production apps will require iAP transport to use Wi-Fi transport. This is because it's not something an OEM will configure through .ini file. (iOS Proxy always utilize iAP transport unless tcpDebugMode is set in the lifecycle configuration.)

**Comment by AndrewRMitchell** [comment]
After chewing on this for a couple of days, my response has tempered a bit. My primary question is rather then simply not auto resuming, why not give Navigation apps especially the ability to opt in to a more limited experience (i.e. not using projection) to be able to still provide useful information to the user.

The use case I'm thinking of in particular is lets say it takes a couple minutes for the WiFi to come up, and all the endpoint negotiations to occur (I hope this is not the case), during that time if the driver was in an active navigation situation and stopped (lets say for gas) they are now without any information until after the WiFi connection comes up.

The reason I say let the Navigation app opt into this type of situation is I agree that simply having an empty HMI is a poor experience, and if the navigation provider does nothing (which is probably the default behavior) the only way to keep the user experience acceptable is to use the described method. But should a navigation provider choose to provide a more limited subset during this time (even potentially voice only), why block them from doing so?

This could also cover the (currently out of scope for this proposal) of what happens when the connection goes down while being used (which given interference is certainly possible while using 2.4 GHz if a vendor so chooses to do so).

Not trying to add more work, just trying to define the best user experience in a rough edge case.

**Comment by joeljfischer** [comment]
@AndrewRMitchell I think your critique brings up a good point, although there are some clarifications that I think would need to be made. Navigation apps can work without their streaming UI on screen in the `LIMITED` HMI state. They can provide Turn-by-Turn directions and such in that state; however, this proposal blocks navigation apps from doing so automatically upon reconnection. Perhaps we should consider allowing NAVIGATION apps to resume into the `LIMITED` state instead, and set up TBT if they already have navigation running? There's obviously no way to show the stream until Wi-Fi comes up (assuming they're not using USB either), but the user should have some amount of information about their route.

**Comment by shoamano83** [comment]
Thanks @AndrewRMitchell and @joeljfischer for your comments.

I think OEMs have different thoughts on what we should do when high-bandwidth transport isn't available. As Andrew suggested, one idea is to let the app work in non-streaming mode. A concern with this approach is that we will be likely to force app developers to implement two modes (video streaming mode and turn-by-turn mode) which sounds like a large amount of work. Another approach, which came from Ford team, is not to launch the app until the transport is available. In this case, HMI will show a non-SDL screen (such as app list) and will also notify the user that Wi-Fi or USB is required for the app to work.

I guess the first approach can be achieved with the configuration of multiple-transports feature. With accepted proposal [SDL 0141](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0141-multiple-transports.md), we can suppress video streaming on a Bluetooth transport through .ini file (i.e. make them only available over secondary transport.) So probably a navigation app will always update TBT screen regardless of video streaming is running or not. When video streaming is not running, HMI can show the TBT screen. I am not sure how TBT navigation is implemented, so please correct me if I'm wrong.

Currently, Core has a fixed behavior that will always resume the app. At least I would like to make it configurable, so that OEM can choose the second approach if they wish.

**Comment by joeljfischer** [comment]
@shoamano83 

> A concern with this approach is that we will be likely to force app developers to implement two modes (video streaming mode and turn-by-turn mode) which sounds like a large amount of work.

It is a best practice for app developers to do this already, or their app won't work in the background very well. It is also not a large amount of work. It's some work, certainly, but far less than getting the streaming app to work in the first place.

> Another approach, which came from Ford team, is not to launch the app until the transport is available. In this case, HMI will show a non-SDL screen (such as app list) and will also notify the user that Wi-Fi or USB is required for the app to work.

This approach would work, and is a better user experience, but I would rather see a mix of this and allowing the app to use the TBT API while waiting for Wi-Fi to come up or USB to be connected. Imagine if the user is in the middle of navigating and goes to get gas, turning off the engine. The phone still has their current progress of their navigation. The user finishes, turns back on the car, and now has to wait an indeterminate amount of time to have _any_ navigation at all on their vehicle. Ideally, they could at least get TBT while waiting for Wi-Fi to come up and connect. It would also alert the user that the full experience cannot display until USB or Wi-Fi is connected.

> So probably a navigation app will always update TBT screen regardless of video streaming is running or not. When video streaming is not running, HMI can show the TBT screen. I am not sure how TBT navigation is implemented, so please correct me if I'm wrong.

This seems correct to me. This would probably require https://github.com/smartdevicelink/sdl_evolution/issues/429

**Comment by robinmk** [comment]
@joeljfischer 
Are you thinking of an approach of putting the Navigation app in a HMI state of LIMITED and at the same time if the user tries to launch the Navigation app, have the system (HMI layer) display a pop-up asking the user to connect via USB/Wi-Fi ?

I feel if the necessary transports are not available, the experience should not be started/allowed.

**Comment by joeljfischer** [comment]
Maybe that needs wider discussion, but I think that's a better user experience than making the user wait for any navigation information at all until they connect when we have TBT information available. I don't like the approach of showing the app but not letting the user use it because the connection hasn't finished. If the app icon is there and the user is hitting the button to launch their nav and it's either (1) doing nothing, or (2) showing an error, that's a recipe for user frustration. In my mind, a progressive experience is much better. 

What if the user has Wi-Fi turned off on their phone for some reason? What if there's interference and the connection drops for no apparent reason? What if the Wi-Fi chip goes bad 5 years later? At least users will have some availability of their nav. Ideally, most of the nav use case would be possible, even without the map, (e.g. entering directions, etc.), but if not that, at least in-progress routes should be picked up by TBT, in my mind.

**Comment by joeljfischer** [comment]
via @robinmk 
> Having applications provide information (like TBT data) while Wi-Fi transport is not yet ready is a good idea, but the application should be able to support templated-approach in the meanwhile. The applications would also have to (re)register as a regular Non-media application for the template to be displayed.

I think this is a prohibitive requirement. No navigation app currently supports both video streaming and a templated approach. They all support video streaming and TBT data. Requiring them to re-register also makes for a poor user experience and significantly larger burden on developers.

via @AndrewRMitchell 

> My guess is if the App is in the foreground while TBT is running, the projection interface is being used at the same time. I can't really see a use case where this wouldn't be true unless the entire Nav app is written to support templates for full functionality.

Yes, both are generally used simultaneously.

> My personal preference would be to support TBT automatically when resuming Apps without a high-bandwidth transport available. You could resume them into the background in a LIMITED state, and put something on the HMI stating the App requires WiFi or USB for full functionality.

I'm in agreement with this. Basically don't allow the app to enter FULL. LIMITED with (if #429 is implemented) video as not allowed, should allow the NAVIGATION app to continue using TBT APIs.

> I would however let the Nav app opt into a templated approach IFF they so choose. This however would probably require work for some (if not all) Navigation Apps. (I assume they use a templated approach for their non-active states, but when under active navigation use the projection interface). But as we do not write a Navigation App using projection, I can't speak for other App providers.

This is probably (as I noted above) is actually, now that I think about it, not possible today. The developer would have to unregister as a NAVIGATION app and re-register as non-media, but then wouldn't have access to TBT APIs.

**Comment by robinmk** [comment]
So the use case is that the user was previously viewing the map, stops at a gas station and turns ignition off. Now when he turns the ignition ON, the device connects first via BT, the Navigation app registers via BT and WiFi is not available. Apps resumes to LIMITED and can possibly display a TBT (via the ShowConstantTBT RPC). The TBT is shown on a status bar on the top portion of the display. 
I assume that most users would try to launch the Nav app on the HU in-order to get back to their map, but the system blocks the launching of the app and informs the user about some issue in getting connected to Wi-Fi (or something similar). This might be confusing as there is data coming from the app and yet the system says there is a problem.
There could potentially be other cases to consider like what if an app tries to send an Alert button with a  softbutton of type StealFocus or what if the user wants to cancel the route or set a new route etc.

I also assume we would not resume a media (Projection) application to LIMITED under similar circumstances.

**Comment by shoamano83** [comment]
Let me just bring this up again that with the proposal [SDL 0141](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0141-multiple-transports.md), OEM can prohibit video streaming over Bluetooth transport (even in FULL level). This is achieved by NOT specifying "IAP_BLUETOOTH" and "SPP_BLUETOOTH" in `0x0B` key of `ServicesMap` section in the .ini file.

I am not sure if I understand the discussion correctly, but I feel like resuming into LIMITED level isn't mandatory to achieve Joel's use-case; the OEM keeps Resumption enabled in the .ini file, and also prohibits video streaming over Bluetooth. After ignition on, the navigation app will resume into FULL mode and will start TBT guidance, yet the video streaming will not start until Wi-Fi secondary transport is established.

**Comment by joeljfischer** [comment]
> Apps resumes to LIMITED and can possibly display a TBT (via the ShowConstantTBT RPC). The TBT is shown on a status bar on the top portion of the display.
I assume that most users would try to launch the Nav app on the HU in-order to get back to their map, but the system blocks the launching of the app and informs the user about some issue in getting connected to Wi-Fi (or something similar). This might be confusing as there is data coming from the app and yet the system says there is a problem.

`ShowConstantTBT` as well as `AlertManeuver` and others, yes. I think a message specifying that the map cannot be displayed could be somewhat confusing, but I think it's better than not allowing the app to show any data, or tell the user of any upcoming maneuvers.

> There could potentially be other cases to consider like what if an app tries to send an Alert button with a softbutton of type StealFocus or what if the user wants to cancel the route or set a new route etc.

Yes, certainly, there would be functionality that would be unavailable in allowing a nav app only into LIMITED when no stream is available. We could (as @shoamano83 says below) also allow them into FULL but with a message saying the stream isn't available without Wi-Fi or USB, etc.

> I also assume we would not resume a media (Projection) application to LIMITED under similar circumstances.

I believe that a media PROJECTION app is a *terrible* idea, for this and other reasons, but barring that objection, absolutely we could. The app should be allowed to stream audio and respond to hard buttons without having to wait for Wi-Fi to come up. Ideally, they would work in a templated manner until the stream came up. In the same (gas station) situation or if the user has Wi-Fi turned off on their phone, waiting to stream any audio while the stream is supposed to be set up is a bad user experience. Of course, not allowing the user to control the music is as well (hence that they should work in a template in the meantime, which is not currently possible).

> After ignition on, the navigation app will resume into FULL mode and will start TBT guidance, yet the video streaming will not start until Wi-Fi secondary transport is established.

In this case, the user would just have a blank screen, right? Unless it contained a message for this case, I'm not sure that's better than resuming to LIMITED. It is, however, likely much easier to accomplish technically, as I'm not sure we have a situation currently where we bar an app from entering FULL when pressed.

**Comment by JackLivio** [comment]
I would like to suggest having an additional field in the ini file that specifies what HMI_LEVEL each  AppHMIType should resume to.

i.e.
[AppHMITypeREsumptionLevel]
```
; DEFAULT_RESUMPTION_LEVEL =
; COMMUNICATION_RESUMPTION_LEVEL =
; MEDIA_RESUMPTION_LEVEL =
; MESSAGING_RESUMPTION_LEVEL =
NAVIGATION_RESUMPTION_LEVEL = LIMITED
; INFORMATION_RESUMPTION_LEVEL =
; SOCIAL_RESUMPTION_LEVEL =
; BACKGROUND_PROCESS_RESUMPTION_LEVEL =
; TESTING_RESUMPTION_LEVEL =
; SYSTEM_RESUMPTION_LEVEL =
PROJECTION_RESUMPTION_LEVEL = NONE
; REMOTE_CONTROL_RESUMPTION_LEVEL =
; "NONE" applies to apps that don't specify any AppHMIType
; NONE =
```

If left blank the default value could be NONE or FULL, or whatever value seems to be the most appropriate.

Each OEM might have different definitions of the "best user experience" and I think allowing for a more detailed customization of the resumption process would be the best solution.

**Comment by AndrewRMitchell** [comment]
I like Jack's idea, but I think it need to be clarified to AppHMITypeFallbackResumptionLevel, i.e., this level is only used if the TransportRequiredForResumption isn't available.

**Comment by shoamano83** [comment]
Thanks @JackLivio , that sounds like an idea that will satisfy everybody. I think LIMITED level is only for a few App types (NAVIGATION, PROJECTION and media apps) so I am not sure if we need configuration for _all_ AppHMITypes.

Looks like the discussion is focused on video streaming apps. How about adding an .ini file entry like:
```ini
VideoStreamingResumptionLevel = LIMITED  (This can be FULL, LIMITED, BACKGROUND or NONE)
```
instead? (Better naming is welcome.)

**Comment by theresalech** [comment]
The Steering Committee has voted to return this proposal for revisions.  The author will revise per the the comments on this issue, notably the additional .ini file entry included in [JackLivio's comment](https://github.com/smartdevicelink/sdl_evolution/issues/428#issuecomment-376634018).  In reference to that comment, it was agreed that this would only be used in high bandwidth situations when a high bandwidth transport is unavailable, and also noted that if an app has multiple HMI types, the highest of the types (None -> Background -> Limited -> Full) will be used.  An OEM can specify resuming into full if desired.  Per the author's request, this review issue will remain open to allow for any suggestions from SDLC members for a name instead of `VideoStreamingResumptionLevel`.

**Comment by shoamano83** [comment]
Thank you @JackLivio! I'm revising the document based on your naming.

**Comment by theresalech** [comment]
The author has updated this proposal per the requested revisions, and those revisions are now ready for Steering Committee review. This revised proposal will be in review until April 10, 2018.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0149] Add capability to disable resumption based on app type and transport type](https://github.com/smartdevicelink/sdl_core/issues/2130)
