### ISSUE TITLE
[Accepted with Revisions] SDL 0167 - App Services

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#485]
Hello SDL community,

The review of the revised "SDL 0167 - App Services" proposal begins now and runs through July 10, 2018.  The original review of "SDL 0167 - App Services" occurred May 2 - May 8, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/485

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by robinmk** [comment]
Due to the complex nature of the issue we are trying to solve, the proposal also seems complex. Some questions on it:

Section: Flows > App Service Provider > Defining the service - AppServiceManifest
Q. `serviceName` - Is there any recommendation on what should be used for `serviceName`? How will the system use this information?
Q. `serviceIcon` - What is the purpose of the `serviceIcon` parameter in the `AppServiceManifest` struct? Is it for the HU to indicate which app is providing the service (meaning it will be something which SDL Core or HMI will have to do) or is it something which the app that consumes the service can use as part of their user experience (eg: Sends a SHOW with that icon to show which app is fulfilling the current service)
Q. `serviceActive` - What is the purpose of the `serviceActive` parameter?
Q. `rpcSpecVersion` - Why is the `rpcSpecVersion` parameter required?


Section: Publishing the service - PublishAppService
Q. Is the expectation that the app would send a `PublishAppService` for every Service that it supports or should this `appServiceManifest` parameter be an array?

Section: Notifying potential consumers - OnAppServiceRecordUpdated
Q. The section and the previous flow has a mention of `OnAppServicePublished`. Is it meant to be `OnAppServiceRecordUpdated`?
Q. When should SDL Core send the `OnAppServiceRecordUpdated` notification to other apps? Is it as soon as SDL Core receives the `PublishAppService` request or when the particular service that is supported becomes active (We will need to also define when a service becomes active)?
Q. `updateResult` - Why is there a `updateResult` parameter within `OnAppServiceRecordUpdated`?
Q. `servicePublished` - What is the need for the `servicePublished` parameter within `OnAppServiceRecordUpdated` ? Is it to indicate if the service is available/no longer available?

Section: App Service Consumer
Q. Since the service consumer uses the 'GetSystemCapability' RPC to know what services are supported, I would suggest renaming `OnAppServiceRecordUpdated` to `OnSystemCapabilityChange` and keep it expandable.

Section: GetAppServiceData
Q. If multiple apps support the same type of service (eg: 2 Mobile nav apps supporting 'Navigation' service), will the system publish that both services are supported?
Q. If yes, How should module handle the response for `GetAppServiceData` request ?

Section: App Service Actions - PerformAppServiceInteraction
Q. "The URI prefix and actions list will be contained in the app service provider's manifest." -  Can you provide an example?
Q. "If the app service consumer currently has an HMI state of HMI_FULL this request can be performed without user interaction. If the app is currently not in that state, the HMI should present the user with a choice to allow this app service provider to become the active service of its specified type." - Irrespective of the HMI state of the consumer app, changing of service provider must always be approved by user.

Q. PerformAppServiceInteraction - Why is AppServiceID required ?

"If multiple app service providers of the same type register and the user has not previously selected an app service provider of that type, the first service to register will be activated by default" - In this case, user should be prompted for a service.
Q. Should this be part of resumption strategy?  - Core will need to remember the last service provider for a type of service.
Q. Shouldn't there be a mechanism for user to select the provider who fulfills a service?

It would be really helpful if the design can be explained from start to end using a use case like SendLocation to Mobile Nav. I also feel that each use case (Weather, Media, Voice Assistant etc) should be dealt with in their own use case.

**Comment by joeygrover** [comment]
I attempted to cover most cases in the proposal as it is complex, but while there are many moving pieces it shouldn't be overly difficult to understand/implement. 

Section: Flows > App Service Provider > Defining the service - AppServiceManifest
>Q. serviceName - Is there any recommendation on what should be used for serviceName? How will the system use this information?

A: This is essentially the app name, but can be more specific if we were to enable an app to offer more than one service

>Q. serviceIcon - What is the purpose of the serviceIcon parameter in the AppServiceManifest struct? Is it for the HU to indicate which app is providing the service (meaning it will be something which SDL Core or HMI will have to do) or is it something which the app that consumes the service can use as part of their user experience (eg: Sends a SHOW with that icon to show which app is fulfilling the current service)

A: The icon could be used for any of those scenarios. In the case of a the Beam POC it could have been used to display what service was running, or used while giving the user the option to select a service provider. 

>Q. serviceActive - What is the purpose of the serviceActive parameter?

It means that service is the active service of that type. All other apps are available, but since only one service per type can be active at a time this is the flag for that.

> Q. rpcSpecVersion - Why is the rpcSpecVersion parameter required?

App consumers might have a newer spec than core and per the [Unknown params](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#unknown-rpc-params) section Core should pass all params regardless of its RPC spec version.


Section: Publishing the service - PublishAppService
>Q. Is the expectation that the app would send a PublishAppService for every Service that it supports or should this appServiceManifest parameter be an array?

I think the typical use case will be a single service per app so an array doesn't make sense. It will also be easier to respond to publish requests if they are denied for any reason. 

Section: Notifying potential consumers - OnAppServiceRecordUpdated

>Q. The section and the previous flow has a mention of OnAppServicePublished. Is it meant to be OnAppServiceRecordUpdated?

Yes this was a typo. The scope of the notification changed so its name did.

>Q. When should SDL Core send the OnAppServiceRecordUpdated notification to other apps? Is it as soon as SDL Core receives the PublishAppService request or when the particular service that is supported becomes active (We will need to also define when a service becomes active)?

A notification should be sent when ever the record is updated. This includes when a service goes from not-active to active. 

>Q. updateResult - Why is there a updateResult parameter within OnAppServiceRecordUpdated?

[Per Service Removal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#notifying-provider-of-removal). Essentially it is a result of why the service would be removed. 

We can change this to a more specific notification to get sent to the service provider specifically though. 

>Q. servicePublished - What is the need for the servicePublished parameter within OnAppServiceRecordUpdated ? Is it to indicate if the service is available/no longer available?

Yes. 


Section: App Service Consumer
>Q. Since the service consumer uses the 'GetSystemCapability' RPC to know what services are supported, I would suggest renaming OnAppServiceRecordUpdated to OnSystemCapabilityChange and keep it expandable.

We have already accepted the [`OnRCStatus` proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0106-remote-control-onRcStatus-notification.md)  for this exactly functionality but specific to RC therefore I was following this flow. Creating a seperate flow now would create fragmentation. 


Section: GetAppServiceData
>Q. If multiple apps support the same type of service (eg: 2 Mobile nav apps supporting 'Navigation' service), will the system publish that both services are supported?

Yes. Both services are published but only one can be active.

>Q. If yes, How should module handle the response for GetAppServiceData request ?

It should only return the data from the active service.

Section: App Service Actions - PerformAppServiceInteraction
>Q. "The URI prefix and actions list will be contained in the app service provider's manifest." - Can you provide an example?

scheme: LivioMusic
actions: play, search 

URI: LivioMusic://play/artist=CoolGuy&song=AwesomeSong


>Q. "If the app service consumer currently has an HMI state of HMI_FULL this request can be performed without user interaction. If the app is currently not in that state, the HMI should present the user with a choice to allow this app service provider to become the active service of its specified type." - Irrespective of the HMI state of the consumer app, changing of service provider must always be approved by user.

The assumption is that the user has already interacted with the system to perform this request. For example, hitting a soft button that stated "Launch 'X Music'". I believe this could be up to the OEM to decide. 

>Q. PerformAppServiceInteraction - Why is AppServiceID required ?

It will be faster than looking up the URI scheme prefix from the supplied full URI string.

>"If multiple app service providers of the same type register and the user has not previously selected an app service provider of that type, the first service to register will be activated by default" - In this case, user should be prompted for a service.
Q. Should this be part of resumption strategy? - Core will need to remember the last service provider for a type of service.

Yes. Once a service is moved to active it should become the default service to use for that service type.

> Q. Shouldn't there be a mechanism for user to select the provider who fulfills a service?

Yes. But that would be an HMI feature and out of the scope of this proposal. The OEM can decide how they want to present that to the user. 

>It would be really helpful if the design can be explained from start to end using a use case like SendLocation to Mobile Nav. 

There isn't much more beyond what exists but the basics would be:
1. App publisher registers [See here](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#app-service-provider)
2. Core activates this service (Either through user interaction or as the default service [per this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#activating-service-providers) ).
3. Another app sends a `SendLocation` request
4. Core recognizes this RPC Function ID is to be handled by an app service, forwards the packet to the app publisher. (As far as timeouts I believe the correlation id should be removed from the current "waiting for response" list and put into a new list for forwarded RPCs that has a longer timeout)
5. App publisher receives request, performs correct action (ie offers to start a nav session with the supplied location)
6. App publisher sends a `SendLocation` response
7. Core receives response, forwards to originally requesting app

>I also feel that each use case (Weather, Media, Voice Assistant etc) should be dealt with in their own use case.

I'm open to taking extra time to review the service types. However, I fear if we nitpick every service type this feature will not be completed in a timely fashion.

**Comment by JackLivio** [comment]
> Activating Service Providers

This section defines HMI behavior that will definitely require some HMI API RPC changes/additions.

> 2. If multiple app service providers of the same type register and the user has not previously selected an app service provider of that type, the first service to register will be activated by default.

This might require a HMI RPC to define a default service provider via user input.

> 3. When an app service provider is changed to be the "Activated" service of that type, the user should be notified.

This might require a HMI RPC to notify the user a service has been activated. 

> 4. The user should have the ability to select default service types through the IVI system based on records of app services that have connected. All selection screens must adhere to driver distraction guidelines per the region in which it is used.

This might require a HMI RPC to define a default service provider via user input. (Same as #2)

> 6. If an app service consumer wishes to activate a different app service provider than the currently selected app service provider, the HMI must present the user with a notification/choice to allow the new app service provider over the previously selected one.

This might require a HMI RPC to prompt the user about the service change request and ask for user input.

**Comment by AndrewRMitchell** [comment]
Since we are calling out a few flows separately, and Navigation is one of them, it would be nice to have an addStop (or addWaypoint, or whatever you want to call it). With the current API that is called out we have the ability to set a destination for Navigation, and the ability to see the waypoints, but no way to set the waypoints, or more specifically add a destination (gas station, restroom, food, or some other stop). Insert waypoint at position X would be even better for some use cases (I want to get off the highway, get gas, then get something to eat), but may complicate things too much. If I missed something and this is possible with just SendLocation (ie, I missed a parameter like addToExistingIfExists), then I apologize.

I love the addition, despite its huge size, and while I'm normally one for breaking things up, I can see a lot of work has gone into document that we have already. I also feel this is one that will delight the customer, so I'm a little more willing to take the we'll fix things with future proposals.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review.  As the author will not be able to attend the Steering Committee meeting on 2018-05-15, this will likely remain in review until at least 2018-05-22.

During the discussion of this issue, it was clarified that app services will be provided to the IVI system as well as other connected apps, and some use cases include allowing the IVI system to leverage an offboard voice assistant that it doesn’t have installed itself, a mobile navigation app having `sendLocation` requests sent to it, or weather services information being displayed in other places beyond basic SDL templates.  The author will consider adding diagrams of some of these use cases.  During discussion, it was also clarified that this would be added to the base RPC spec (Mobile_API.xml) as an app would register on the head unit, and then policies would handle whether or not apps would be allowed to publish services on the IVI system.  Lastly, it was confirmed that it would be up to the navigation system when it receives `sendLocation` to know whether there is a destination already set and, if so, provide the option to the user to add a location as a waypoint or set it as a new destination.

Lastly, it was discussed that the basic flow/overall structure of this feature has been generally agreed to by the SDLC, and that subsequent reviews should be focusing more closely on app service types specifically.  This should include service specific RPCs and what data is most important for these services to provide.

**Comment by joeljfischer** [comment]
I apologize that I was not here for the previous review, so here are my holistic thoughts and notes:

1. Perhaps it's too late for this, but [x-callback-url](http://x-callback-url.com) might be a good standard to build upon. It says "iOS interapp communication", but seems that it may work for this use case as well. Essentially it just defines the following URL structure: `[scheme]://[host]/[action]?[x-callback parameters]&[action parameters]`. `x-callback parameters` are used for the receiver app to know how to respond, and might have sdl-specific definitions for our use case (since SDL is our router and knows the target app). Or, we may want to take some ideas from it.

2. The `MediaServiceData` may want to include something like what type of media is playing (e.g. music, podcast, audiobook), perhaps an enum value.

3. Additional `WeatherServiceData`:
  a. I think the various structs should look like this:

```xml
<struct name="WeatherServiceManifest">
    <param name="currentForecastSupported" type="Boolean" mandatory="false"/>
    <param name="maxMultidayForecastAmount" type="Integer" mandatory="false"/>
    <param name="maxHourlyForecastAmount" type="Integer" mandatory="false"/>
    <param name="maxMinutelyForecastAmount" type="Integer" mandatory="false"/>
    <param name="weatherForLocationSupported" type="Boolean" mandatory="false"/>
</struct>

<struct name="WeatherServiceData">
    <description> This data is related to what a weather service would provide</description>
    <param name="location" type="LocationDetails" mandatory="true"/>
    <param name="currentForecast" type="WeatherData" mandatory="false"/>
    <param name="minuteForecast" type="WeatherData" array="true" minSize="15" maxSize="60" mandatory="false" />
    <param name="hourlyForecast" type="WeatherData" array="true" minsize="1" maxSize="96" mandatory="false" />
    <param name="multidayForecast" type="WeatherData" array="true" minsize="1" maxSize="30" mandatory="false" />
    <param name="alerts" type="WeatherAlert" array="true" minsize="1" maxSize="10" mandatory="false" />
        <description> This array should be ordered with the first object being the current day</description>
    </param>
</struct>

<struct name="WeatherData">
    <param name="currentTemperature" type="Temperature" mandatory="false"/>
    <param name="temperatureHigh" type="Temperature" mandatory="false"/>
    <param name="temperatureLow" type="Temperature" mandatory="false"/>
    <param name="apparentTemperature" type="Temperature" mandatory="false"/>
    <param name="apparentTemperatureHigh" type="Temperature" mandatory="false"/>
    <param name="apparentTemperatureLow" type="Temperature" mandatory="false"/>
    
    <param name="weatherSummary" type="String" mandatory="false"/>
    <param name="time" type="DateTime" mandatory="false"/>
    <param name="humidity" type="String" mandatory="false"/>
    <param name="cloudCover" type="Float" mandatory="false"/>
    <param name="moonPhase" type="Float" mandatory="false"/>

    <param name="windBearing" type="Integer" mandatory="false"/> <!-- In degrees, true north at 0 degrees -->
    <param name="windGust" type="Float" mandatory="false"/> <!-- km/hr -->
    <param name="windSpeed" type="Float" mandatory="false"/> <!-- km/hr -->

    <param name="nearestStormBearing" type="Integer" mandatory="false"/>
    <param name="nearestStormDistance" type="Integer" mandatory="false"/> <!-- In km -->
    <param name="precipAccumulation" type="Float" mandatory="false"/>
    <param name="precipIntensity" type="Float" mandatory="false"/> <!-- cm of water per hour -->
    <param name="precipProbability" type="Float" mandatory="false"/> <!-- 0 to 1, percentage chance -->
    <param name="precipType" type="String" mandatory="false"/>
    <param name="visibility" type="Float" mandatory="false"/> <!-- In km -->

    <param name="weatherIconImageName" type="String" mandatory="false"/>
</struct>

<struct name="WeatherAlert">
    <param name="title" type="String" mandatory="false"/>
    <param name="summary" type="String" mandatory="false"/>
    <param name="expires" type="DateTime" mandatory="false"/>
    <param name="regions" type="String" array="true" minSize="1" maxSize="99" mandatory="false"/>
    <param name="severity" type="String" mandatory="false"/>
    <param name="timeIssued" type="DateTime" mandatory="false"/>
</struct>
```

4. It does not appear to be possible to see the name of the app that provided the `onAppServiceData` notification or `GetAppServiceDataResponse`, perhaps the `AppServiceData` struct should include the `serviceName`? Otherwise devs will have to track and correlate the Id.

5. Are there any security implications with `GetFile`?

6. The `serviceURI` of `PerformAppServiceInteraction` seems out of sync with the `AppServiceManifest` definitions. The sender must assemble the full service URI itself, but the manifest only provides a prefix and the actions. Are we assuming that the developer will publish full URI schemas? In your example in the comments above, the "artist" and "song" are unpublished by the manifest, so just "play" would be virtually unusable. If that's the case, I think we can remove `appActions` from the list and require developers to publish their entire schema themselves.

**Comment by theresalech** [comment]
The Steering Committee has voted to defer this proposal, keeping it in review until our next meeting on 2018-05-22, to allow for more time for Steering Committee representatives to comment on app service types and for the author to respond to comments.

**Comment by theresalech** [comment]
The Steering Committee has voted to defer this proposal, keeping it in review until our next meeting on 2018-05-29, to allow for a more in depth discussion of the proposal to take place in a workshop setting.

**Comment by theresalech** [comment]
Workshop Outcome: attendees identified gaps within the proposal as it stands, and the author will work to update the PR to fill in those gaps.  Once changes are made to the proposal regarding the architecture of the feature, each of the service types (VR, Navigation, Media, etc.) will be reviewed individually - for 1 week at a time - instead of all at once, to allow for deeper and more specific discussion about each service type.

**Comment by theresalech** [comment]
This proposal has been revised to reflect the decisions made during the workshop and is now ready for review.  The revised proposal will be voted on during the 2018-07-10 Steering Committee meeting.

**Comment by joeljfischer** [comment]
I think this is a very good proposal. I have a few small comments on the main section, but I agree with the proposal that app service types should be defined and discussed individually.

* `GetFile` should have a `CRC` so that we know it's done correctly. Additionally, I assume the `response`'s `bulkData` contain the file data? Will we receive multiple responses?
* An additional Core ini option could be `supportedServices` in addition to `embeddedServices`. Can there be a supported service without an embedded service (e.g. VOIP)?

**Comment by joeygrover** [comment]
- Agreed. I copied `PutFile` from the last release of the RPC spec, but the CRC param is being added to the next one so it should be included into `GetFile` as well.
- I was on the fence about this. I want to say no because I believe Core should support all services, but it is true that it doesn't have the ability to in some cases. So I think I agree that we can add it and by default keep all services as supported.

**Comment by robinmk** [comment]
Overall, I agree with this proposal.
Noting a few comments:
 1)
>param name="allowAppConsumers" type="Boolean" mandatory="false"
   <description>If true, app service consumers beyond the IVI system will be able to access this service. If false, only the IVI system will be able consume the service. If not provided, it is assumed to be false. 

Suggest using the `defValue` field for indicating default value:
param name="allowAppConsumers" type="Boolean" defvalue="false" mandatory="false"

2) Suggest renaming the param `appServiceUpdated` to 'updatedAppServiceRecord'

3) Is there a need for the `FileType` parameter in the `GetFile` request if the `fileName` is mandatory?
4) It probably makes sense for the `GetFile` response to have a `FileType` parameter (non-mandatory) so that the requesting app can be informed about the type of file.

5) If a particular `ServiceType` is not active, can a consumer successfully subscribe to it?

**Comment by joeygrover** [comment]
1. I always figured if a nonmandatory boolean param was not included the `defValue` would be false, but for clarity I'm fine with adding that. 
2. I don't have a strong opinion either way so I change it to `updatedAppServiceRecord`
3. I believe it would help the system identify if the file exists or not as it might be possible to have a file of a certain name but it is the incorrect type. I don't have a strong opinion here either though. 
4. Agreed.
5. I would say no. Based on other rules in the proposal if a single service of a service type existed it should become active by default, therefore, if there are no active services for a service type then that would mean no services of that type have actually been published.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions, pending individual service reviews.  Separate evolution issues will be raised for each of the services in the upcoming weeks, with 1 service being reviewed per week.  The revisions to this proposal are outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/485#issuecomment-403591277) and [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/485#issuecomment-403906723).

**Comment by theresalech** [comment]
@joeygrover please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Revisions have been incorporated into the proposal file and issues have been entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/2343)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1023)
[Android](https://github.com/smartdevicelink/sdl_android/issues/810)

**Comment by jordynmackool** [comment]
The below PR revisions have been accepted and implemented: 

https://github.com/smartdevicelink/sdl_evolution/pull/679
https://github.com/smartdevicelink/sdl_evolution/pull/673
https://github.com/smartdevicelink/sdl_evolution/pull/671
