### ISSUE TITLE
[Accepted] SDL 0176 - High level interface: Views and Controllers

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#511]
Hello SDL community,

The review of the revised proposal "SDL 0176 - High level interface: Views and Controllers" begins now and runs through June 26, 2018.  The original review of "SDL 0176 - High level interface: Views and Controllers" occurred June 6 through June 12, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0176-high-level-interface-views-and-controllers.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/511

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I have some notes:

### View Controller Lifecycle
* The subclassed methods in `View Controller Lifecycle` *must* call `super`. One way we could get around this is to make these delegate methods instead of overrides (see below "iOS 12 CarPlay Notes").

### SDLViewController
* The base view controller can't be implemented
* *Either* the `layout` *or* `customLayout` must be implemented
* This should include coloring information [SDL-0147](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0147-template-color-scheme.md).
* I would prefer to see, instead of separate views, a single stack, with the developer being able to use `setRootViewController:` instead of using `basic` with `pushViewController`, as it seems that would just replace the root? This seems kind of confusing.
* I'm assuming you're ignoring modal view methods for the time being, so I will as well.

### Views
* It appears that you're primarily using properties here, and don't have any methods. Is that intentional?
* `SDLView` should probably, for example, have an `addSubview:` method.

### SDLButtonView
* `SDLSoftButtonWrapper` should be `SDLSoftButtonObject`.
* Alternatively, we could map some of these things into `SDLSoftButtonObject` directly, as this name is much better.

### iOS 12 CarPlay Notes
* Yesterday, Apple released a session of [WWDC 2018: Session 213 - CarPlay Audio and Navigation Apps](https://developer.apple.com/videos/play/wwdc2018/213/). This has bearing upon us because Apple opened up APIs for "template-based" applications in these categories.

* Navigation apps have access to [`CPApplicationDelegate`](https://developer.apple.com/documentation/carplay/cpapplicationdelegate) with  required `connect` and `disconnect` methods that pass them the [`CPInterfaceController`](https://developer.apple.com/documentation/carplay/cpinterfacecontroller), an equivalent to `SDLViewControllerManager` (though their naming is perhaps better) as well as two optional navigation-specific callbacks.
* [`CPInterfaceManager`](https://developer.apple.com/documentation/carplay/cpinterfacecontroller) has a [delegate](https://developer.apple.com/documentation/carplay/cpinterfacecontrollerdelegate) with `templateWillAppear / Disappear` / `templateDidAppear / Disappear` methods. It has many of the same methods and properties as you do with `SDLViewControllerManager`, though `SDLViewController`s are `CPTemplate`s in their parlance, and they have a few additional methods: `popToTemplate:` and `popToRootTemplate`.
* Navigation apps (the only ones with raw access to templates besides OEM apps) have access to [several templates](https://developer.apple.com/documentation/carplay/templates).
    * Since we are not yet talking about navigation apps, I will ignore `CPMapTemplate` and additional CarPlay navigation-specific classes, but they can be [found here](https://developer.apple.com/documentation/carplay).
    * Likewise, I will ignore [`MPPlayableContentManager`](https://developer.apple.com/documentation/mediaplayer/mpplayablecontentmanager), [`MPNowPlayingInfo`](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter), and [MPRemoteCommandCenter](https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter), as these are specific to media apps. For more information on these apps, check out [these slides](https://devstreaming-cdn.apple.com/videos/wwdc/2017/719d0c0vj588o/719/719_enabling_your_app_for_carplay.pdf) from Session 719 of WWDC 2017
    * Interesting notes on the rest: Apple prefers **specific** pre-made subclasses the developer can instantiate to developer created subclasses, which we are building in this proposal; though, it should be noted, they have 5 templates compared to the 20+ pre-made templates we have. Our templates also have significantly more variability than the Apple ones do, indeed, they don't even have "floating" text and images, but only menus and maps.

**Comment by joeljfischer** [comment]
### View Controller Lifecycle

As I've thought about it more, I see two possible options. Either (1) we go with the above, which is slightly different from UIKit but is the direction Apple went with CarPlay and would be nicer because devs don't have to think about `super`. (2) We devise a way to know if they don't call super, and throw an exception.

I *think* I lean towards (1), but am open to both arguments.

### SDLViewController
Ah, I'm silly. They would just set the views and properties after initialization instead of in `viewDidLoad`, etc., using `DEFAULT` layout makes sense, or `MEDIA` if they're a media app.

Yes, `SDLConfiguration` would cover that info for RAIR, but I think we can also just pull it off the `rootViewController` set at launch (and should). This would be slightly confusing, as there are two different ways of setting it, and one, if set, overrides the other. The rest of those would be for the SetDisplayLayout.

`setRootViewController` would replace the first in the array, but it would also clear the rest of the array. It could also just be a property, like `UIWindow`.

> If the window has an existing view hierarchy, the old views are removed before the new ones are installed. [UIWindow.rootViewController](https://developer.apple.com/documentation/uikit/uiwindow/1621581-rootviewcontroller)

### SDLButtonView
I'm just thinking that instead of every time doing `SDLButtonView.button.whatever`, it might be nicer to do `SDLButtonView.whatever`.

### CarPlay
I agree with what you're saying. I think that as far as nav & audio apps go, we should try to make it easier and mimic their APIs if we can. Nav is already fairly close, it would involve making higher level TBT APIs mostly. I'm wondering if there's anything we can do to make audio better for SDL, like a signal from the app that they want to play audio, then the head unit just switches sources for a moment? For audio, we have some work to do though.

**Comment by kshala-ford** [comment]
### View Controller Lifecycle

I prefer the delegate. If the app developer tries to call super Xcode will raise an error message during compile time.

### SDLViewController

@joeljfischer thank you for the input. The appear methods should also be added here. The app developer can decide what fits best for the use case. In my view the manager mode is actually not needed anymore. See below

```objc
@interface SDLViewController
:
// if the view controller is contained in a view controller manager's stack this property 
// can be used as a shortcut
@property (nonatomic, weak) SDLViewControllerManager *manager;
@end

@protocol SDLViewControllerManagerDelegate
@optional
- (void)viewControllerWillAppear:(SDLViewController *)viewController;
// etc.
@end

@interface SDLViewControllerManager

@property (nonatomic, weak) id<SDLViewControllerManagerDelegate> delegate;

@property (nonatomic, copy) NSArray<SDLViewController *> *viewControllers;

@property (nonatomic) SDLViewController *rootViewController;
@property (nonatomic) SDLViewController *topViewController;

// sets and presents the root view controller satrting a new stack
- (void)setRootViewController:(SDLViewController *)rootViewController;

// Pushes a new view controller to the stack and presents it
- (void)pushViewController:(SDLViewController *)viewController;
// pops the top view controller from the stack and presents to underlying view controller
- (void)popViewController;
// pops all view controllers from the stack and presents the root view controller
- (void)popToRootViewController;
// pops all view controllers on top of the specified view controller and presents it
- (void)popToViewController:(SDLViewController *)viewController;

@end
```

The view controller should not have the `showViewController` method but point to the manager in charge. That would allow an easy access to the current stack. Examples (assuming `self` is an SDLViewController object):

```objc
SDLViewController *nextVC = ...;
// push a new view controller on top of the current one
[self.manager pushViewController:nextVC];
// replace the stack 
[self.manager setRootViewController:nextVC];
```

### SDLButtonView

As agreed: Instead of an SDLSoftButtonObject property the view should bypass just as SDLApplication does with SDLManager:

```objc
@interface SDLButtonView
@property (copy, nonatomic, readonly) NSString *name; //bypass to .SDLSoftButtonObject.name
// etc.
@end
```

### Conclusion

I suggest to return for revisions  (or accept with revisions if the changes are clear) as the changes affect a big portion of the proposal.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions.  The needed revisions are included in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/511#issuecomment-396211115) and [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/511#issuecomment-396255119) from the author.

**Comment by theresalech** [comment]
The author has updated this proposal per the agreed upon revisions, and the revised proposal has now moved into review. The Steering Committee will vote on this revised proposal during the 2018-06-26 meeting.

**Comment by joeljfischer** [comment]
Just a minor note:

### SDLView
* Because `SDLTextView` and `SDLImageView` inherit from `SDLView`, they'll have a `subViews` property that I can't think of a function for. Perhaps `SDLTextView` and `SDLImageView` should not inherit from `SDLView`.

**Comment by kshala-ford** [comment]
@joeljfischer good point but that's a common case in pretty much any UI framework I worked with. Under the hood (private methods) the inheritance is beneficial to go through the view hierarchy requesting the views to update the screen.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal.  It was agreed that the method to request the views to update the screen, as mentioned in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/511#issuecomment-399321912) from the author, can be viewed as an implementation detail and will therefore be determined upon implementation.

**Comment by theresalech** [comment]
Issue has been entered: [[SDL 0176] High level interface: Views and Controllers](https://github.com/smartdevicelink/sdl_ios/issues/1005)
