### ISSUE TITLE
[Accepted] SDL 0183 - Automatic Mobile Resumption Hash Management

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#533]
Hello SDL community,

The review of the revised proposal "SDL 0183 - Automatic Mobile Resumption Hash Management" begins now and runs through July 24, 2018.  The original review of "SDL 0183 - Automatic Mobile Resumption Hash Management" took place June 27 - July 10, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0183-mobile-hash-managment.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/533

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
The idea here is good, but I think the developer facing aspect is a little odd. Essentially there are two flows that are defined, 1. fresh start and 2. resumption. The developer will have to check to see if the resumption was successful before trying to set all of their components again or the managers would have to prevent the attempt to send them. The overhaul some apps would have to make could be troubling as it could potentially require a decent amount of refactoring that some developers might see as not worth the effort. 

In order to prevent that I believe there should be a setting to enable/disable resumption. By default I believe it would have to be false. Otherwise some apps are not going to work correctly if they don't include the new delegate and properly hook it to their existing blocks.  

You mentioned in your alternatives a way to enable the developer to set "new" blocks during resumption. I believe we should strive to a create a way the managers can detect potentially resumed components and tie them with the objects developers create during fresh start. For example, if a developer adds a soft button the screen manager should check its attributes against what was known to be resumed and then tie that code block to the resumed object. Admittedly this is a much more complex system, but it greatly eases the burden placed onto the developers.

**Comment by joeljfischer** [comment]
After more thought, I agree with @joeygrover.

A configuration option to disable / enable hash resumption should be available. It should probably default to disabled for now (since that's closest to the current behavior). Perhaps once the bugs are ironed out and major version occurs it could be enabled by default. It would likely notify the developer of the resumption in the ready block or something similar.

When a developer attempts to set up their "fresh start" data, if it already exists, the code block will be tied to the existing data, and the rest of the request would be ignored. If the data does not match, the old data will be cleared and the new data sent. e.g. If the set of menu cells doesn't entirely match the set resumed, the previous set will be cleared and the new ones set.

The primary downsides are (1) that existing data, particularly, and perhaps only, choice sets may linger between cycles unused unless the developer manually scans through and deletes unneeded ones, and (2) that the system may be fairly complex.

**Comment by theresalech** [comment]
At the author's suggestion, the Steering Committee voted to return this proposal for revisions.  The proposal will be revised to incorporate the changes described in the first two comments on this review issue.

**Comment by theresalech** [comment]
The author has updated this proposal per the agreed upon revisions, and the revised proposal has now moved into review. The Steering Committee will vote on this revised proposal during the 2018-07-24 meeting.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues entered:
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1066)
[Android](https://github.com/smartdevicelink/sdl_android/issues/853)
