### ISSUE TITLE
[Returned For Revisions] SDL 0195 - Minimum Main and Secondary Font Size

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#588]
Hello SDL community,

The review of "SDL 0195 - Minimum Main and Secondary Font Size" begins now and runs through August 28, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0195-minimum-main-and-secondary-font-size.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/588

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm not sure that this proposal is necessary.

The motivation states:
> Today navigation app developers create a video stream using the screen resolution in pixel without knowing the screen size/pixel density. This can result into differnt [sic] font sizes on screens with the same size but different resolutions.

However, we already have a proposal [SDL-0179](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0179-pixel-density-and-scale.md) that mitigates that motivation. This proposal seems to want to mitigate the same issue as 0179, but doesn't say why this proposal is necessary given that we've already accepted 0179.

**Comment by kshala-ford** [comment]
With 0179 and pixel per inch (ppi) you know the actual size of UI elements on the screen. If you want an app to show text of a specific font size you need 0179.

Now as we know the screen details we still don't know the distance between the drivers eyes and the screen. Depending on the interior design the same screen may be more far away from the driver making text more difficult to read. This proposal is placed to solve these issues as we believe it makes more sense to provide this data directly by the head unit.

**Comment by MichaelCrimando** [comment]
@joeljfischer great questions!
We were going to do this proposal inside of [SDL-0179](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0179-pixel-density-and-scale.md) originally. The reason why we didn't is because we super needed the pixel density part of the proposal and didn't want anything slowing it down.

SDL-0179 tells apps the pixel density so that they can scale their UI to be the same size no matter the screen pixel density.

What this proposal does is allow the OEM to essentially say to an app "On our system, our HMI team designed our system to meet the NHTSA (or whatever) guidelines for font height. We know our screen is X distance away from the user.  We need your primary text to be 13pts tall and secondary text to be 11 pts tall"
+ That value can change per OEM and whatever guidelines they are following

Does that make sense?

**Comment by joeljfischer** [comment]
@kshala-ford @MichaelCrimando That makes sense, however, I think it's going to cause more issues than it solves. Most apps are not going to be set up to alter their UI in this way, which will lead to the question of whether an app *has to* implement these kinds of changes when the data is passed to them in order to be accepted, in which case the sheer amount of work to alter a UI to make something like this work when the app is not designed for it may discourage apps from even attempting it in the first place. Or, if they don't have to, then what is the point? Apps *should* be capable of updating their sizes based on accessibility concerns like iOS' `dynamic type`, but it's not always easy to do so, especially with a lot of custom UI like navigation apps often have.

I'm unsure if this proposal is necessary if it's just about the distance from the driver to the screen, but even if the proposal goes through, I'm unsure this is the way to go. First, there are certainly more than 2 font sizes in the app, so I think this proposal will cause confusion. Second, telling an app to use specific font sizes is probably not the way to go. Instead a "very small, small, normal, large, very large" scale might work better and providing an example font scale.

**Comment by MichaelCrimando** [comment]
Well I will say that as part of an OEM, the problem we have and are trying to solve are based on the NHTSA Phase 1 report on Driver Distraction gives minimum font requirements. 
https://www.nhtsa.gov/staticfiles/nti/distracted_driving/pdf/distracted_guidelines-FR_04232013.pdf
Which just recommends using [ISO 15008:2017](https://www.iso.org/standard/62784.html)

This is not to say that apps HAVE to use these 2 font sizes. They can go bigger. We're just creating an avenue for them to know what the minimum usable font size would be from the OEM side. From an app partner perspective, it may actually be helpful to know this information so that they can actually ensure that their app is readable from all systems - seeing that some screens may be further back from the driver than others.

**Comment by jordynmackool** [comment]
This proposal is being returned for revisions. The Steering Committee voted to return this proposal for revisions.  The revisions should include the author’s stance on how the SDLC should adhere to NHTSA guidelines. This was determined after the Steering Committee discussed the impact this proposal would have on navigation app developers, as specific targets for font sizes may make it difficult for app developers to build the UI (especially menus, footers, etc.) for their apps, and it was questioned whether this requirement would be mandatory for app developers.  It was clarified that the issue would not be that apps have a minimum font size, but rather that developers would have to build their apps in a dynamic way, which they may not be set up for or able to do.  Steering Committee representatives also spoke to the fact that many OEMs may consider NHTSA as mandatory, while those in other regions may not, and this will need to be taken into consideration when we determine the guidelines that should be given to app developers who want to join the SDL ecosystem.

**Comment by theresalech** [comment]
@MichaelCrimando @kshala-ford please advise if you will be able to take action on this proposal within the next two weeks.  If not, we will plan to close as inactive on 2019-05-08.  Thank you!

**Comment by theresalech** [comment]
Closing as inactive.
