### ISSUE TITLE
[Accepted with Revisions] SDL 0198 - Media Skip Indicators

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#596]
Hello SDL community,

The review of "SDL 0198 - Media Skip Indicators" begins now and runs through September 4, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0198-media-skip-indicators.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/596

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by robinmk** [comment]
I support the idea but have a few comments/questions:

1. Should the `seekTime` parameter be limited to 99 seconds?
2. Probably a typo but shouldn't the `type` for `forwardSeekIndicator` and `backSeekIndicator` be `SeekStreamingIndicator`?

3. > By default the seek indicators should be TRACK when: the media app was closed by the user (App enters HMI_NONE)

I think this is not required and the system can remember that the seek buttons should be of type `TIME` since this indicator seems more like a property (maybe we should consider it to be part of `SetGlobalProperties` instead) rather than a state (which is the likely the reason for the design of [SDL-0109](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0109-set-audio-streaming-indicator.md))

4. Minor issue with the formatting of the `seekTime` parameter.

**Comment by robinmk** [comment]
3. I guess it is not a big concern as it would be HMI design decision. However, app/proxy developers must be made aware to send the SeekIndicatorType whenever the app moves out of NONE.

Agree to other comments.

**Comment by jordynmackool** [comment]
The Steering Committee voted on 2018-04-18 to defer this proposal, keeping it in
review until our next meeting on 2018-09-18, to allow the author to respond to
the questions on the review issue.

**Comment by MazdaMKok** [comment]
@jordynmackool What exactly were the other questions that the author had to respond to, because it seems that @robinmk had his questions answered? robinmk did note that app/proxy developers must be made aware to send the SeekIndicatorType whenever the app moves out of NONE, but besides that, I don't see any other questions to be answered. Maybe there was something I missed....

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept this proposal with revisions on 2018-09-18. The revisions will incorporate the feedback agreed to [in this comment](https://github.com/smartdevicelink/sdl_evolution/issues/596#issuecomment-418749992) by the author, and will also make sure that conditions of `SeekIndicatorType` are documented, as requested [in this comment](https://github.com/smartdevicelink/sdl_evolution/issues/596#issuecomment-418755274).

**Comment by jordynmackool** [comment]
Proposal has been revised, and issues have been entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/2625)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1080)
[Android](https://github.com/smartdevicelink/sdl_android/issues/871)
[generic_hmi](https://github.com/smartdevicelink/generic_hmi/issues/113)
[sdl_hmi](https://github.com/smartdevicelink/sdl_hmi/issues/122)
[rpc_spec](https://github.com/smartdevicelink/rpc_spec/issues/127)

**Comment by theresalech** [comment]
JavaScript Suite issue: https://github.com/smartdevicelink/sdl_javascript_suite/issues/346
