### ISSUE TITLE
SDL 0209 - Static Icon Capability

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#636]
Hello SDL community,

The review of "SDL 0209 - Static Icon Capability" begins now and runs through December 11, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0209-static-icon-capability.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/636

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by kshala-ford** [comment]
I always thought this information is provided to the app... in fact it is included in the HMI_API already (see https://github.com/smartdevicelink/sdl_core/blob/5.0.0/src/components/interfaces/HMI_API.xml#L2776) Therefore the HMI part of this proposal is not required.

I would propose one of the following options:

### 1. Mobile API should match the HMI_API 

By adding the parameter `imageCapabilities` to `DisplayCapabilities` to the mobile API.

#### Mobile API changes

```xml
<struct name="DisplayCapabilities" since="1.0">
  :
  <param name="imageCapabilities" type="ImageType" array="true" mandatory="false" since="x.x" />
</struct>
```

This reduces the affected area to Core only. No HMI changes are required.

### 2. Add another bool

As proposed in the proposal add another bool just like `graphicSupported`. This bool is true if imageCapabilities array of HMI API contains STATIC, otherwise it's false. I'm not in favor of this thinking of possible other image types to support (like remote with url...).

### 3. Be more specific for each image field

There's another field called `imageFields` that specifies the capabilities per image field (graphic, button icon etc.). If we are more specific we could say that static icons are supported for button icons but not for graphics. Though it could be handy I believe it's far beyond the desired functionality and a pretty big change...


### Conclusion

My conclusion is to go with option 1

**Comment by joeljfischer** [comment]
I missed that part of the HMI_API when investigating this proposal. I agree that it should match. The only bad part about matching is that the `arraySize` of the HMI_API's `imageCapabilities` is only 2, which means that any later additions to capabilities done in this manner would need to expand that `arraySize` as well (Not a big deal for HMI, bigger deal for MOBILE). So I think a parameter like the following would be best:

```xml
<param name="imageCapabilities" type="ImageType" array="true" minsize="0" maxsize="999" mandatory="false">
```

**Comment by kshala-ford** [comment]
you're right the size constraints are not good. Alternatively you could just remove `minsize` and `maxsize`?

**Comment by JackLivio** [comment]
In the hmi api, "imageCapabilities" is only for saying which of the two types of images are supported "Static"/"Dynamic". This array size should be left at max 2 since there are only two image types defined in that enum.

I think the "imageField" parameter is the one you want to add to the mobile api. 

```
<struct name="ImageField">
  <param name="name" type="Common.ImageFieldName" mandatory="true">
    <description>The name that identifies the field. See ImageFieldName.</description>
  </param>
  <param name="imageTypeSupported" type="Common.FileType" maxsize="100" array="true" mandatory="false" minsize="1">
    <description>The image types that are supported in this field. See FileType.</description>
  </param>
  <param name="imageResolution" type="Common.ImageResolution" mandatory="false">
    <description>The image resolution of this field.</description>
  </param>
</struct>
```

**Comment by jordynmackool** [comment]
The Steering Committee voted to accepted this proposal with the revisions 2018-12-11. The author will alter his proposal to match his [last comment](https://github.com/smartdevicelink/sdl_evolution/issues/636#issuecomment-445936879) but with the array maximum size as 1000.

**Comment by jordynmackool** [comment]
The author has made the requested revisions and issues have been entered: 
[rpc_spec](https://github.com/smartdevicelink/rpc_spec/issues/142)
[generic_hmi](https://github.com/smartdevicelink/generic_hmi/issues/147)
[sdl_hmi](https://github.com/smartdevicelink/sdl_hmi/issues/173)
[sdl_core](https://github.com/smartdevicelink/sdl_core/issues/2790)
[sdl_ios](https://github.com/smartdevicelink/sdl_ios/issues/1140)
[sdl_android](https://github.com/smartdevicelink/sdl_android/issues/952)
