### ISSUE TITLE
[Deferred] SDL 0215 - iOS ReplayKit Streaming

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#661]
Hello SDL community,

The review of "SDL 0215 - iOS ReplayKit Streaming" begins now and runs through February 19, 2019. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0215-ios-replaykit-streaming.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/661

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

**Comment by BrettyWhite** [comment]
My biggest gripe with the current method is the fact the screen has to stay on while the app is in use. Does this API allow for the app to stream in the background or with the screen turned off? If not, I'm not sure the UX disadvantage of a permission pop up every time would be worth the trade off.

**Comment by SatbirTanda** [comment]
@NicoleYarroch Yes, there is an issue regarding screen sizes, it may be possible to scale to pixel data to fit the screen size width and height, but I have to double check.  I tested with iPhone 6s Plus and the output was too big for HU, and with iPhone 7 and the output a smaller for HU.  

@BrettyWhite The API does not allow the stream while app is in the background or with the lock screen up, its main benefit is reduction of CPU usage and increased battery life.  There is a screen recording widget in the control center that allows a system level screen capture that does record in the background and when locked - however its API is not exposed to the developer publicly.

**Comment by kshala-ford** [comment]
So far I read the following cons about this proposal:

1. It captures the whole phone screen. Size and aspect ratio won't fit the HU
2. The UX requires the user to approve of screen recording on the phone and every time
3. The phone still needs to be unlocked and app must be in foreground on the phone

I want to add:

4. We may not be able to use lock screens for the projection app. Otherwise ReplayKit captures the lock screen.
5. Question: Does the background string still work if the user accidently presses the home button or lock button?

The pro is:

1. It comes with way better performance

**Regarding 1.** One upside is that we may be able to benefit from retina screens by scaling down the capturing view. This will ensure we capture views if HU screen resolution is very big (HU.width > capturingView.width). In addition to that we might be able to use CoreImage framework to crop the sample buffer. See code below (not confirmed to work...)

```objc
// before start recording we should scale down the capturing view based on retina scale
carWindow.rootViewController.view.scale = 1.0 / UIScreen.mainScreen.scale;

[[RPScreenRecorder sharedRecorder] startCaptureWithHandler:^(CMSampleBufferRef  _Nonnull sampleBuffer, RPSampleBufferType bufferType, NSError * _Nullable error) {
    if (error) {
        SDLLogD(@"Video stream error %@", error.debugDescription);
        return;
    }
     
    CVPixelBufferRef pixelBuffer = CMSampleBufferGetImageBuffer(imageDataSampleBuffer);
    CFDictionaryRef attachments = CMCopyDictionaryOfAttachments(kCFAllocatorDefault, imageDataSampleBuffer, kCMAttachmentMode_ShouldPropagate);
    CIImage *ciImage = [[CIImage alloc] initWithCVPixelBuffer:pixelBuffer options:(NSDictionary *)attachments];
    CFRelease(attachments);

    CGRect capturingViewBounds = ... carWindow.rootViewController.view.bounds;
    CIImage *croppedImage = [ciImage imageByCroppingToRect:capturingViewBounds];
   
    [self.streamManager sendVideoData:croppedImage.pixelBuffer];
} completionHandler:^(NSError * _Nullable error) {
    if (error) {
        SDLLogD(@"Video stream error %@", error.debugDescription);
    }
}];
```

**Comment by SatbirTanda** [comment]
@kshala-ford When the lock screen appears it actually does not impede on the recording of stream (as I  saw in testing).  Also, yes the background string still appears because the logic behind the streaming state does not change - so when the app is backgrounded the framework handles showing the string appropriately.

**Comment by kshala-ford** [comment]
@SatbirTanda can you provide some more details regarding the lock screen? Is there any example app for testing? To my understanding RPScreenRecorder captures the key window of `UIScreen.mainScreen`. I'm just curious if we are missing something. I can remember there was the approach to remove the lock screen for a split second right before the screen is captured then show the lock screen again but it caused screen flickering.

**Comment by kshala-ford** [comment]
I want to provide some more feedback with regards to the upcoming steering commitee:

I suggest to return the proposal for revision. The revisions should be:
1. To evaluate and show functionality of the lock screen
2. Evaluate the provided code snippet to crop the captured view out of the pixel buffer
3. Evaluate if the app still needs to be landscaped (crop the view may eliminate this item)
3. Revise proposed solution to add `SDLCarWindowRenderingTypeReplayKit` and to have `syncFrame` according to this new rendering type

**Comment by SatbirTanda** [comment]
[SDL-ReplayKit-Example.zip](https://github.com/smartdevicelink/sdl_evolution/files/2784874/SDL-ReplayKit-Example.zip)

@kshala-ford Attached is an example app that has the changes to `SDLCarWindow.m`.  Here are some answers:
1.  If you run through the attached example (with encryption off on a HU), you will see that when you toggle the SPEED on a HU the lock screen will appear on the app but not on the stream.
2. I tried out the code snippet provided for resizing, but it looks like it did not change the pixel buffer (I did not debug deeply)
3.  The attached app is landscaped by default.  However, feel free to change it to Portrait only to see the result.  You will see that SDL force resizes the view controller and since ReplayKit does a full app screen capture it captures it exactly as so.  `Note:  With replay kit enabled, the developer will no longer need to continuously set the rootViewController of the stream.  Rather, they would only need to set it to UIApplication.shared.keyWindow?.rootViewController in the SDLStreamingMediaConfiguration once.`
4.  The attached app did not add `SDLCarWindowRenderingTypeReplayKit`, however, it should be trivial to do so in actual implementation.

**Comment by joeljfischer** [comment]
I have reviewed this possibility in the past, and I agree that working past some of the issues would solve a lot of our CPU usage issues. However, some issues I can see with this proposal as written:

1. The `proposedSolution` needs to note what will actually be changing with the public API, and not just suggest it in the `Impact on existing code` section.
2. The proposal notes: `The app would need to be forced in a horizontal orientation.` What does this mean? There is no API to force a window into an orientation at runtime that I'm aware of. The pixel sizing issue is a major one that this proposal provides little clarity on. How exactly does screen orientation work. How is an app locked into horizontal orientation. What happens if it's misconfigured? Is the window resized based on the head unit screen available size? If not, is the view distorted on the head unit? Is it sized to fit? Sized to fill? The example app provided, when in portrait orientation, takes a "size to fill" approach that leaves the app unusably stretched. Even in landscape, it's still stretched and the screen can appear upside down if in the wrong landscape orientation. These questions must all be answered by this proposal before the maintainer can support a vote on it.
3. `Tests would need to be done with iPhone XS, X, XS Max, XR - when testing these phones, there has been notable crashes.` I think this is a major blocker for accepting this proposal.
4. `It has been determined the replay kit stream also contains audio data that can be used to stream audio to the Head Unit exactly like a media app. This would mean the developer would no longer need to send PCM audio files to SDL (they can play audio as they would in their app and it should carry over).` What does this mean? Because a navigation app can _already_ stream audio like a media app. That's not what we want. Do you mean that we can make additions to the proxy library to change that audio data into PCM data automatically?
5. The recording prompt is an unfortunately large issue. If the user wants to use navigation while in their car, it means that they _must_ interact with their phone. While that is true for many older head units because the user must open the app on their phone, that is being mitigated in newer head units to the best of my knowledge, and we at least provide a prompt to do so.
6. Even with an iPhone 8, the example app provided faced a number of failures in which the app displayed a black screen until the app was uninstalled and reinstalled.

**Comment by kshala-ford** [comment]
@joeljfischer thanks for looking into this. I'm not the author of this proposal but let me try to add some notes in hope it brings us forward in understanding the impact of ReplayKit.

Reg 2. I believe the landscape requirement is not needed. I found a way to crop sample buffers and return pixel buffers. https://gist.github.com/kshala-ford/5f10b8be912439da6e1d05bd489e1924 It's very immature code but it shows that ReplayKit can capture the screen while the method crops the captured buffer to the frame of the view we are targeting.
Reg. 3. and 6. you're absolutely right. In order to evaluate the performance increase we should compare ReplayKit mode vs. all other capturing modes from CarWindow.
Reg. 4. I think this is an optional feature we could take advantage from after we understood how ReplayKit can be used for video. I think it helps all of us to focus on video first.
Reg. 5. This is the important question of all questions. 

Do we as the SDLC agree to this hard requirement of having this prompt facing users if a developer chooses `CarWindow` to work in `ReplayKit` mode? In this case we should return for revisions and work all together to provide answers to all the questions and better understand how ReplayKit works. As soon as we have finished working on ReplayKit and understand all we can return the proposal for acceptance.

Or do we disagree and not add `ReplayKit` mode at all? In this case we should reject the proposal so that we don't waste our time in answering all questions.

My personal preference is to use ReplayKit but we definitely need to work further to understand it.

**Comment by joeljfischer** [comment]
2. Do you mean that the window could be resized? Or that the existing window in portrait could be cropped? If so, then the window being streamed would have to be, for example, only as wide as the device in portrait, right? If so, then on an iPhone SE, the width would be max 640 px, which is quite small, and it would be different for many head units with different aspect ratios.

I think we definitely need more discussion on all of these issues, with (in order) the prompt, crashes, failures, cropping / stream resolution being the most important issues. I'm not entirely against using ReplayKit, but I think the prompt is a significant issue that severely limits us, the crashes and failures is a big concern to me, and the resolution is a significant hurdle. 

I agree with you that the prompt is the first issue to be discussed, because if the business case isn't there, then the proposal should be rejected. Then, if the crashes / failures can't be solved, then the proposal should be rejected. Finally, if the resolution issues can't be solved, the proposal should be rejected. First, we should discuss the business case, then the author can move on to proving the crash / failure and resolution issues.

**Comment by jordynmackool** [comment]
The Steering Committee voted to keep this proposal in review. Prior to moving forward with this proposal, SDLC members need to determine if having the hard requirement of having a prompt facing users if a developer chooses `CarWindow` to work in `ReplayKit` mode is an acceptable user experience. It was requested that members provide their feedback on this issue. 
If members disagree with this user experience then there will be no need to investigate the outstanding questions. If this is an acceptable user experience, the author will need test/identify a solution for the multiple crashes that are noted in the proposal and called out in point three in [this comment.](https://github.com/smartdevicelink/sdl_evolution/issues/661#issuecomment-464848077)   Additionally, if the prompt is acceptable a solution needs to be identified for making sure we can resize the window that is streaming to whatever resolution and aspect ratio that is necessary and with an acceptable quality. It was noted that the iOS Replaykit would be an additional option to what currently exists for app developers, so if they did not want to use the iOS Replaykit with the prompt they would not have to and they could choose one of the existing options.

**Comment by jordynmackool** [comment]
The Steering Committee voted to keep this proposal in review. Prior to moving forward with this proposal, OEM SDLC members need to decide if it is an acceptable user experience to make the user select a prompt on the phone before video streaming apps will work on the head unit. OEMs should consult their user experience team and/or their driver distraction lawyers to see if this user experience is acceptable. It was requested that the other OEM SDLC members provide their feedback on this issue. Ford was the only OEM who noted that this was an acceptable user experience.

The PM noted that if this was accepted, in the wild an OEM would not be able to deny an app to do this unless they created a special case policy where they are denying the app entirely. If accepted the prompt will appear on devices. 

If this is determined to be an acceptable user experience, the author will need test/identify a solution for the multiple crashes that are noted in the proposal and called out in point three in [this comment.](https://github.com/smartdevicelink/sdl_evolution/issues/661#issuecomment-464848077) Additionally, if the prompt is acceptable a solution needs to be identified for making sure we can resize the window that is streaming to whatever resolution and aspect ratio that is necessary and with an acceptable quality.

**Comment by jordynmackool** [comment]
If any SDLC OEM Members have feedback in response to this request:

**"OEMs should consult their user experience team and/or their driver distraction lawyers to see if this user experience is acceptable. It was requested that the other OEM SDLC members provide their feedback on this issue. Ford was the only OEM who noted that this was an acceptable user experience."**

Please comment on this issue.

**Comment by jordynmackool** [comment]
The Steering Committee voted to defer this proposal. Subaru voiced that it is not an acceptable user experience to make the user select a prompt on the phone before video streaming apps will work on the head unit without an indication to the user on the head unit. Based on the driver distraction guidelines, Ford agreed that this would not be a good UX for drivers. Toyota additional stated that they are waiting to hear back from internal partners in regards to this being an acceptable user experience, but it is expected that they will have the same concerns Subaru.
The author will need to investigate if it is achievable to notify the user on the vehicle screen when the prompt is displayed on the device. If this is possible, the author is to add additional details to the proposal and resubmit for review.

**Comment by SatbirTanda** [comment]
Sure, it's certainly possible to send an SDLAlert RPC to notify the the end user to accept the prompt on their device.  Also, before streaming begins (before the accept button is tapped) the streaming state is considered to be in the background so we can also display a string to indicate to the user to tap the accept button.  Also, I'm not too familiar on programming for MFi devices such as SYNC as to whether of not the user can accept the prompt from the screen of the Head Unit.

**Comment by theresalech** [comment]
@SatbirTanda please advise if you will be able to take action on this proposal within the next two weeks.  If not, we will plan to close as inactive on 2019-05-08.  Thank you!

**Comment by theresalech** [comment]
Closing as inactive.  The issue will remain in a `deferred` status and unlocked so the author can notify the Project Maintainer when it is ready to be revisited.
