### ISSUE TITLE
SDL-0217 Android Manager Listener Update

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#665]
Hello SDL community,

The review of "SDL 0217 - Android ManagerListener Update" begins now and runs through January 29, 2019. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0217-android-manager-listener-update.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/665

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

**Comment by bilal-alsharifi** [comment]
Thanks, @kshala-ford  for submitting the proposal. I have some questions and comments about it:

> List<Language> supportedLanguages = this.languagesSupported;

Where is the supported languages list coming from? I couldn't find defined anywhere in the `SDlManager`


I also suggest adding `onHMIStatusChanged` instead of adding three different methods for `hmiLevel`, `audioStreamingState`, `systemContext` like 

```
void onHMIStatusChanged(@Nullable OnHMIStatus oldState, @NonNull OnHMIStatus newState);
```

Because `hmiLevel`, `audioStreamingState`, `systemContext` are already included in `OnHMIStatus`. This will make it also easier to maintain in case we add other variables to `OnHMIStatus` in the future

**Comment by joeygrover** [comment]
>However, as Java interfaces force you to implement every single method, it can be distracting.

I think this is very important when adding items to a mandatory interface for developers. One of our goals was to move away from this type of overloaded interface after we witnessed what happened with `IProxyALM` as it only grew and grew which made developer's integration code untenable. Since a developer can already listen for an `OnHmiStatus` notification which contains most of the information these three additional methods provide is there a real advantage to adding them? I believe @bilal-alsharifi is even better than what was proposed, but in my opinion the developer can already access the necessary information so adding specific APIs for it seems redundant.

I have not actually used this but Java 8 also added a `defualt` keyword for interface methods that looks as though would let you add filled out default methods that don't need custom implementation for every class implementing the interface. Like I said though, I haven't used it or looked too far into yet but it does seem like it is relevant here. https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html
 
####  onConfigurationUpdate and Updater

The `onConfigurationUpdate` method seems like it's supposed to be generic, however the only parameter that is supplied is a language. Is the idea that in the future more parameters could be added? Or will this always and only be called in the case of a language change?

The updater class is not a static class so it is different from the Builder class as an SdlManager instance must be created and used in order to create an instance of the updater. This class also seems redundant as it essentially is just a factory class for a `ChangeRegistration` RPC and its response. Also the updater itself changes the `SdlManager` data prior to actually knowing if the ChangeRegistration was successful which seems a little odd as it could create discrepancy between the module and the client app.

**Comment by kshala-ford** [comment]
#### HMI Status 

I don't think a listener of the whole `OnHMIStatus` notification solves the actual issue listening for HMI level change but filter out system context change. The notification `OnHMIStatus` was created for the sake of reducing the number of RPC notifications. I don't know how many times I saw app developers toggling audio streaming because the system context has changed (and not the audible state). We should always consider SDL newbies as the API users and we as the SDLC should be the one providing a convenient API and notify the app for each single parameter if it has changed. The question is how:

The current solution to add a generic RPC notification listener for `OnHMIStatus` is not self explaining and requires manual work. Having `onHMIStatusChanged` does not reduce the manual work to filter unchanged parameters. It's a trap for developers and we should avoid it.

The `default` keyword with Java 8 sounds promising but I'm afraid this might cause issues if the app developers have not yet updated to Android Studio 3 and `JavaVersion.VERSION_1_8`. I believe it's (still) too invasive enforcing the app to do this upgrade.

Please have a look at the alternative solution where developers can add listeners for each parameter in the `Builder` class. Pros:
1. It wouldn't create yet another `IProxyListener` bloat
2. The HMI level and other parameters are not hidden but available while building the app
3. The app developer can choose to add listeners only to the parameters important for the app lifecycle

#### Language mismatch

>> List supportedLanguages = this.languagesSupported;

> Where is the supported languages list coming from? I couldn't find defined anywhere in the SDlManager

I'm sorry I think I missed that part in the proposal. `SdlManager` needs to store not only (desired) `language` but also `languagesSupported` This includes `set` methods for the static `Builder` class.

```java
public class SdlManager {
  :
  private Language hmiLanguage;
  private Vector<Language> languagesSupported; // <- New
  :
  public static class Builder {
    :
   public Builder setLanuagesSupported(...) {...} // <- New
   :
 }
```

> The onConfigurationUpdate method seems like it's supposed to be generic, however the only parameter that is supplied is a language.

It's updating the manager with all settings that can be modified with `ChangeRegistration`. It follows the process that is already implemented for sdl_ios (see https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0054-change-registration-manager.md):
1. If language mismatch detected but supported languages contains IVI language then ask the app for configuration update
2. the app returns an update object with new localized app name TTS name etc.
3. If the app returns an update object then the sdlManager calls update()

**Comment by joeygrover** [comment]
>I don't think a listener of the whole OnHMIStatus notification solves the actual issue listening for HMI level change but filter out system context change.

The developers can easily perform this task. For example, it would be possible to store the last received hmi status in the listener itself and do a compare against the last received and the new one. Getting the individual updates will actually come in as a serial queue while it makes more sense to get the full hmi status at the same time. Otherwise, the developers still have to check other params from the RPC at the time when they receive each one of the updates through each of the callbacks. 

The individual callbacks appear to be an untenable nightmare of overly specific interfaces. It's essentially creating a callback for each param that is to be watched. Maybe there is a more elegant way to handle this scenario, but I don't believe creating an overburdened interface or micro interfaces are the way to go. 

>It's updating the manager with all settings that can be modified with ChangeRegistration. 
Understood, but the only time it is called is when there is a language change. So the method naming makes it seem generic, when really it's a very specific scenario. However, if that's how the iOS API already is then unfortunately Android would have to just match. 


These changes seem a bit unrelated so it makes the proposal itself and I would recommend separating such change requests into two seperate proposal. Essentially the second part is [0054] Change Registration Manager for Android.

**Comment by NicoleYarroch** [comment]
True, the code isn't that long, but to someone who is building their first app, it isn't very readable. Most developers assume that once the `SdlManagerListener` tells them that the manager has started everything is good to go when that isn't the case. Having them register for some notification on top of creating a `SdlManagerListener` and `Builder` objects isn't the most user friendly introduction to permissions.

**Comment by joeygrover** [comment]
I think you have to really understand the headache that is Java Interface requirements of implementing every method. If you look at pre-manage implementations the Android Service object had to implement it and it was a lot for a developer to be faced with right off the bat. Imagine the user having to implement all the methods found in this [interface]( https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java). There's no option to only implement what you need, they all have to be a part of your class. 

That's my biggest problem with this proposal, we are creating callbacks for parameter changes and that doesn't scale. We can create something smarter than that.

**Comment by NicoleYarroch** [comment]
I agree that forcing developers to implement methods that they aren't going to use isn't the way to go but I do think something should be done to make setup more friendly. The alternative solution seems like a much more viable option.

**Comment by jordynmackool** [comment]
The Steering Committee voted to reject this proposal on 2019-01-29 based on the amount of feedback given in the comments. The author plans to rework the proposal in a new format and resubmit the updated proposal for review.
