### ISSUE TITLE
SDL 0218 - Facilitating OEM Communication with App Developers

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#680]
Hello SDL community,

The review of "SDL 0218 - Facilitating OEM Communication with App Developers" begins now and runs through February 26, 2019. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0218-developer-oem-communication.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/680

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by joeljfischer** [comment]
1. Would this include OEM - OEM communication regarding non-code (e.g. Github) issues. For example, facilitating OEM communication regarding Apple iAP or Google issues? Is there a better forum for that which now exists outside of the weekly SDLC Steering Committee call?
2. How is a developer / OEM notified of new messages / updates? Should we use a github-style "watch"? e.g. Subscribe my email to a particular message / issue thread, or to all threads relating to my app developer / OEM.
  * Otherwise, how does an OEM know when a new message arrives? It seems that there's no notification system at all right now, which doesn't seem right.

**Comment by nickschwab** [comment]
@joeljfischer -

> 1. Would this include OEM - OEM communication regarding non-code (e.g. Github) issues. For example, facilitating OEM communication regarding Apple iAP or Google issues? Is there a better forum for that which now exists outside of the weekly SDLC Steering Committee call?

This proposal is intended for communication between OEMs and App Developers in the context of a specific application. Multiple OEMs can join in the discussion of shared application issues, but general communication between OEMs should be considered outside of the scope of this proposal.

> 2. How is a developer / OEM notified of new messages / updates? Should we use a github-style "watch"? e.g. Subscribe my email to a particular message / issue thread, or to all threads relating to my app developer / OEM.
> * Otherwise, how does an OEM know when a new message arrives? It seems that there's no notification system at all right now, which doesn't seem right.

Email notifications will be sent to the contact email address set by OEMs and App Developers on their Developer Portal account in the "Company Info" tab. Either entity may choose to enable or disable these email notifications through a new checkbox/toggle switch. In the future - if these communication channels are well-adopted by OEMs and App Developers - we can add more granular notification options.

**Comment by joeljfischer** [comment]
Regarding (1), I think that would probably be very helpful to have, like a general "Platform issues" issue board for Apple / Google / etc. issues that all OEMs could see. I understand that it's outside of the scope of this proposal, but it seems like a logical "v2" addition.

2. Sounds fine to me, though I would also advocate for some sort of notification icon / page for logged in members with unread chat / issues that takes them to their unread messages. I understand if that's also a "v2" issue.

**Comment by kshala-ford** [comment]
1. What's the negative allowance filter? I expect this filter to be better explained than in parenthesis. 
2. What are these general text-based messages about? I can understand messages to issues as comments but I don't understand general messages. My understanding is this means text messages in some kind of a bulletin board with threads for each app. Or multiple threads can be created per app?
3. What are granted OEMs? 
4. I guess with OEMs it means SDLC members selling SDL (Core) enabled products like Ford Motor Company? Does this include companies selling after market IVI with SDL core support?
5. I'm Still not sure about message/issue visibility. Can a developer and SDLC member have private messages and issues? I'm very sure some issues will be related to confidential data. I would expect developers to be able to mark chats and issues as secret/private.
6. Will there be a REST/GraphQL interface so that members can link this platform with anything? Did we consider slack messaging support?

I'm concerned about this way of communicating with app developers especially when having partnerships. It all stands and falls with developers being motivated to handle input, feedback, issues etc. from any SDLC member. There should be a way to have some kind of Key account managers (aka. technical leads) who organises and aligns messages from all sources so that the app partner is not distracted. This leads to the point that registered companies should have a list of users (like Apple Enterprise Program with multiple developers with different roles). To my understanding all apps from one company are based on single login credentials. App developers have to decide on a single contact though the roles might be separated to multiple developers/teams. think of a company working on Android and iOS. The partners have to triage the issue and forward it according to the team. I don't see the benefit for the partner with this platform.

The proposal is missing some sort of notification system where people can listen to changes or updates. This notification system should be sending emails. Otherwise I don't see why developers will look into the portal.

Do we actually know what partner is requesting this feature? Did we ask existing app partners for feedback? The proposal does not say any word about it, which makes me worried about the quality of this portal. We should not create a service to serve a group without asking the group how to serve. We should not agree to this proposal without having a survey to existing developers. 

If we move forward with this feature there should be an opt-in for app partners to list their app on this platform. This opt-in should be added to the registration process and a message should be sent out to existing partners to opt-in.

**Comment by joeygrover** [comment]
1. It means the inverse of the selected OEM allowances. App developers currently select who they share their information with. This would be the ones they didn't. 
2. Initially it is a single thread to facilitate private OEM-> App communication that could be outside the scope of a singular issue. 
3. As stated in response to 1, app developers select their OEM allowances. As of right now, this allows OEM policy servers to retrieve that apps data (not the users or company). In this context, it will allow an OEM to open issues and chat with that app developer.
4. Yes, the term we use is "App Consumer". If the company has selected that they are an app consumer, they will show up as an option in the OEM allowance section of the app's information page.
5. As stated previously, right now the chats are only a single thread. We can add a warning that chat messages will be shared with the company entity. Issues, however, can have a private or public setting. Private means only the OEM and the app developer will see the issue. Public means the OEM, the app, and any of the app's OEM allowances will be able to see the issue.
6. Slack is a great tool for direct communication, but it lacks any real tracking ability. To facilitate a more centralized tracking system for SDL specific issues that OEMs are experiencing with their partners something new was needed. Due to concerns around storing data off the developer portal we decided to include this in the same portal and backend rather than offboarding the functionality. For the first phase there is no API that will be exposed. This could be a future addition. 

I agree that app communication is a delicate subject, and that's why we put something forward to try and take that on. The steering committee has talked about how we can track issues and improve the app communication process for a long time. However, there hasn't been any real progress and certainly no member has proposed anything. (I can dig up old meeting minutes here if you need to see) What we do know, is that we have developer feedback that the communication process can be slow and disorganized (with slack support being the exception). Therefore we created this proposal as a way the PM can directly get involved. 

I would love to see more app developer feedback, but I believe that is exactly what this forum is for. The proposal was put in front of the entire community to review. If you have specific partners you'd like to have review I'd recommend tagging them in the issue.

**Comment by nickschwab** [comment]
@kshala-ford 
> The proposal is missing some sort of notification system where people can listen to changes or updates. This notification system should be sending emails. Otherwise I don't see why developers will look into the portal.

Please see previous comment: https://github.com/smartdevicelink/sdl_evolution/issues/680#issuecomment-464778616

**Comment by kshala-ford** [comment]
Thanks @nickschwab but it doesn't answer the question of some public issue so that 3rd person can subscribe to issues. Let's say an issue in App A was created by OEM B. Me as OEM C or Developer D see this issue as well and want to know if and how it's fixed.

**Comment by nickschwab** [comment]
@kshala-ford 
> Thanks @nickschwab but it doesn't answer the question of some public issue so that 3rd person can subscribe to issues. Let's say an issue in App A was created by OEM B. Me as OEM C or Developer D see this issue as well and want to know if and how it's fixed.

As @joeygrover stated in his comment (https://github.com/smartdevicelink/sdl_evolution/issues/680#issuecomment-465168628) and is outlined in the proposal:
> As stated previously, right now the chats are only a single thread. We can add a warning that chat messages will be shared with the company entity. **Issues, however, can have a private or public setting. Private means only the OEM and the app developer will see the issue. Public means the OEM, the app, and any of the app's OEM allowances will be able to see the issue.**

**Comment by NicoleYarroch** [comment]
How would app developers actually go about starting an app review for a registered application with an OEM? From the proposal, it looks like they would start a chat with the desired OEM and then move forward from there?

**Comment by joeygrover** [comment]
App reviews are started when the developer selects "Ready for certification" on the app information screen. That piece is outside of the scope of this proposal and will likely be discussed when the app certification process is reviewed in the coming months.

**Comment by jordynmackool** [comment]
Due the meeting time running out on 2019-02-19, this proposal will be taken out of review and voted on during the next Steering Committee meeting on 2019-02-26.

**Comment by joeygrover** [comment]
@lauratonwe @kshala-ford As this proposal is still in review this would be a great time to tag any partners to have them review or send them a communication to review and have feedback ready by Tuesday!

**Comment by kshala-ford** [comment]
@nickschwab I'm sorry. May be I'm not clear about my concern. I am asking for the ability to subscribe and listen to public issues as a third person. I do understand issues being private or public and I do understand email notifications as it's proposed today but there are third parties interested in being notified about issue updates. We are already communicating about app issues cross OEM as multiple OEMs may be affected by an app issue and we do notify each other about issue updates. I doubt that third persons login to the portal every day to check for updates. Please consider issue subscription for third persons as a needed feature.

**Comment by BrettyWhite** [comment]
I agree @kshala-ford that that would indeed be a good feature to include. Whether or not it's included in v1, I don't think that should be a show stopper. Just as many features approved here come in steps (think RC, app services, RPC message protection) it is best to get good features moving forward. I think this proposal does a good job at moving toward a unified SDL platform - for both OEMs and developers, and helps reduce communication disparities.

**Comment by nickschwab** [comment]
@kshala-ford 

I share @BrettyWhite's stance that enhancements to issue email notifications should be considered for future iterations of this feature, not v1. This could mean opting into email notifications for all public issues, or opting into notifications on an issue-by-issue basis - to be determined at a later date in a future evolution proposal.

I recommend accepting this proposal with revisions to note the inclusion of basic email notifications, as mentioned in this comment: https://github.com/smartdevicelink/sdl_evolution/issues/680#issuecomment-464778616

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept this proposal with revisions. The author is to add additional details in the proposal stating that both the app developers and the OEM can choose to enable or disable email notifications through a new checkbox/toggle switch noted in [this comment.](https://github.com/smartdevicelink/sdl_evolution/issues/680#issuecomment-464778616)
There was additional discussion in regards to developing this proposal as a beta to determine if it was widely used and allow OEMs and App developers to use this feature at their own will. After a great deal of conversation, it was determined that it would be in the best interest of the SDLC to have all members adopt this Developer Portal enhancement in full so that communication between app developers and OEMs can be greater. 
It was noted that additional enhancements could be added in future proposals such as the ability to subscribe and listen to public issues as a third person noted in [this comment.  ](https://github.com/smartdevicelink/sdl_evolution/issues/680#issuecomment-466919558)

**Comment by jordynmackool** [comment]
The author updated the proposal to reflect the accepted revisions on March 5, 2019, in this [commit](https://github.com/smartdevicelink/sdl_evolution/commit/cf762c2fffb423998218ea46a2f6fcf91ee34425#diff-a87a76911cb684764fa8ab8469062903).
