### ISSUE TITLE
[In Review] SDL 0230 - SPP resource management for Android

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#730]
Hello SDL community,

The review of the revised proposal "SDL 0230 - SPP resource management for Android" begins now and runs through July 23, 2019.  Previous reviews of this proposal took place June 26 - July 9, 2019, June 5 - June 18, 2019, and May 15 - May 21, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0230-spp-resource-management-for-android.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/730

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
| 1. There is no message defined as to what will be presented to the user. This should be defined here as to what is an acceptable message to the developer while taking into consideration they might have already started driving by the time they see this message.

If each app developer is forced to decide what should go into that notification, it adds the burden onto them to decide what it should say and the SDLC will not have control over such messaging. This can lead to confusion to the user when inconsistent messaging is present.

| 2. Legacy Mode is required for apps to work on IVI systems that use v1 of the SDL Protocol. If a developer selects to not allow legacy mode they will not work on those systems and it should be understood that is a risk.

| 3. Legacy mode is also an important part of ensuring apps are able to display on an IVI system even if the router service feature fails. Allowing apps to prevent this will likely lead to confusion on the users side that they do not understand why some apps show up and some apps do not. This is an undesirable user experience.

| 4. Disallowing legacy mode by default does not seem acceptable because of point 2 and 3. It should default to true if implemented.

| 5. There is some unnecessary code when unable to obtain the RFCOMM channel. The `MultiplexBaseTransport` class already has states including an error state. This can be used to inform the implementing class that the transport has experienced an error. This type of communication should be performed as it is already establishes communication between the router service and the implemented transports. 

| 6. An alternative to creating a dialog would be using the notification for the router service itself, or a separate notification. Just an option.

| 7. `MessageType` does not need to be an enum. It can either be a simple constant or using Android's enumerated annotations for a pseudo-enum.

**Comment by khburdette** [comment]
For clarification, setLegacyModeAllowed is for the use case where you are using the v1 protocol?

Implementing the notification listener is only required when the app wants to do something when the SPP channel runs out of available resources?

**Comment by joeygrover** [comment]
>For clarification, setLegacyModeAllowed is for the use case where you are using the v1 protocol?

`LegacyMode` is also used when the currently running router service is not trusted by the client library.

>Implementing the notification listener is only required when the app wants to do something when the SPP channel runs out of available resources?

As I understand the proposal, yes. Which forces the developer to make a choice if they want to propagate a dialog. If there is no real use case by developers to do this, it is an unnecessary addition. Therefore, if this feature is to be accepted the library should handle the messaging and behavior itself. Possibly giving apps the ability to disable the dialog.

**Comment by khburdette** [comment]
I agree with Joey on his point 4, setLegacyModeAllowed should default to true.

I don't see an issue with adding the new notification listener for the case where the SPP channel runs out of available resources because it's not removing functionality or requiring the app to do more work. As Joey already stated, if we're going to use this as a way to deliver some sort of dialog, we should make sure there's some consistency among SDL apps.

**Comment by mrapitis** [comment]
I agree that adding better notifications would be beneficial for error cases like mentioned when the device has ran out of available SPP ports.  I understand the desire to make messaging uniform and provide the messaging library side, however we do have some concerns regarding overall maintenance of strings and their respective translations.  Similar concerns were voiced in #356 for iOS background strings in the past.  If the messaging is being handled library side, I believe as a prerequisite we would need to have a process in place regarding handling of string translations.

In regards to LegacyMode as mentioned it is needed, but IMHO LegacyMode should be used exclusively as a last resort for low bandwidth transports only.  In testing we have seen cases where the proxy falls into legacy mode because security was set to high (and RSVP validation failed) while high bandwidth was also set to true (projected app).  In this case the proxy shuts down all together and cannot connect with the HU because no acceptable transport was found.  It seems counter intuitive in this case; one would expect the app to be able to spin up its own service locally that is considered trusted to utilize with a high bandwidth transport when needed.

**Comment by joeygrover** [comment]
So are you saying it's acceptable to have app developers define their own messages? Do we have any guidelines for them? Or do you seem them being in complete control of what gets displayed? IMO pushing off responsibility from the SDLC to the app developer is not a good practice that gets abused too often. If we tell developers they have to do this, then each app developer will be responsible for what messaging is used and the translations that follow. Then if each OEM has different requirements on what that string/message can be they have to create custom integrations. 

I think this point on LegacyMode is a bit off topic in regards to the proposal. Legacy mode is used for protocol v1  and for low bandwidth when there is no trusted router service available. That is the current, defined behavior. In the case you mentioned it is not possible for an app to spin up their own service as the AOA resources are only available to be opened by a single application and in order to use TCP there has to first be a primary connection established. Any proposal that outlines how that could be changed to achieve the desired results is welcomed. However, for this proposal the request is to add a flag that enables/disables the ability to use legacy mode bluetooth and my opinion is it should not be an option.

**Comment by mrapitis** [comment]
> So are you saying it's acceptable to have app developers define their own messages? Do we have any guidelines for them? Or do you seem them being in complete control of what gets displayed?

It makes sense to handle the messaging library side to provide uniformity and simplicity for app developers like mentioned.  If this approach is taken, my suggestion would be to have a translation process / system in place to handle strings appropriately.

In regards to the flag that enables/disables the ability to use legacy mode, I agree that this should not be an option.

**Comment by shiniwat** [comment]
@joeygrover @mrapitis @khburdette Thanks for the feedback. There're two open issues in the discussion:

1) When SPP channel is out of resource, we have two approaches: a) define a listener in the proxy, and let application developer implement the listener to provide UX, b) implement error UX in the proxy itself.
This proposal takes the approach a), because Android Proxy basically has no error UX, and I thought it would be the design policy. If maintainer prefers approach b), that's OK, but in that case showing dialog does not make sense (because it is service). We have to think about what is the expected UX if we take approach b).

2) Whether or not it makes sense to enable/disable the ability to use legacy mode
I understand that legacyMode is required for V1 support. Let's focus on if legacyMode is indeed required when trusted RouterService is not found. As mentioned in the proposal, legacyMode consumes additional SPP resource on device, which definitely causes negative effect. Suppose 10 SDL apps exists on the device, and if all SDL apps falls into legacyMode, I don't think all apps can register to SDL Core because of limited SPP resources. Let's think about another example, e.g. navigation app, which won't work with V1 protocol. If the navigation app uses both BT transport and USB transport, it would be beneficial to allow an option to disable legacyMode, because the app knows it won't use legacyMode at all.

**Comment by joeygrover** [comment]
1. The service doesn't have to create a UI itself. As I suggested, using a notification is likely the better UX paradigm. Then if a user presses the notification it can present the user with a dialog that informs them of the situation. However, to @mrapitis comment, we would need to ensure what string is used and that it is translated properly to a number of supported languages. 

2. Navigation apps will already set the requiresHighBandwidth flag if they can't use bluetooth. This includes legacy mode. The SdlProtocol class will respond to the TransportManager that the app does not support legacy bluetooth through this flag or if the app didn't include Bluetooth as a supported primary transport. Adding the flag to allow/disallow legacy mode will simply create a worse user experience by confusing users on why some apps show up and some dont when connected to the same transport as well as OEMs have to understand which developers have enabled legacy mode. The current strategy is to ensure all apps go through the certification process and get added to the trusted service list which will help avoid the legacy connection fallback.

**Comment by shiniwat** [comment]
Regarding 1.
>using a notification is likely the better UX paradigm. Then if a user presses the notification it can present the user with a dialog that informs them of the situation

OK, using the notification approach sounds good. I am wondering, however, if having string resource in the library itself is indeed the good approach. It is up to the application what language is supported, and other cases will use the fallback language (usually English). I think the library can implement the predefined string in English, and apps are responsible for providing localized resources in accordance with the supported languages.

Regarding 2.
My point is that we want to reduce (or completely remove) the case where the application unexpectedly falls back to legacyMode. I often see the legacyMode case when running with custom RouterService, too. We may need to come up with a better way than having legacyModeAllowed option, though I don't have a good idea at this moment.

**Comment by theresalech** [comment]
A large part of the discussion about this proposal in the Steering Committee meeting focused on how translations should be handled in scenarios like the one presented by this proposal.  Considerations included how the SDLC would decide which languages would be translated and who would be responsible for obtaining and maintaining translations (possibilities for inconsistencies if app developers are responsible, additional maintenance if the SDLC is responsible).  There was also agreement that an alternative to `legacyModeAllowed` should be discussed in a separate proposal.  The Steering Committee ultimately voted to return this proposal for revisions.  The revisions will include the following:

- Author to propose standard string that would be used in the notification from the service to inform the user that they need to close other apps in order to open up a potential SPP channel, as well as details about what the notification will look like
- Author to propose which languages the above string would be translated to, considering the language enum of the [Mobile API](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L167) for reference
- Author to propose who they believe should be responsible for obtaining and maintaining translations of this string, setting the precedent for future similar cases.
- Remove legacyMode components from proposal, as these should be discussed separately

**Comment by theresalech** [comment]
The author has revised the proposal, and it is now ready for Steering Committee Review.  The Steering Committee will vote on the revised proposal during the 2019-06-11 Steering Committee meeting.

**Comment by joeygrover** [comment]
|5. As stated previously `    private Runnable mSocketErrorListener;` is **not** necessary. See the previous comment. The solution should make sense of the communication handler that is already in place as to not create multiple entry points to the class for state communication. 

| 8. 	`public void notifySppError()` why does this need to be a target level of 28? Also, there are no checks around 

| 9.  The `NOTIFICATION_LOCK` variable is used for the foreground notification synchronization, not for all notifications in general. I don't believe it should be used here. Another lock could be introduced or just synchronize on the class instead if necessary, but I don't see an obvious  reason why it would need to be. 

| 10. `SdlNotificationActivity` will require developers to add an additional activity to their manifests. If they don't this activity won't be displayed. I would recommend it takes other actions, like a dialog or redirect to a URL where more information could be stored. This could also be a local page in the library that gets opened via an Intent to open an installed browser app. 

| 11. Might be good to use a different icon here as well. Something to convey there was an issue. 

| 12.
`    <string name="spp_out_of_resource">Bluetooth channel is out of resource</string>`

This should be something a little bit more user friendly. Most users do not understand what an RFCOMM channel is. Something like `Too many apps using bluetooth` or `Bluetooth is unavailable`, something that has a higher level wording to it.

| 13. `spp_out_of_resource_message` similar comment as 12. I'm not sure users are going to know which apps to close because it's not clear which apps are using bluetooth. If we're going to give them instructions, we should make sure they are clear. If we want to tell them to close apps using bluetooth, we should try to tell them which apps are using bluetooth. 

| 14. `Localization of SPP error UX` I believe we would still need to get sign off of each translation by the steering committee. That way all SDLC members have an opportunity to review and accept them before being added to the library.

**Comment by shiniwat** [comment]
> 5. private Runnable mSocketErrorListener; is not necessary

OK, I will extend MultiplexBaseTransport.setState something like below
```java
    protected synchronized void setState(int state, int error) {
        if(state == mState){
            return; //State hasn't changed. Will not updated listeners.
        }
        //Log.d(TAG, "Setting state from: " +mState + " to: " +state);
        int arg2 = mState;
        arg2 |= error;
        mState = state;

        // Give the new state to the Handler so the UI Activity can update
        //Also sending the previous state so we know if we lost a connection
        notifyStateChanged(state, arg2);
    }

    private void notifyStateChanged(int arg1, int arg2) {
        handler.obtainMessage(SdlRouterService.MESSAGE_STATE_CHANGE, arg1, arg2, getTransportRecord()).sendToTarget();
    }
```

so that we can use MultiplexBluetoothTransport.setState(STATE_ERROR, REASON_SPP_ERROR) to notify the SPP_ERROR.
REASON_SPP_ERROR can be defined something like
```java
public static final int REASON_SPP_ERROR    = 0x00010000;    // REASON = SPP error, which is sent through Message.arg2.
```
>8. why does this need to be a target level of 28?

Sorry, that was a typo. Actually that should have been:

```java
	@TargetApi(11)
	public void notifySppError() {
           // because Notification.Builder(Context) requires API 11.
            ...
        }
```

>9. The NOTIFICATION_LOCK

I thought it is used for all notification channel. I will remove the NOTIFICATION_LOCK clause because it is not for the designed purpose.

>10. I would recommend it takes other actions, like a dialog or redirect to a URL where more information could be stored

OK, the idea sounds good. How about the following approach:
```java
in SdlRouterService class
	/**
	 * This method can be overridden by developer in their own SdlRouterService class.
	 * @param error
	 * @return
	 */
	public Intent getErrorNotificationIntent(int error) {
		return null;
	}
```

Then, we can use the developer's defined intent something like:
```java
	public void notifySppError() {
		...
		// Create an intent that will be fired when the user clicks the notification.
		Intent intent = getErrorNotificationIntent(MultiplexBaseTransport.REASON_SPP_ERROR);
		if (intent == null) {
			intent = new Intent(getApplicationContext(), SdlNotificationActivity.class);
		}
		PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent, 0);
		....
	}
```

>11. Might be good to use a different icon here as well

OK, that makes sense. But the icon must be reviewed by steering committee, right?

>12 <string name="spp_out_of_resource">Bluetooth channel is out of resource</string>

Well, `Too many apps using Bluetooth` sounds good to me. The title still needs to be reviewed by steering committee.

>13 <string name="spp_out_of_resource_message">

Well, I don't have very good idea what message is better to let users know the situation. Giving instructions would be good, but as mentioned int he proposal, it is not practical to identify which app uses the Bluetooth socket. Any suggestion would be appreciated.

>14. Localization of SPP error UX

OK, I will revise the proposal as suggested.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2019-06-18, to allow the author time to respond to the comments left on the review issue.  On the call, it was clarified that regarding 13. (`spp_out_of_resource_message`), we need to be clear with which action user's should take as we cannot tell them to close apps using Bluetooth if they don't know which apps are using Bluetooth.

**Comment by joeygrover** [comment]
| 5. This would actually be a breaking change since you're changing what information is sent through `arg2`. Since all the simple arguments are taken up I would suggest attaching a Bundle to the message for Error states that contains an extra `ERROR_TYPE` with a value of the correct type of error. 

| 10. This is not a good approach because it is forcing the developer to do something extra still. Then we have to determine if it is optional or not. And if it is not optional, then we will have to determine what are acceptable actions to be taken there. It's easier if we redirect to a URL which could be a stored webpage.

| 11. I suppose that would be up to the SDLC to decide, or if they could trust the project maintainer and author in creating a solution that aligned with the SDL brand guidelines.

| 13

Well we know if an app is using one of the SPP/RFCOMM channels, then they must have the bluetooth permission. So we could add something that checks for those permissions and returns a list of `ApplicationInfo` objects that can point to those apps which could be listed.

```
	private List<ApplicationInfo> checkBluetoothPermissions() {
		PackageManager pm = getPackageManager();
		List<ApplicationInfo> packages = pm.getInstalledApplications(PackageManager.GET_META_DATA);
		List<ApplicationInfo> bluetoothApps = new ArrayList<>();

		for (ApplicationInfo applicationInfo : packages) {
			try {
				PackageInfo packageInfo = pm.getPackageInfo(applicationInfo.packageName, PackageManager.GET_PERMISSIONS);

				//Get Permissions
				String[] requestedPermissions = packageInfo.requestedPermissions;
				boolean usesBluetooth = false;
				if (requestedPermissions != null) {
					for (int i = 0; i < requestedPermissions.length; i++) {
						if(Manifest.permission.BLUETOOTH.equalsIgnoreCase(requestedPermissions[i])
								|| Manifest.permission.BLUETOOTH_ADMIN.equalsIgnoreCase(requestedPermissions[i])){
							usesBluetooth = true;
							break;
						}

					}
				}
				if(usesBluetooth){
					bluetoothApps.add(applicationInfo);
					CharSequence appName =  pm.getApplicationLabel(applicationInfo);
					if(appName != null){
						Log.i(TAG, "checkBluetoothPermissions: " + appName + " uses bluetooth");
					}else{
						Log.i(TAG, "checkBluetoothPermissions: null uses bluetooth");
					}
				}
			} catch (PackageManager.NameNotFoundException e) {
				e.printStackTrace();
			}
		}
		return bluetoothApps;
	}
```

**Comment by shiniwat** [comment]
>5. This would actually be a breaking change since you're changing what information is sent through arg2

I don't think it is breaking change to extend the ```arg2``` for specific combination of ```what``` and ```arg1```. In particular, arg2 is currently not checked at all when ```arg1``` (i.e. new state) is ```STATE_ERROR```, so extending the ```arg2``` in that case won't break existing app. However, it is more likely preference thing, so it is OK to use Bundle instead. Here's the code snippet for using Bundle:

```java
    public static final String ERROR_REASON_KEY = "ERROR_REASON";
    public static final byte REASON_SPP_ERROR   = 0x01; 
    ....
    protected synchronized void setState(int state, byte error) {
        if(state == mState){
            return; //State hasn't changed. Will not updated listeners.
        }
        //Log.d(TAG, "Setting state from: " +mState + " to: " +state);
        int arg2 = mState;
        mState = state;

        // Give the new state to the Handler so the UI Activity can update
        //Also sending the previous state so we know if we lost a connection
        notifyStateChanged(state, arg2, error);
    }

    private void notifyStateChanged(int arg1, int arg2, byte error) {
        Message msg = handler.obtainMessage(SdlRouterService.MESSAGE_STATE_CHANGE, arg1, arg2, getTransportRecord());
        Bundle bundle = new Bundle();
        bundle.putByte(ERROR_REASON_KEY, REASON_SPP_ERROR);
        msg.setData(bundle);
        msg.sendToTarget();
    }
```

>10. This is not a good approach

Well, this is error UX that tells users what went on. From localization perspective, the simplest way would be to utilize Android dialog, because it takes the advantage of Android system's internationalization. Providing language specific webpage is more complex than using dialog. This is why the revised proposal uses the Dialog. As you suggested, this will require developers to add the activity into AndroidManifest. In order to make it optional, I think it's OK to use the WebPage (in English) by default if developers don't specify the intent:

```java
	public void notifySppError() {
		Intent intent = getErrorNotificationIntent(MultiplexBaseTransport.REASON_SPP_ERROR);
		if (intent == null) {
			intent = new Intent(Intent.ACTION_VIEW, Uri.parse(SDL_SPP_ERROR_WEB_PAGE + "?lang=" + Locale.getDefault().getDisplayLanguage()));
		}
	}
```

>11. I suppose that would be up to the SDLC to decide

No objection to rely on project maintainer to use the different icon that conforms the SDL design guideline.

>13. utilizing ApplicationInfo to obtain the app list that uses Bluetooth permission

That would be a good idea. But I am wondering if it is legitimate to say "Please close the app XXXX because that uses Bluetooth", because the app XXXX is external app. If that's OK, specifying the application would be helpful for users to get recovered from the error.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions, so that the author can update the proposal to reflect the discussion with the Project Maintainer on the review issue.  Regarding comment 13, it was clarified that SDL apps won't be included in the list of apps to try and close to obtain SPP connections.  Instead of giving a direction, the response can be informative, such as "The following applications are taking up Bluetooth resources."

**Comment by theresalech** [comment]
The author has updated the proposal, and the revised proposal is now in review until 2019-07-09.

**Comment by joeygrover** [comment]
1\. Minor edit:

` public static final byte REASON_SPP_ERROR   = 0x01;    // REASON = SPP error, which is sent through Message.arg2.`
That should be updated to say attatched as value in bundle with key `ERROR_REASON_KEY` or something similar. 

2\. I think the code should be updated as followed

``` java 
private void notifyStateChanged(int arg1, int arg2, byte error){
   ...
   }
``` 

should instead be 

```java 
protected synchronized void setState(int state, Bundle bundle) { 
    if(state == mState){
        return; //State hasn't changed. Will not update listeners.
    }
    int arg2 = mState;
    mState = state;

    Message msg = handler.obtainMessage(SdlRouterService.MESSAGE_STATE_CHANGE, arg1, arg2, getTransportRecord());
    msg.setData(bundle);
    msg.sendToTarget();
}
```

That way it could be used for other states in the future if we need to add additional data for other states and `notifyStateChanged` method is uncessary.

Next, the stop() method should look like the following,

```java

    @Override
    protected synchronized void stop(int stateToTransitionTo, byte error) {
    	
    	...
    	if(stateToTransitionTo == STATE_ERROR){
    	    Bundle bundle = new Bundle();
            bundle.putByte(ERROR_REASON_KEY, error);
			setState(stateToTransitionTo, bundle);
    	}else{
            setState(stateToTransitionTo, null);
        }
    }

```

In RouterService I would do the following deprecate `onTransportError()

```java
private static class TransportHandler extends Handler{
	    @Override
	    public void handleMessage(Message msg) {
	        case MESSAGE_STATE_CHANGE:
	            TransportRecord transportRecord = (TransportRecord) msg.obj;
	            switch (msg.arg1) {
	        	....
                case MultiplexBaseTransport.STATE_ERROR:
                    service.onTransportError(transportRecord, msg.getData());
                    break;
                }
	    }
	};


    @Deprecated
	public void onTransportError(TransportRecord transport){
		onTransportError(TransportRecord transport, null){

	}

	public void onTransportError(TransportRecord transport, Bundle errorBundle){
        switch (transport.getType()){
            case BLUETOOTH:
                if(bluetoothTransport !=null){
                    bluetoothTransport.setStateManually(MultiplexBluetoothTransport.STATE_NONE);
                    bluetoothTransport = null;
                }

                if (errorBundle != null && errorBundle.getByte(MultiplexBaseTransport.ERROR_REASON_KEY) == MultiplexBaseTransport.REASON_SPP_ERROR) {
                        notifySppError();

                }
                break;
            case USB:
                break;
            case TCP:
                break;
        }

    }
```



3\. `getErrorNotificationIntent` being overriden would allow developers to create different experiences based on which apps have that method overriden. For example, if a malicious app was able to start running as the router service, it could input any number of intents into that return which opens up the SDLC to being responsbile for whatever happens. I do not believe this is a good idea. I do not see a need for developers to supply their own intents and thefore think this should be removed. The experience for the user should be kept the same regardless of which app started the router servce.

4\.

> Please note that channel name ("SDL Error" in Fig. 2) is TBD.

>The details of error text on the WebPage is still TBD

These need to be figured out before acepting this proposal.

5\.

>Localized strings are maintained by project maintainer, and steering committee will be responsible for sign off of those localized strings.

Once the default english string is accepted, and the SDLC votes to accept the translations, the project maintainer will not alter the strings. It will be up to the SDLC to make changes to them, so their is no maintaince. 

6\.

>Showing the list to the user will be optional (at least developers can choose), because we may need to determine if it is worth doing or not.

I disagree here for similar reasons that changing the eperience based on which app starts the router service is a poor UX for the user. It should be consistent. So we either include the list, or we don't. However, with starting a webpage  form an intent and letting the user's default browser handle the request, it will be difficult to pass this list to the webpage even if it is a stored webpage.

7\. Potential downsides: As the proposal is asking to notify the user with vibration, sound, etc I think the SDLC should be very aware that the SDL library and any apps that implement it will be doing so to their users. This has to be considered with caution.

**Comment by shiniwat** [comment]
> 1. 1. Minor edit:

Yes, the comment needs to be updated as suggested.

> 2 notifyStateChanged and stop method.

Well, the code snippet could be revised as suggested.

> 3. getErrorNotificationIntent

I understand your point, but then we need to determine if we should provide either local dialog UX or lead to Website when user clicks on notification. Because local dialog is easier to localize, I prefer the local dialog, but in previous comments, the maintainer suggest using Website.

> 4 and 5.

It depends on if error UX is Web site or local dialog, so we need to determine the UX.

> 6. Showing the list to the user will be optional 

Well, I will think about it again. I am actually wondering if showing the list is indeed worth doing,.

> 7. Potential downsides:

Will update as suggested.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions, as the author noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/730#issuecomment-509833760).  The author and project maintainer also discussed item 3 on the call, determining that if possible, the notification error could be updated to something like "Too many apps are using Bluetooth. Please close some of them and try to reconnect." so that the string is localized and there is no need to add another intent or start up another screen.

**Comment by theresalech** [comment]
The author has updated the proposal, and the revised proposal is now in review until 2019-07-23.

**Comment by joeygrover** [comment]
5\. The proposal still states the PM will be responsible for maintaining the translations. I would ask this be removed and clearly stated the translations will not change without the SDLC requesting to do so.


8\. `public void notifySppError() {` should be private. 


## Items that should be announced and understood before vote:

- Notification will be "noisy" including lights, vibration, and sound.
- Notification will display a message to the user, these strings should be reviewed before vote.

**Comment by shiniwat** [comment]
> 5. The proposal still states the PM will be responsible for maintaining the translations.

I did not mean PMs will update translations whenever they want, but I will clarify that point as suggested.

> 8. `public void notifySppError() {` should be private.

I will update accordingly.

> Items that should be announced and understood before vote:

During the review period, we would understand pros and cons about Notification, and we got into the consensus that Notification would be the most reasonable method to notify the SPP error. I believe steering committee members understood that point already.

**Comment by theresalech** [comment]
During the Steering Committee discussion of this issue, it was noted that the Steering Committee had previously considered the possibility of pointing the user to a URL/Webpage with regards to the `SDLNotificationActivity` component, and came to the conclusion that a notification with "Too many apps are using Bluetooth" dialog would be best as to not overcomplicate the UX and take advantage of the Android system's internationalization.  Additional information about this item can be found in the review issue comments.

It was also specified that by accepting the proposal, members understood that the notification implemented by the feature will be "noisy" including lights, vibration, and sound.  Additionally, the notification will display the following message to the user "Too many apps are using Bluetooth" (in English).  It was understood by members that the English string would be accepted by accepting the proposal, and there would be an additional review period for SDLC Members to review translations of this string.

Ultimately, the proposal was accepted with the revisions included in the author's comment [here](https://github.com/smartdevicelink/sdl_evolution/issues/730#issuecomment-514008710).

**Comment by theresalech** [comment]
@shiniwat please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issues in the Java Suite repository for implementation. Thanks!

**Comment by theresalech** [comment]
Author has updated the proposal to reflect revisions, and implementation issue has been entered: [[SDL 0230] SPP resource management for Android](https://github.com/smartdevicelink/sdl_java_suite/issues/1132)
