### ISSUE TITLE
[Accepted] SDL 0249 - Persisting HMI Capabilities specific to headunit

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#816]
Hello SDL community,

The review of "SDL 0249 - Persisting HMI Capabilities specific to headunit" begins now and runs through September 3, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0249-Persisting-HMI-Capabilities-specific-to-headunit.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/816

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm not super familiar with HMI development, so forgive me if any of my comments are ill-informed.

1. Assuming that the HMI is able to have a software update change its capabilities, how would it be able to force Core to overwrite its cache?
2. (a) Would `Buttons.GetCapabilities` return different results for different templates? (b) Do RC capabilities change based on the connected application (whether or not it has permissions, for example)? (c) Wouldn't `GetLanguage` change between ignition cycles if the user changed the language of the head unit (i.e. they change it, then do a new ignition cycle)?

**Comment by atiwari9** [comment]
@joeljfischer 
1. Core can simply delete the file after loading up data from _cache_ file. That'd trigger file re-creation and re-persistence of capabilities data for next ignition cycle. It depends on OEM implementation, but most SW updates usually restart headunits anyways.

2. 
   a. `Button.GetCapabilities` sent all supported buttons. Templates may utilize a subset of this, details on that are sent as response for `SetDisplayLayout` rpc.

   b. No, RC capabilities from HMI(System) remain same. App's access to RC modules is controlled by policies.

   c. Yes, language change would trigger `UI.OnLanguageChange` , `VR.OnLanguageChange`, `TTS.OnLanguageChange` and that is why we treat those as [Dynamic](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0249-Persisting-HMI-Capabilities-specific-to-headunit.md#dynamic) ones since this is a User triggered event. Core would always overwrite the data in these notifications to _cache_ file. So even if user did an ign cycle after that, _cache_ file would already be updated with new language data.

**Comment by JackLivio** [comment]
1. If you want Core to handle delete the cache on a HMI software update then I think there needs to be a new enum added to ApplicationsCloseReason in the HMI API.

<enum name="ApplicationsCloseReason">
  <description>Describes the reasons for exiting all of applications.</description>
  <element name="IGNITION_OFF" />
  <element name="MASTER_RESET" />
  <element name="FACTORY_DEFAULTS" />
  <element name="SUSPEND" />
+<element name="SOFTWARE_UPDATE" />
</enum>

**Comment by atiwari9** [comment]
@JackLivio 

1. So for SW update scenario, SDL Core would know about it only after system has restarted. That is when SDL sends [GetSystemInfo](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/BasicCommunication/GetSystemInfo/index.md) to HMI. It is only now that SDL Core would know that SW has changed. SDL Core can then:

* Keep the current capabilities _cached_ and delete the _cache_ file. Upon next ign cycle, SDL Core would check for this file as per flow defined in proposal and trigger all the capabilities requests to HMI and persist the response. (Proposed flow)
* Trigger all the capabilities requests to HMI and wait for the response(and overwrite _cache_). Once response is received, unregister all registered apps with a _new_ `ApplicationsCloseReason` so that apps can request a fresh registration. (Alternate flow)

Cons of Proposed flow:
* Apps won't get the latest Capabilities changes for the ignition cycle right after SW update. For subsequent ignition cycles app would get updated capabilities.

Cons of Alternate flow:
* Apps would unregister abruptly during usage. That might be undesired user experience if user is interacting with application or if application is providing some service etc.
* Additional logic needs to be added to core to trigger capabilities requests upon HMI SW version check(`ccpu_version`)

In my opinion, it is more work if we follow Alternate flow while providing interruption to user. Proposed flow could also affect app functionality but assuming HMI would make changes which are backwards compatible, impact should be low here.

cc: @joeljfischer 

PS: Noticed that the sequence diagram is incorrect [in implementation guidelines](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/BasicCommunication/GetSystemInfo/index.md#sequence-diagrams)

**Comment by JackLivio** [comment]
@atiwari9 OK thank you for the explanation. Unfortunately the Con listed for the Proposed flow is kind of a deal breaker for me. I believe an app that has incorrect capabilities could cause other issues that might be worse for the user experience compared to an app re-registering. 

If the alternate solution is still not acceptable, then maybe there is a way we can improve it. Right now in Cores RAI request run function, Core will make an app wait for the HMI to be connected and cooperating with core. The flag (`IsHMICooperating`) that allows to Core to continue processing the RAI request is set to true after the HMI sends its first OnReady notification. 

I suggest we delay setting core's flag `IsHMICooperating` to true until after the HMI responds to Core's GetSystemInfo request to check the HMIs software version (best case), or delayed until the HMI responds to all of the interface capabilities after a software update (worst case). This will allow core to collect the capability information (cached, or from HMI) before responding to the RAI request.

**Comment by atiwari9** [comment]
@JackLivio

I am ok with alternate flow then along with your suggestion to hold up RAI till hmi responds to all capabilities requests *When data is missing in cache file*

**Comment by atiwari9** [comment]
@JackLivio 

I created a draft flow for what we discussed, let me know if you have same understanding.

![image](https://user-images.githubusercontent.com/18143556/64261240-36ea9580-cefa-11e9-9139-dddcf520f142.png)

**Comment by theresalech** [comment]
The Steering Committee discussed either returning this proposal for revisions or accepting this proposal with revisions, and it was determined the proposal should be returned.  The author will revise the proposal to use the alternate approach as agreed to in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/816#issuecomment-527656663), and include defined flow charts for what this connection scheme will look like.  The project maintainer may be able to assist with this offline as well.  Returning the proposal for revisions will allow all SDLC Members with the chance to review the new SDL Core to HMI connection scheme, and check to make sure it works within their implementations.

**Comment by jordynmackool** [comment]
The author has updated this proposal as requested in [this comment ](https://github.com/smartdevicelink/sdl_evolution/issues/816#issuecomment-527945314). 

The re-review of "SDL 0249 - Persisting HMI Capabilities specific to headunit" begins now and runs through September 17, 2019. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0249-Persisting-HMI-Capabilities-specific-to-headunit.md

**Comment by JackLivio** [comment]
👍

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Implementation issue entered: https://github.com/smartdevicelink/sdl_core/issues/3037.

**Comment by theresalech** [comment]
SDL HMI issue: https://github.com/smartdevicelink/sdl_hmi/issues/387
