### ISSUE TITLE
[Accepted] SDL 0023 - Update Mobile API to Include Mandatory Flag on Parameters

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#82]
Hello SDL community,

The review of "Update Mobile API to Include Mandatory Flag on Parameters" begins now and runs through February 7, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0023-update-mobile-api-mandatory-flag.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/82

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by stefanek22** [comment]
The proposal makes sense and has been a longstanding housekeeping task in the Mobile API.  Till now, the accepted rule has been that if the mandatory flag was not specified, the parameter was mandatory by default.  This proposal should remove the implicit rule and clarify the status for all parameters going forward.

**Comment by joeljfischer** [comment]
My only concern is that this makes the spec considerably more verbose. I would have preferred to have language in the spec that defines that parameters are mandatory by default and only optional parameters are specified as such. All parameters that are mandatory would then not have the mandatory flag at all. That should be just as clear, but would be less verbose.

**Comment by jacobkeeler** [comment]
I've run into several small issues (primarily with unit tests) which were caused by the `mandatory` field being omitted when it really should have been set to `false`. An example of this is the "GPSData" struct, which has optional parameters in the HMI_API, but not the MOBILE_API (due to omitting the field in each parameter).

Forcing this field to be included would fix those issues and prevent future issues of the same nature (so long as each parameter missing this field is reevaluated when this is implemented).

It seems to me that it would have been significantly clearer if the default value for `mandatory` was `false` in the first place. Optional parameters seems like the more likely case, and parameters being optional by default also seems like the more common convention. 

I've been told that the reason that `true` was the original default value was that the `mandatory` parameter was added after the fact, meaning that optional parameters didn't exist in the protocol to start with. This might introduce complications if the default value were changed directly to `false`, but it seems counterintuitive to leave it as `true`.

In any case, I do not think that the change proposed would really affect the verbosity of the spec a great deal (most parameters seem to have the field already), and I believe it would increase the clarity of the spec in many places. As such, I believe this proposal should be accepted.

I am also of the opinion that if this proposal were to be accepted, it should be done to both the MOBILE_API and the HMI_API, and that this convention should be enforced by the InterfaceGenerator so that the field is not omitted in the future.

**Comment by robinmk** [comment]
Agree to the proposal and the same should be applicable to HMI_API as well

**Comment by mrapitis** [comment]
The proposal is reasonable and I agree that the mandatory flag should be explicitly included for each parameter.  In the past the omission of the flag has caused confusion among developers and team members.

**Comment by theresalech** [comment]
Based on the comments left on this issue, the Steering Committee has approved this proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0023] Update Mobile API to Include Mandatory Flag on Parameters ](https://github.com/smartdevicelink/sdl_core/issues/1278)
