### ISSUE TITLE
[Accepted] SDL 0024 -Minimum iOS Version to 8.0

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#83]
Hello SDL community,

The review of "Base iOS Version to 8.0" begins now and runs through February 7, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0024-ios-8-0-minimum.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/83

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I believe this is the right time to drop iOS 7.0 and move the minimum version to iOS 8.0. Apple's Xcode 8 release in September 2016 largely dropped support for iOS 7, making it quite difficult to co-develop SDL iOS for both iOS 7 & iOS 8+. By focusing support on Xcode 8 and moving the minimum version to iOS 8+, we will be able to remove several separate code paths and continue to focus on making our swift compatibility as good as it can be. This would also free us for a potential eventual move to Swift as our codebase.

I believe this proposal should be accepted.

**Comment by kshala-ford** [comment]
What's the planned SDL version for that? 4.x or 5.0?

**Comment by joeljfischer** [comment]
While it isn't specified in the proposal, because this would be a breaking change it would be a major version change, so 5.0.

**Comment by Toyota-Sbetts** [comment]
While we don't have any concern with this specific proposal, we feel that the consortium should define some criteria for when SDL as a technology will change or drop the minimum supported version for mobile OS (adoption rate, age, etc.).  

From our perspective, each OEM may have specific requirements on the minimum mobile OS version they would like supported for their customers base and different criteria for when that changes.  Additionally, the adoptions rate of a new mobile OS version for each OEM's userbase may vary compared to each other or the overall public adoption rate.  

We also feel that app developers might have different criteria on which minimum OS version to support to cover their own userbase.  Just because no current SDL applications may be using iOS 7.x, maybe some potential app developer would want to.  If SDL clearly defines the criteria for changing the minimum mobile OS version, app developers and OEMs will have a clear picture on the level of support needed to adopt and maintain SDL now and in the future.

**Comment by mrapitis** [comment]
The proposal makes a reasonable request, currently according to apple iOS 9 & 10 account for 94% of iOS devices.  As Sbetts alluded to, going into the future a version support matrix could be beneficial so that developers know what to expect.

**Comment by asm09fsu** [comment]
@Toyota-Sbetts I agree, there should be some list of things that must be crossed off for us to move to a newer minimum version of iOS, such as Xcode version support. I believe we should create a new proposal for these once we have an idea of what we feel is necessary in determining what qualifies as an update parameter.

**Comment by joeljfischer** [comment]
@Toyota-Sbetts I agree that there should be a checklist before updating to a newer version in the future. This one has been done more by feel, considering that such a small percentage of users are still on iOS 7 and all major partners have moved to iOS 8 at a minimum.

**Comment by theresalech** [comment]
This proposal has been accepted by the Steering Committee, based on the comments left on the issue.  The committee has also agreed that we will need to define clear criteria on how SDL will change both iOS and Android support moving forward.  New proposals should be submitted for this request of both platforms.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0024] Minimum iOS Version to 8.0](https://github.com/smartdevicelink/sdl_ios/issues/526)
