### ISSUE TITLE
[Withdrawn] SDL 0258 - Update vehicle data TurnSignal

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#858]
Hello SDL community,

The review of "SDL 0258 - Update vehicle data TurnSignal" begins now and runs through November 12, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0258-Update-vehicle-data-TurnSignal.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/858

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm strongly against the current version of this proposal. This proposal is making a breaking change to merely add hazard lights.

1\. This proposal moves the `turnSignal` parameter to a new structure `TurnSignalData` but doesn't deprecate the old parameters (it weirdly only "deprecates" the description, which I'm not even sure we support in the MOBILE_API).

2\. Hazard lights are kind of already supported with `TurnSignal.BOTH`. If that's not adequate, why not add `TurnSignal.HAZARD`? Or, if that's not adequate, why not just add another parameter instead of making breaking changes?

**Comment by atiwari9** [comment]
@joeljfischer 

2. `TurnSignal.BOTH` does act as hazard lights. Thanks for pointing that out. Since the desired result can still be achieved by current implementation, though not specifically naming it as hazard lights, it is still technically acceptable to communicate to app partner to treat `TurnSignal.BOTH` as hazard lights.

@theresalech - Due to this reason, i'd like to **withdraw this proposal.**

**Comment by theresalech** [comment]
This proposal has been withdrawn per the author's request.
