### ISSUE TITLE
[Accepted with Revisions] SDL 0264 - Adding Audible Status Notification

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#872]
Hello SDL community,

The review of the revised proposal "SDL 0264 - Adding Audible Status Notification" begins now and runs through January 21, 2020. The review of the original proposal took place November 18 - December 3, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0264-Separating-the-change-of-Audible-status-and-the-change-of-HMI-Status.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/872

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm trying to understand the ask in this proposal. Is the ask for an alternate HMI_API to `OnEventChanged.eventName.AUDIO_SOURCE` that doesn't bring the app to HMI Background? If that's the case, then I believe I'm against this proposal. A media app that is playing audio should not remain in HMI NONE. It should be moved to HMI Background, Limited, or Full.

**Comment by Shohei-Kawano** [comment]
@joeljfischer -san 
Thank you for commenting our proposal.
We want to create a state with HMI_Level: Full and AUDIBLE_STATUS: NOT_AUDIBLE.
In other words, we want to create a state in which the template/VPM is shown, but not play the audio output.

**Comment by atiwari9** [comment]
@Shohei-Kawano  - For a phone call(event) use case, you may refer to [hmi guidelines here]( https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/BasicCommunication/OnEventChanged/index.md)

There are different set of events which control the `audioStreamingState` in `OnHMIStatus` notification. e.g. TTS also effects the audible state as described [here](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/TTS/Started/index.md)

**Comment by Shohei-Kawano** [comment]
@atiwari9 -san Thank you for providing information.
I found OnHMIStatus (FULL, NOT_AUDIBLE) status in the PHONE_CALL, media app is active Sequence Diagram.
Does this mean that I need to call SDL.ActiveApp again after calling OnEventChange (PHONE_CALL, isActive = true) to get this state(FULL, NOT_AUDIBLE)?
From the user's point of view, will the app be hidden and then reappear?
If so, we want to avoid it.
This is because flicker is a phenomenon that should be avoided in the Japanese market.
Probably, if it slow down the time to call SDL.ActiveteApp, it may disappear from the flicker, but from the user's perspective, it may appear that the app has been restarted.
So I think we need a way to change audioStreamingState while keeping the FULL state.

**Comment by atiwari9** [comment]
@Shohei-Kawano 

HMI needs to send correct notifications to SDL in order to receive appropriate HMI notifications as [defined here]{https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/BasicCommunication/OnEventChanged/index.md#phone_call}

You may refer to [`OnEventChanged` spec here](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L4622)
* when the phone call is active/starts, then HMI should send `OnEventChanged` to SDL with `eventName` =`PHONE_CALL` and `isActive` = true. 
* when phone ends, then HMI should send `OnEventChanged` to SDL with `eventName` =`PHONE_CALL` and `isActive` = false.

How you manage HMI screen transition is totally up to HMI. Ideally during the phone call, HMI screen should switch to Phone Call screen. After the call is completed, HMI screen should switch back to previously displayed app screen.

**Comment by Shohei-Kawano** [comment]
@atiwari9 -san
I understand that there is a screen transition that you are talking about as one case.
However, there are other ways to represent and transition the phone screen.
For example, it is possible to display the telephone screen using ONS, POPUP, NotificationBar, etc. on the SDL screen while the SDL screen is displayed.
I think that Core should not restrict HMI specifications.

**Comment by kshala-ford** [comment]
@Shohei-Kawano -san I read your proposal carefully to make sure I understand your motivation. If I'm understanding correctly, your main issue is related to SDL behavior with phone calls. You are looking for a way to remain app HMI levels as they are during phone calls. Similar to iOS where my incoming phone call is full screen but when I press the home button it only appears as a green status bar allowing me to use my apps again. Please let me know if there are other events or cases you like to cover with your proposal.

You're proposed solution to add a new HMI RPC could solve the problem but according to the current HMI integration guidelines it would require quite a lot of additions and modifications to make sure it doesn't break existing logic. I think your idea could be solved without additional API; just by changing existing logic. Thanks @atiwari9 for sharing the link to the guidelines. It gave me the idea. Let me try to explain:

As mentioned in the SDL HMI Integration Guidelines for OnEventChanged for PHONE_CALL (see [here](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/master/docs/BasicCommunication/OnEventChanged/index.md#phone_call) the HMI must do following steps when a phone call starts:

1. Send BC.OnEventChanged(PHONE_CALL, active:true)
2. Send SDL.OnAppDeactivated(app_id) _where app_id is the current activate app_

The guidelines are saying

> Upon receiving OnEventChanged(PHONE_CALL), SDL will:
>
> isActive | Result
> -- | --
> true | Change the HMI state of all applications currently either in FULL or LIMITED to (BACKGROUND, NOT_AUDIBLE)

I believe the result is a combination of both RPCs, not only the result of `OnEventChanged`. I think this result can be changed in SDL Core so that OnEventChanged and OnAppDeactivated can offer the change you're looking for. See suggested change when a phone call starts:

1. Send BC.OnEventChanged(PHONE_CALL, active:true)
   
    SDL Core knows that a phone call starts. The phone call doesn't necessarily take over the full screen but it could only be Notification Bar. Therefore audible apps receive `OnHMIStatus.audioStreamingState=NON_AUDIBLE` but they keep the current HMI level.

2. Send SDL.OnAppDeactivated(app_id) _where app_id is the current activate app_

    If the HMI is presenting the phone call UI as full screen. SDL Core should be notified that the app is deactivated. This should cause the app to transit to HMI_BACKGROUND.

Above change should be backward compatible. During a phone call the HMI should be able to activate/deactivate apps at any time and SDL Core should understand the HMI level transitions properly. Audible state should also remain NON_AUDIBLE because PHONE_CALL is still active. Please let me know what you think. Also the project maintainers could help to confirm feasibility.

**Comment by Shohei-Kawano** [comment]
@kshala-ford -san
Thank you for reading and understanding my proposal.

I'm not good at English, so please make sure my understanding is correct.

You recommend to change OnEventChanged (PHONE_CALL, active: true) behavior as follows:

|state|result|
|---|---|
| Current | Change the HMI state of all applications currently either in FULL or LIMITED to (BACKGROUND, NOT_AUDIBLE)|
| Changed | Keep the HMI state of all applications currently either in FULL or LIMITED |

is it right?

If yes, I think that it is good idea.

Please wait for the final conclusion as we will check it internal.
(Since Japan is a night now, there are no colleagues...)

**Comment by kshala-ford** [comment]
@Shohei-Kawano -san, I'm sorry for my [Germish](https://en.wiktionary.org/wiki/Germish). I tend to write lengthy sentences as I do in my native language (German).

You got it! My recommendation is to change the behavior of OnEventChanged(PHONE_CALL, active: true). I copied your table and extended the "result" so that it's more specific to the recommended change.

> state |	result
> -- | ----
> Current	| Change the HMI state of all applications currently either in FULL or LIMITED to (BACKGROUND, NOT_AUDIBLE)
> Changed	| Keep the HMI state of all applications ~~currently either in FULL or LIMITED~~ **but change audible state of all applications to NOT_AUDIBLE**

Note: You can still change the HMI state using `BC.OnAppDeactivated` and `BC.OnAppActivated` during an active phone call. This way you can switch between full-screen phone-call UI and NotificationBar phone-call UI.

**Comment by Shohei-Kawano** [comment]
@kshala-ford -san
Thank you for changing. The behavior has become very clear.
When I discussed about your idea at internal, it was an opinion that it was better to proceed with your plan.
Danke schön!!

**Comment by Shohei-Kawano** [comment]
@theresalech -san
I have a very good idea from @kshala-ford -san, so we think it's better to adopt it, but how should I proceed in this case?
Can we start correcting the proposal material? Or are we better off listening to other people's opinions and waiting for?

**Comment by theresalech** [comment]
@Shohei-Kawano the Steering Committee will need to vote on this proposal during our meeting on 2019-12-03.  During the meeting, you can request that the Steering Committee vote to return this proposal for revisions, to incorporate the suggestions from @kshala-ford.

**Comment by JackLivio** [comment]
@kshala-ford @Shohei-Kawano 

I agree with the updates needed for the behavior in the chart described below.

> state |	result
> -- | ----
> Current	| Change the HMI state of all applications currently either in FULL or LIMITED to (BACKGROUND, NOT_AUDIBLE)
> Changed	| Keep the HMI state of all applications ~~currently either in FULL or LIMITED~~ **but change audible state of all applications to NOT_AUDIBLE**

**Comment by theresalech** [comment]
Per the author's request, the Steering Committee voted to return this proposal for revisions.  The author will revise the proposal to change the behavior of `OnEventChanged` as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/872#issuecomment-559523287).

**Comment by theresalech** [comment]
The author has revised this proposal per the Steering Committee's request, and the revised proposal is now under Steering Committee review. This review will take place until January 21, 2020.

**Comment by joeljfischer** [comment]
1\. This also needs a documentation update for integrators.

Other than that 👍

**Comment by Shohei-Kawano** [comment]
Hi @joeljfischer -san
Thank you for your comment.

1. You say we need to add sample code etc. to document for integrator?

**Comment by joeljfischer** [comment]
The HMI integration guidelines will need a substantial revamp of this use-case.

**Comment by Shohei-Kawano** [comment]
@joeljfischer -san
I understand. thank you for your reply.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, with the revision that it should specify it requires a documentation update for the integrators.

**Comment by theresalech** [comment]
@Shohei-Kawano Please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated and implementation issues have been entered:
- [Core](https://github.com/smartdevicelink/sdl_core/issues/3227)
- [Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/236) 
- [SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/275)
