### ISSUE TITLE
[In Review] SDL 0267 - Main Menu UI Updates

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#882]
Hello SDL community,

The review of "SDL 0267 - Main Menu UI Updates"  begins now and runs through December 10, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0267-addcommand-ui-updates.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/882

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
I do support this proposal. It's a good enhancement to the app menu. I do have a question to `AddCommand`. Is there a particular reason why the proposed params are suggested in `AddCommand` and not in `MenuParams`?

**Comment by joeljfischer** [comment]
Thanks @kshala-ford, I didn't have a strong reason either way. The reason I added it directly to the `AddCommand` was because `AddSubMenu` doesn't have `MenuParams` and I didn't want to add them to different places. If the steering committee wants them in the `MenuParams` struct that's fine, though the `MenuParams` struct doesn't have much utility, and I think it would be better to move away from using it.

**Comment by kshala-ford** [comment]
@joeljfischer personally I agree to `MenuParams` doesn't have much utility. I am looking for more consistency to the existing structure. Looking at `AddCommand` only I think the new params should be in `MenuParams`... but adding `AddSubMenu` to the equation I lean towards having all params in the root, may be even deprecating `MenuParams`. The deprecation would be no big deal as the menu managers can take it into account. Not sure if it's worth the effort because the only us will see the RPCs so it would be only for the beauty of the RPC API...

**Comment by kshala-ford** [comment]
I want to note the naming discrepancy between `cmdIcon`, `menuIcon` and `secondaryImage`. Can you elaborate why you chose the naming? I assume in the libraries, at the menu manager, the RPC naming is abstracted from the developer facing API?

**Comment by joeljfischer** [comment]
1. It would be nice to deprecate `MenuParams`, but it's probably not worth it. If the SDLC wants, I can move some or all of the updated parameters into the `MenuParams` struct for `AddCommand`.

2. Yes, I used nomenclature closer to `Choice` for the updates. The `name` naming for the text didn't really fit for secondary or tertiary text fields. I debated the `Icon` vs. `Image` naming. I decided to go `Image` because I was already using `Choice` naming for secondary text. I have no problem with renaming it to `secondaryIcon` if desired.

**Comment by kshala-ford** [comment]
1. In order to keep the existing structure the additional text params should go to MenuParams and secondaryImage should be in AddCommand because the image may be used in a UI view while in a VR session.

2. I agree with using the name image and match with the struct Choice.

**Comment by joeljfischer** [comment]
1. I'm okay with that.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: additional text params should go to `MenuParams`.

**Comment by theresalech** [comment]
@joeljfischer Please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
The proposal has been updated to reflect the accepted revisions, and implementation issues have been entered:
[RPC Spec](https://github.com/smartdevicelink/rpc_spec/issues/213)
[Core](https://github.com/smartdevicelink/sdl_core/issues/3195)
[SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/268)
[Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/230)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1510)
[Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1246)

**Comment by theresalech** [comment]
JavaScript Suite: https://github.com/smartdevicelink/sdl_javascript_suite/issues/348
