### ISSUE TITLE
[Accepted with Revisions] SDL 0027 - Increase Specificity of Handler Events

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#89]
Hello SDL community,

The review of "Increase Specificity of Handler Events" begins now and runs through February 14, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0027-ios-specify-handlers.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/89

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
I appreciate and support this proposal.

To overcome the issue of the two notifications for buttons you could merge them into one. OnButtonPress is a notification for the button actions "long press" and "short press". OnButtonEvent is a notification for the button actions "button down", "button up". All four enum values could be unified and be called "ButtonAction". 
```objc
enum {
    SDLButtonActionLongPress,
    SDLButtonActionShortPress,
    SDLButtonActionTouchUp, // or button up
    SDLButtonActionTouchDown, // or button down
};
```
The successor of the button notifications could be called `SDLOnButtonAction`. The handler for hard and soft buttons would be then `SDLButtonActionNotificationHandler` (I've removed the RPC prefix as it wouldn't be an actual RPC from head unit).

```objc
typedef void (^SDLButtonActionNotificationHandler)(SDLOnButtonAction *notification);
``` 

What's the benefit?
- There's only one notification for buttons
- App developers can easily implement e.g. a feature to seek through a song (all in one block of code)

Downside?
- SDLButtonAction isn't (but acts like) a notification from the head unit 
- (I expect) slightly more development effort within the sdk

**Comment by asm09fsu** [comment]
@kshala-ford we currently do support both `SDLOnButtonEvent` and `SDLOnButtonPress` in the `SDLSoftButton`'s `handler`, however its not clear to them that this is happening, so they can already seek through a song, as your example.

I don't like the idea of introducing a new enum type, but am opening to the conversation.

**Comment by joeljfischer** [comment]
@kshala-ford Thanks for the feedback. I've tried to think about this quite a bit, and I don't think I can agree. I don't like the idea of hiding the raw events in this case. It would have been ideal to have the raw events come in one notification, but we're not there anymore. I agree that problems could crop up (e.g. seeking through a song) by not having both events come into one block. If I'm understanding right the problem would be as follows:

Block 1 (event) starts a timer on the button down event to check for seeking.
Block 2 (press) registers a long press.
Block 1 (event) starts seeking after a certain amount of time, waiting for the button up event.
Block 2 (press) runs an unintended action due to the long press being registered.
Therefore, an unintended press event occurs when the event is the desired mode of operation.

Perhaps a solution that would help solve the issue while retaining the raw events could be:

```
typedef void (^SDLButtonActionNotificationHandler)(__nullable SDLOnButtonPress *buttonPress, __nullable SDLOnButtonEvent *buttonEvent);
```

One of the two will be set, the other will be nil. This makes it more explicit that there are multiple possibilities here and provides better typing while combining both into one block.

**Comment by kshala-ford** [comment]
@asm09fsu @joeljfischer thanks for your taking your time. To me it feels like over-specified to have press mode and event mode being divided. These modes are based on two enums each having two items so both are not of a big deal. The idea of having an action enum would follow the design of how `UIEvent` on a `UIControl` calls an `@IBAction` and make it more native to the API iOS developers are used to work with.

**Comment by asm09fsu** [comment]
@kshala-ford I understand your concern, however Apple's `UIControl` handles touch down events, not long press as well, so I don't think your comparison is equivalent.

The issue we arise with introducing a new enum instead of using the notifications themselves is if there is a proposal in the future that adds properties to the `SDLOnButtonPress` or `SDLOnButtenEvent` notifications, we will have to rearchitect this. With @joeljfischer 's solution, we would be safe.

**Comment by theresalech** [comment]
The Steering Committee has accepted this proposal, given the following revisions: the `SDLRPCButtonEventNotificationHandler` and `SDLRPCButtonPressNotificationHandler` would be combined into one handler instead, with the signature: `typedef void (^SDLButtonActionNotificationHandler)(__nullable SDLOnButtonPress *buttonPress, __nullable SDLOnButtonEvent *buttonEvent);`

**Comment by theresalech** [comment]
Issue entered: [[SDL 0027] Increase Specificity of Handler Events](https://github.com/smartdevicelink/sdl_ios/issues/537)
