### ISSUE TITLE
[Accepted] SDL 0029 - Multiple File Manager Transactions

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#91]
#Hello SDL community,

The review of the revised proposal "Multiple File Manager Transactions" begins now and runs through February 28, 2017. The original review of "Multiple File Manager Transactions" occurred February 8, 2017 through February 14, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0029-ios-multiple-file-manager-transactions.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/91

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by Toyota-Sbetts** [comment]
Ultimately this proposal doesn't impact us very much, but we're weighing the benefit of this proposal vs the potential risk.
As per the proposal's potential downsides:

> The primary potential downside of this proposal is that the APIs being added will be among the most complicated to implement in SDL. It wraps what is already a fairly complex API to upload files and provide completion blocks and will have to track those completion blocks and provide progress updates. Due to it also providing the number of bytes uploaded and to be uploaded, it will have to track those uploads in a bit more detail than the file manager currently does.

Complex changes often require a lot of time in development and validation and introduce a lot of risk of creating issues.
Assuming this, we're not sure the benefit obtained by this change is worth it.
Is this frequently requested by app developers or are there some metrics (ex. increased performance, reduces app size, etc.) to strengthen the motivation for this proposal?

**Comment by kshala-ford** [comment]
Personally from my experience I know quite some apps doing multiple file upload e.g. for choice sets, soft buttons or menu entries. Currently many apps keep track of correlation ids when uploading files. Some of them don't even track faulty uploads which means the app may not be fully functional throughout the current session (app registration). Bottom line it would be very helpful for app developers.

Looking at the completion handler hoping that it's possible to unify them:
```objc
typedef void(^SDLFileManagerMultiUploadCompletionHandler)(NSArray<SDLFileName *> *failedNames, NSUInteger bytesAvailable, NSError *__nullable error);

typedef void(^SDLFileManagerMultiDeleteCompletionHandler)(NSArray<SDLFileName *> *failedNames, NSUInteger bytesAvailable, NSDictionary<SDLFileName, NSError *> *errors);
```

- `failedNames` is equal to `errors.allKeys` if so the first parameter could be omited
- The value of `bytesAvailable` should be equal to the file managers `bytesAvailable` parameter, right? I bleive this information is used very rarely anyhow.
- The `error` parameter should be a simple error. The `userInfo` property of `NSError` could be used to provide file specific error message. To access file errors do e.g. `error.userInfo[@"files"]`

The unified handler could look like this. This would be a single parameter and shorten the method call to something more readible.
```objc
typedef void(^SDLFileManagerMultiTransactionCompletionHandler)(NSError *error);
```

The idea of adding `numberOfBytes` to SDLFile sounds very helpful to provide a precise progress calculation and it helps knowing the size of `data` without loading the actual data but I have some concerns about it:
- It may be ignored and not set by the app developer (especially in implementations already using the file manager)
- It may be set to a value that doesn't match the data size. (app developer may make mistakes)
- The underlying file/data can change. E.g. app updated to a new set of icons. (app developer may not want to track all SDLFile creations every time a file changes). 
- It's not essential to perform multi upload. It's just informative.

Personally I would be totally OK with having the progress information of how many files are uploaded compared to the total number of files.

Looking into the progress handler I'm afraid it adds some complexity which is not mandatory.
```objc
typedef void(^SDLFileManagerMultiUploadProgressHandler)(BOOL success, SDLFileName fileName, NSUInteger bytesAvailable, float uploadPercentage, NSDictionary<SDLFileName, NSError *> *errors);
```

- `bytesAvailable` could be removed (see completion handler above)
- `errors` should be `error` and set to an object only if the current file failed. Not sure if it is necessary to track all past errors. I belive this would be necessary only in very rare cases (the app should then track them).
- `success` could be omited when providing `error` (apps could use `if (!error)` )
- `uploadPercentage` could be replaced with `pendingFiles` telling how many files are left. This would overcome the need of `numberOfBytes`. As an alternative it would be the percentage of how many files are uploaded. File sizes may be different which means this progress information can be inaccurate. I belive this is acceptable because most of the time the app would upload a set of files of a similar size (set of icons for choices, all 30x30 pixels).

The progress handler could become very powerful when asking for a BOOL return value.
- YES/true would tell the file manager to continue file transfer
- NO/false would cancel the multi-file transfer. The completion handler would be called with the error 

At the end the progress handler could look like this
```objc
typedef BOOL (^SDLFileManagerMultiUploadProgressHandler)(SDLFileName *fileName, NSUInteger filesLeft, NSError *error);
```

For convenience there should be a second method to upload files but without the progress handler. Some apps may not be interesseted to know the intermediate status.
```objc
- (void)uploadFiles:(NSArray<SDLFile *> *)files completionHandler:(nullable SDLFileManagerMultiUploadCompletionHandler)completionHandler;
```

Do you want the multi file upload to work sequentially? Concurrent file upload heavily improves performance but only if uploading very small files. This should be asked through the method signature (concurrent should be default).

```objc
- (void)uploadFiles:(NSArray<SDLFile *> *)files completionHandler:(nullable SDLFileManagerMultiUploadCompletionHandler)completionHandler {
    [self uploadFiles:files sequential:NO progressHandler:nil completionHandler:completionHandler];
}

- (void)uploadFiles:(NSArray<SDLFile *> *)files  sequential:(BOOL)sequential progressHandler:(nullable SDLFileManagerMultiUploadProgressHandler)progressHandler completionHandler:(nullable SDLFileManagerMultiUploadCompletionHandler)completionHandler;
```

**Comment by joeljfischer** [comment]
Hi @Toyota-Sbetts, while this is a complex API, it is not a very large API and relatively self-contained, and I'm confident we can build it in an acceptable time frame and without a significant risk of serious bugs. The primary motivation for this proposal is that it is one of the most requested features and we have seen developers need to implement something similar themselves, with varying results.

@kshala-ford Thanks for the thorough review. I agree with some of what you're saying and disagree with others; I will try to address in order.

### Transaction Completion Handlers
The idea of putting error information into an error's `userInfo` seems odd to me, but it should work. I think this combination could be acceptable.

The idea of removing the `bytesAvailable` is acceptable as well. The idea was that it would give them easy access to information that changed without referencing `self` (e.g. to log it), and therefore not having to do the weak/strong dance, but I probably overthought it.

### SDLFile Additions
There seems to be a bit of confusion around `SDLFile numberOfBytes`. This would be pulled directly from the file by SDL, not set by the developer. This property would be a `readonly` computed property that calculates the file's size using system APIs. With that in mind, does it change your opinion on any of your following comments?

I agree that `bytesAvailable`, `success`, and the `error` can be altered. I think the `uploadPercentage` is still helpful because its automatically calculated. I strongly considered using a percentage based on number of files or passing back the number of completed files and remaining files. However, as I already said, I think a byte based `uploadPercentage` is the most flexible and usable. Now that I'm thinking about it however, perhaps a `bytesRemaining` would be helpful. In addition, if we're checking the file sizes, we can now throw an error if they attempt to upload more data than is available.

A BOOL `stop` pointer would also be helpful for the `progressHandler`, I agree. They would be able to set `stop` to true and the upload would be cancelled.

### Sequential vs. Concurrent
Since this is using `NSOperationQueue` and `NSOperations` this API would just be adding new `SDLUploadOperation`s onto the queue and tracking their completions. The queue is set to sequential right now, so these would all be sequential operations. The reason for that is that `deletes` and `uploads` should probably not happen concurrently due to creating race conditions. We may wish to explore making them concurrent.

**Comment by theresalech** [comment]
Joel Fischer (Livio) suggested that this proposal be deferred, so he can revise per the discussion on the issue with Kutjim Shala (Ford).  The Steering Committee agreed with this decision.

**Comment by theresalech** [comment]
There was full agreement from the Steering Committee to accept this proposal now that it’s been revised per the discussion between Joel Fischer (Livio) and Kutjim Shala (Ford).

**Comment by theresalech** [comment]
Issue entered: [[SDL 0031] Mobile Projection](https://github.com/smartdevicelink/sdl_ios/issues/559)
