### ISSUE TITLE
[Accepted with Revisions] SDL 0277 - Continuous integration and testing

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#934]
Hello SDL community,

The review of "SDL 0277 - Continuous integration and testing"  begins now and runs through February 18, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0277-Continuous-Integration-And-Testing.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/934

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
1. Is this proposal requesting for the SDLC to host the CI servers?

2. I think all scripts relating to the ATF CI use cases should be seperated into the SDL_ATF or SDL_ATF_TEST_SCRIPTS repositories. I believe those repos should be listed as impacted platforms as well.

3. What does "noUT" mean in the `CI ATF jobs: Trigger` column?

4. For this section
`Optimizing of building process and resources usage`

are there any core code change implications?

5. Is mesos a needed dependency? When you say cluster are you referring to a cluster of docker instances on a single machine, or a cluster of multiple machines?

**Comment by MNikora** [comment]
@JackLivio 
1. This proposal doesn’t specify where it’s necessary to deploy servers. Luxoft can provide hardware and people resources for maintain it. However, we are going to publish infrastructure configuration files on the GitHub so a similar CI system can be deployed anywhere.

2. In this proposal we’re talking not only about ATF scripts, but about bash scrips which helps us to make the CI processes run, for example take each script from some test_set and run them one by one, collect the report, and show it on Jenkins like detailed html.

3. “noUT” is the abbreviation for job, which builds SDL “without UnitTests”. In current CI model when “SDL build job” finishing successfully, it’s usually triggering “ATF test jobs”.

4. `Optimizing of building process and resources usage` section is only about server resources, but not about any core code changes.

5. We are using several virtual servers, and run dockers on each of them. Also Mesos is not a dependency for us, we can configure all the slave servers in Jenkins configuration differently. It’s just a good practice to maintain a pool of such resources.

6. To fix all the issues in one proposal is too much. When this proposal is implemented we’ll see a list of issues, and make a decision for each of them. Our main idea is about finding possible hidden problems which can be fixed in the future.

6.1. No Core and ATF changes needed for this proposal implementation.  

7. We want to keep Travis check while it helps, but free version of Travis can do only basic checks.

**Comment by JackLivio** [comment]
1. 👍 
2. 👍 
3. 👍 
4. 👍 
5. 👍 
6. 👍 
7. 👍 

8. It is proposed that there should be a new repository as well as creating a new directory structure in SDL Core's repository?

I would prefer to keep the new CI code in its own repository. Also I would prefer to not move the existing sdl core tools directory and not create a new folder structure.

**Comment by E-SAITO-TMC** [comment]
I have 2 question
1. Does PM create test code for existing code?
2. Do contributors need test code in the future?

**Comment by MNikora** [comment]
@E-SAITO-TMC 
1. We are using only open source Continuous Integration tools in this proposal. Then we've configured a lot of different such jobs, as: build SDL with different flags, run UnitTests, run a lot of ATF test sets. All these jobs have simple XML config files, which can be used on another Jenkins server anywhere.
2. When some contributor implemented feature or bugfix in some branch, it's a Best Practice to run all the regression test sets on this branch before opening a PR to develop. We want to implement such process for sdl_core repository. So any contributor can do this check by itself or this check can be processed on our servers after PR is opened.

**Comment by MNikora** [comment]
@JackLivio 
8. Yes, I think we can change this structure tree. 
What if the core_tools will be a submodule for sdl_core and can be updated and improved in the infrastructure repository?

- sdl_core
    - tools (submodule)
- sdl_infrastructure
    - sdl_tools (source)
    - sdl_ci
        - scripts and other stuff
    - sdl_workspace
        - docker containers
        - config. scripts

**Comment by E-SAITO-TMC** [comment]
@MNikora 
Thank you for your answer.
I understood:)

**Comment by JackLivio** [comment]
8. My issue with the adding a submodule is that the CI submodule will get wrapped up with the other submodule dependencies. Very few developers cloning and initializing the sdl core submodules will need the CI directories.

Can the SDL Core repository be a submodule of the SDL Core CI/infrastructure repository instead?

**Comment by MNikora** [comment]
@JackLivio 
I understood your reason, and it looks right for me. We are building ATF and SDL core in separate jobs, to not duplicate operations. So let's keep repositories independent.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will include removing “section 3. Creating a subfolder for storing infrastructure files,” with justification that the new CI feature should be hosted in its own/separate repository.

**Comment by theresalech** [comment]
@ZhdanovP @MNikora Please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the Core repository for implementation. Thanks!

**Comment by theresalech** [comment]
Author has updated PR to reflect agreed upon revisions, and implementation issue has been entered: [[SDL 0277] Continuous integration and testing](https://github.com/smartdevicelink/sdl_core/issues/3251).
