### ISSUE TITLE
[In Review] SDL 0278 - Screen Manager Template Management

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#935]
Hello SDL community,

The review of the revised "SDL 0278 - Screen Manager Template Management" proposal begins now and runs through March 31, 2020.  The original review of this proposal occurred February 12 - March 10, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0278-screenmanager-layout-management.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/935

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
1\. Would a developer be required to use their template class extension to update the screen or would they refer back to the screen manager? For example `template.setMainLine("Hello")` or `sdlManager.getScreenManager().setMainLine1("Hello")`. 

2\. Is screen information cached between template changes? For example, when a user pushes a new template onto the stack is the current information cached? If so, where is that stored, in the template object or somewhere in the screen manager? Would this happen automatically or would the developer be required to do it?

3\. Would it be possible to pop to any template in the stack instead of just the root?

4\. I think it would make sense to allow the developers to config the screen manager to use templates or not in an all or nothing type of operation. I'm afraid if we don't push it to operate in one mode or the other developers will get confused on how to use the API. I can see them setting a single template and making all changes to it when that is not necessary. 

5\. I think it would be helpful to even create base extensions on the template class itself. Creating child classes such as `MediaTemplate`, `SoftButtonsOnlyTemplate`, etc. This way we could create more convenience methods that make sense in those templates. For example, the media template has main lines but the soft button only template does not. So not exposing those methods would be helpful to developers as they could instantly understand their capabilities without having to query the system. This could be a different proposal for this feature, but I wanted to bring it up to start.

**Comment by joeljfischer** [comment]
1\. They would refer back to `sdlManager` in the current proposal. They could set an instance of the screen manager within their class easily as a convenience. If we wanted to have methods to do, as you noted `template.setMainLine("Hello")`, we could, however, there are a few downsides:

a. We would have to use class inheritance instead of a protocol / interface. This is possible, but Obj-C / Swift are designed as protocol-conformance first languages instead of inheritance languages (e.g. no multiple inheritance, no abstract classes, no required methods to be implemented). I would prefer to stick with protocol / interfaces if possible.

b. There would be methods available that wouldn't work. I think there's a little bit of psychology that may occur if `sdlManager.screenManager.setText4("Text")` doesn't work, compared to `self.setText4("Text")` doesn't work. This can be "overcome" with proper documentation, but it was something I wanted to avoid.

A possible compromise could be to have a `ScreenManager` property attached to the protocol / interface which we automatically fill in for them. e.g. We do this from the screen manager:

```
template() // initialize
template.screenManager = self
// run lifecycle methods, push to stack, etc.
```

I would be leery of adding an initializer because the dev would need to implement it and it prevents us from adding onto that initializer in the future.

2\. It is not cached automatically. I note in the proposal (it's kind of hidden in the `templateActivated` method documentation):

> Called immediately after the head unit has responded successfully to an RPC that changes to this template layout. Data for this template can now be shown on the screen. Note that data from the previous template will remain until modified. You can call `ScreenManager.clearScreen` in this method to quickly clear the screen.

If the dev wished to cache the data for a template and show it again, they could store it in the class itself (in vars), and then re-apply it when the `templateActivated` method is called. This gives the dev the most flexibility to keep or remove data without us having to persist it or send additional unwanted RPCs, and without causing the dev too much frustration (I hope).

3\. Yes, we could add that. The reason I didn't add it is that it requires us to provide a way for the dev to identify the template. But as I'm thinking about it now, comparing references is easy and should work. The method would be like `-(BOOL)popToTemplate:(id<SDLTemplate>)template`, where the `retval = true` if the pop will be attempted because the template was found in the stack and the `retval = false` if it is not found in the stack and fails. Alternatively we could return an error value, or in Java Suite's case, `throw`.

4\. Are you saying that if they turn it on we deny `SetDisplayLayout` / `Show w/ layout change` RPCs from being sent outside of the screen manager, and if it's off, we deny the push / pop methods? We could do something like that. If it defaulted to off and they did a push / pop we would throw an unrecoverable exception / assert, or if we defaulted to on and they did an RPC, we'd do the same. That way in development they should discover they can only do one way.

I don't think your use-case is that big of a deal (after all we let devs do `Show` and screen manager simultaneously and rely on them knowing not to do that and we haven't heard too many horror stories), but we can consider it.

5\. That ties in a little to (1) above, about using abstract classes vs. protocols. I see the utility of what you're saying, though I think it's really rather minimal. It would mainly be about the support of three things: text, graphics, and soft buttons, and we would add / remove methods based on what's supposed to be on the layout. 

However, I don't know how much control we have over OEM implementations. Yes, the layout you referenced is _supposed_ be soft buttons only with no text or graphic, but all that it takes is one head unit released with a text field on that layout and then we'd have to at least consider adding a text field onto that template subclass, which could then end up being confusing. I think that it could end up being bloat without a big benefit. I think that idea could be an extension to this, but because it could be added later, I would prefer the merits be debated in a separate proposal.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow for further discussion on this review issue.

**Comment by kshala-ford** [comment]
Going through the proposal I had the same questions as Joey mentioned.

This proposal is very close to the accepted proposal https://github.com/smartdevicelink/sdl_evolution/issues/511 which allows a stack of view controllers that do cache the view content. Pushing new view controllers will cache the data of an underlying view controller. Changing it's properties will modify the "cache" but won't send RPCs to the head unit. Pop a view controller will notify the app about the view appearance allowing cache modifications before sending the Show request.

I highly suggest to follow this flow. Also suggest to revisit the proposals around the high level interface.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, to allow the author time to respond to comments and for additional conversation on the review issue.

**Comment by joeljfischer** [comment]
I'm okay with @kshala-ford's suggestion to cache existing show data. This would change the proposal in the following ways:

1. The current show data would be cached for each id<SDLTemplate> object within the sub-manager.
1. On < SDL 6.0 systems, `templateActivated` would only fire after both the `SetDisplayLayout` and `Show` RPCs finish.
1. Caching behavior is able to be turned off in a new object `SDLScreenManagerConfiguration` in a sub-object `TemplateConfiguration` with the property name `cachingEnabled` that is `true` by default. The existing `MenuConfiguration` and `KeyboardConfiguration` would be deprecated from their current locations and moved in there for better encapsulation.

In discussion offline with Joey, I would also propose the following modifications to this proposal:
1 Add a new `SDLScreenManager` method `- (void)changeLayout:(NSString *)layout error:(NSError *)error`. This method would use `Show` on > 6.0 systems, and `SetDisplayLayout` on < 6.0 systems. This would be used for existing apps that aren't ready to migrate to the template system. However, if an app has any template on the template stack and calls `changeLayout:` an exception will be thrown. The developer should only use one or the other.
2. Deprecate the `SetDisplayLayout` RPC and direct developers to use `changeLayout:` or the template stack system.

**Comment by kshala-ford** [comment]
@joeljfischer 

1\. Can you elaborate how the data will be cached and where the data will be stored? My expectation is that the template protocol has additional properties to each `Show` related parameter. When using the `ScreenManager` methods to set main fields or soft buttons it would manipulate the most top template instance in the stack. When pushing or removing one template instance to/from the stack it would be helpful for the screen manager to fetch the data out of the template instance. Especially in cases like `templateActivating` (or in UIKit `viewWillAppear`) there are valid reasons to use this method to update the content before it is activated.

3\. I am not sure if a configuration is required. I believe all applications would prefer content per item in the stack as this is what they are used from designing a UI on mobile apps. Adding a configuration means that both (caching on or off) must be supported by the managers which means more effort to implement this feature.

Continuing the enumeration of the offline discussion with Joey

4\. The method `changeLayout` makes complete sense and should be included. As you suggest: Using this method without the template stack should be possible to simplify migration. However, if template stack is used this method should not throw an exception but update the layout of the most top item in the stack. This would be aligned with the suggestion in 1.

**Comment by joeljfischer** [comment]
1\. The idea that I was basing off was that the manager would store the current data for the template internally and restore whatever was last there, but that the developer could store their own data however they want. I still think that that's the best option, and I don't like the idea of adding properties for `Show` data properties to the templates. That will greatly increase the complexity of this feature and I think that we should try to keep the `ScreenManager` features helpful but relatively simple. It would also be confusing for developers for layouts that, for example, only have soft buttons or images and no text data, but the text data would still be on the `id<SDLTempate>` for the developer to set. I think that this is confusing and should be avoided.

If we were to go down that path, I think we'd want to go with Joey's idea of separate template subclasses for each predefined template layout, but I oppose that, at least for the first version of this proposal.

In sum, if that's the direction that you think the caching should go, then I oppose that and think we should stick with the original idea. Yes, there are downsides, such as that the data can't be updated until `templateActivated`, but I think that downside is much smaller than the downside of the great increase in complexity by adding the caching feature you're talking about.

3\. See (1) here. This wouldn't be necessary if we stick with no caching like I'm proposing.

4\. The developer would use `replaceCurrentTemplateWithNewTemplate:` instead. I strongly oppose a developer having the ability to change the layout of a template without changing to a new template. That would break the `@property (copy, nonatomic, readonly) NSString *layoutName;` property on the template protocol, and becomes confusing and complex for little or no gain.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review until our next meeting, to allow for additional discussion on the review issue before vote.

**Comment by joeljfischer** [comment]
After further offline discussion with Joey, I would like to substantially revise this proposal to only include the discussed `changeLayout:` method, and instead have this functionality exist in a separate "extension" repository if [the example apps repo proposal](https://github.com/smartdevicelink/sdl_evolution/issues/957) is accepted.

**Comment by joeljfischer** [comment]
I have created a revision PR here: https://github.com/smartdevicelink/sdl_evolution/pull/958

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions.  The author will revise to remove the pushing/popping of template objects and instead add a method for simply changing the current layout.

**Comment by theresalech** [comment]
The author has updated this proposal to incorporate the agreed upon revisions noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/935#issuecomment-597690995), and the revised proposal is now in review. The proposal will remain in review until 2020-03-31.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Implementation Issues Entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1612)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1327)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/175)
