### ISSUE TITLE
[Accepted] SDL 0286 - Java Suite Cleanup

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#956]
Hello SDL community,

The review of "SDL 0286 - Java Suite Cleanup"  begins now and runs through March 10, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0286-java-suite-cleanup.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/956

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by E-SAITO-TMC** [comment]
I believe this proposal will cause a major change. So, how long do you think it will take for this change to be complete?
This proposal was not included in the roadmap workshop. Shouldn't such major change must be included in the roadmap?

**Comment by joeygrover** [comment]
@E-SAITO-TMC the version will be considered a major change because a lot of previously public classes and methods will be removed or refactored, however, most of them are not in use. We do not believe this proposal will take a long time due to the fact most of it can be done through the IDE automation tools, it is removal of code, the code already exists in the Java SE/EE modules so it just needs to be linked in the Android module, etc. 

The only way for an item to be included on the roadmap is to have it as an accepted proposal. As always, the roadmap is modifiable when new proposals are accepted. Dates for such requests were included in the presentation as usual.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.  It was noted that implementation effort and timing could be brought before the Steering Committee when planning future releases.

**Comment by theresalech** [comment]
Implementation issue: [[SDL 0286] Java Suite Cleanup](https://github.com/smartdevicelink/sdl_java_suite/issues/1306)
