### ISSUE TITLE
[In Review] SDL 0298 - Processing of unknown enum values by SDL Core

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#989]
Hello SDL community,

The review of the revised proposal "SDL 0298 - Processing of unknown enum values by SDL Core" begins now and runs through May 19, 2020.  The original review of this proposal, previously named "SDL 0298 - Processing of unknown enum values by SDL Core and Mobile Libraries", occurred March 31 - April 21, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0298-Processing-of-unknown-enum-values-by-SDL-Core.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/989

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. The section "Changes related to mobile application connecting to SDL Core" is unclear. What are the changes that are occurring here? I think you're mixing up the protocol version and the RPC spec version, which are very different. You state:

> To filter out unsupported items we need to know the exact protocol version, not only the major part of it but the minor part as well since certain parameters were added in between the major change. For instance, AppHMIType items PROJECTION and REMOTE_CONTROL were rolled in as early as 4.5. There is a possible case when we know the major version is 4 but the information about the minor part of it is unknown before RegisterAppInterface request is sent and responded.

But this doesn't help us filter out unsupported items at all unless they're _protocol spec_ items. It does not help us filter out _RPC_ items unless you're able to correlate a protocol version with an RPC version. At best this will be inconsistent and only work in some cases.

2\. In "Changes related to sending request(s) from mobile application to SDL Core", why are we doing both this _and_ filtering on the Core side? It seems redundant to filter out bad values on the proxy side and to filter them out on the Core side. It should just be one or the other.

3\. You state "iOS should be extended with similar mechanism in order to encapsulate filtering logic." Why is this only called out for iOS and not for the other app libraries.

4\. You state "Note: In case no HMI types are left after filtering, Mobile Library should throw an exception, otherwise RegisterAppInterface RPC will be sent with remaining HMI types."

Is this only for `RegisterAppInterface` or do the libraries need to account for mandatory / optional enum values in all RPCs? It's not clear in this proposal.

5\. You don't note JavaScript Suite anywhere, but this proposal should impact that platform as well.

**Comment by JackLivio** [comment]
6. 
> however REMOTE_CONTROL was introduced in version 6.0 of the RAPI.

REMOTE_CONTROL was added in RPC spec version 4.5, not 6.0.

7. 
For example 1 

> Request contains a parameter which value is an enum item.

The flow described depends on if the parameter was mandatory or not. Mandatory status can change between versions, which version should be used to decide the mandatory status? 

8. Example 1 continued:

I am not sure that these cases apply to RPCs other than register app interface. By the time the app is sending a `SetMediaClockTimer`  request there should be a negotiated rpc spec version and the valid enum types should be known by both core and proxies.

**Comment by Sohei-Suzuki-Nexty** [comment]
9. The core version 4.3 is used as an example, but does this mean that the core of the current vehicles need to be updated as well?

**Comment by IGapchuk** [comment]
Hi @joeljfischer. Thank you for the feedback! Regarding your questions:

1. Because we do not have the `MOBILE_API` `RPC` spec version at the time of registration we need to use the `PROTOCOL` spec version to make a decision if the `REMOTE_CONTROL` and `PROJECTION` enums are supported.
So, according to the following version match:

**SDL 4.3.0**
SDL protocol 4
Mobile API 4.4.0 (see [MOBILE_API](https://github.com/smartdevicelink/sdl_core/blob/release/4.3.0/src/components/interfaces/MOBILE_API.xml))
**SDL 4.4.0**
SDL protocol 5 (see [release/4.4.0](https://github.com/smartdevicelink/sdl_core/releases/tag/4.4.0))
Mobile API 4.5.0: ([MOBILE_API](https://github.com/smartdevicelink/sdl_core/blob/4.4.0/src/components/interfaces/MOBILE_API.xml))

we can definitively say that the `PROTOCOL` version 5 and above will always have support for the `REMOTE_CONTROL` and `PROJECTION` enums.

2. The approach needs to happen on both sides, `SDL Core` and `Mobile Libraries`. In order to preserve backward compatibility the `Mobile Libraries` needs to be able to filter out enum items that are not compatible with the connected `SDL Core RPC spec` version. Going into the future, `SDL Core` should be updated to be smart enough to ignore unknown enum items (as it does for other things like parameters).  As headunits are updated in the field with newer core versions, there eventually will be less of a need for the Mobile Libraries to filter enums as the new `SDL Core` version will ignore enum items that it does not understand.

3. This proposal provides the changes that should be implemented for `iOS` and extended for `Android OS`. Because some filtering logic is partly implemented for `Android OS` and not implemented for `iOS` at all.  For example, please take a look at the format code snippet below: 
https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L2275

4. This logic relates only to `RegisterAppInterface RPC`.

5. We'll investigate updating to include details regarding JavaScript Suit.

**Comment by IGapchuk** [comment]
Hi @JackLivio . Thank you for the feedback! Regarding your questions:

6. We will update the changes (change `RAPI`'s version from `6.0` to `4.5`)

7. The solution provided by the proposal doesn't depend on mandatory parameters. And in the current implementation, `SDL Core` doesn't have a workaround solution about unknown enums.

8. It's true that the `RPC` spec version has been negotiated by this time. If a newer app sends a 
request with a new enum item to an older version of `SDL Core`, it will receive back invalid data. 
This behavior differs from other parts of `SDL Core` where new or unknown parameters are ignored 
(e.g. a policy table request or new parameters for `RPC`s). This proposal suggests ignoring the unknown enum and sending a success with a warning back to the app instead of invalid data with failure. This will make the platform behavior more consistent.

**Comment by IGapchuk** [comment]
Hi @Sohei-Suzuki-Nexty . Thank you for the feedback! Regarding your question:

9. We assume the `SDL Core` of current vehicles should not be updated, `Mobile Libraries` should handle it on a mobile device side.

**Comment by theresalech** [comment]
A quorum was not present during the 2020-04-07 Steering Committee Meeting, so this proposal will remain in review until our meeting on 2020-04-14.

**Comment by joeljfischer** [comment]
1\. Yikes, that's pretty ugly, but it would technically work. It would just be pretty convoluted code.

2\. I strongly disagree. There's no reason to do this on both Core and Mobile and doing so is complicated and will lead to bugs. You state:

> there eventually will be less of a need for the Mobile Libraries to filter enums as the new SDL Core version will ignore enum items that it does not understand.

Code and features like this don't simply drop off and start to stop working over time. If it's built into the app libraries it should work into the future. I would strongly recommend that the author choose a side and have either Core or the Mobile library filter out enum values that aren't valid for a given connection version.

3\. Understood

4\. I'm not asking about that specific case, I'm asking if the proposal as a whole relates to just `RegisterAppInterface` or all RPCs?

5\. Thank you

**Comment by mrapitis** [comment]
Regarding item number 2, the reason this is an issue is because of SDL core's inconsistent parameter and enumeration validation logic. A new parameter can be added to an existing RPC and core will simply ignore the parameter in the JSON message. A simple example of this would be to send a Show command and add an arbitrary parameter with an arbitrary value that is not a part of the RPC spec.  
SDL core will simply ignore the new parameter and send a success result back to the mobile application. Taking that a step further, take the Show command again and this time send it with a MetaDataTag for MainField1 as can be seen at the links below in the mobile API. This time when sending the Show command add multiple MetadataTypes and introduce a new MetadataType that does not exist in the list. The result this time will be SDL core sends back an INVALID_DATA response.
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L3968
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L3929

I believe the issue could be solved solely with mobile side changes to format each RPC message based on RPC spec version (this actually is required for the RAI example that has been mentioned in the proposal), however it may also be lower long term maintenance to correct SDL Core's inconsistent behavior so that both use cases described above are aligned.

If a brand new enumeration that never existed in a current SDL Core version is introduced in the future, we may also need new corresponding mobile library changes to format the RPC when changes are made to the enum in the future.  

Please take note of the hypothetical example below:

Hypothetical case:
Add a new parameter with a new list of enums to a  sdl core 6.1, this parameter does not belong to any version of SDL core prior to version 6.1
In the following version of sdl core 6.2 add an item to the enum list
Similar to the use case presented above regarding the MetaDataTag field, SDL core 6.1 will return back invalid data if the new enum item is utilized.
If Core's validation scheme was updated to consistently ignore enums that it have no definition  (similar to how undefined parameters are ignored) mobile side changes would not be required for the step above.

**Comment by Sohei-Suzuki-Nexty** [comment]
10. Is the purpose of this proposal to display a warning to app users? Or do you want to display a warning to app developers when developing apps? Or is it something else?

**Comment by IGapchuk** [comment]
Hi @joeljfischer ! Regarding your questions:
1. We are going to use the same implementation as for filtering regular RPC's. A little example from Android Library. We have `rpcSpecVersion` and `protocolSpecVersion`. Those objects are still of type `Version` and the `format(Version rpcVersion, boolean formatParams)` method is the one, where we can implement any custom filtering logic for each RPC. We can easily determine the place in the library where `RegisterAppInterface` is processed and right before this RPC sent call `format` method in order to call filtering logic but pass as argument `protocolSpecVersion` instead of `rpcSpecVersion`.

2. Filtering logic should be implemented for each RPC, though exception throwing - only for ‘RegisterAppInterface’.

3. The purpose of the proposal is to align validation logic and in the case when unknown parameters/enums are present, notify the app developer about that via a warning.

**Comment by joeygrover** [comment]
1\. 
>we can definitively say that the PROTOCOL version 5 and above will always have support for the REMOTE_CONTROL and PROJECTION enums.

This should be considered invalid. There is an association that is being made that has nothing to do with each other. Just because the Core project was released with those version of the specs together does not mean that they will always be used in such combination. They are two different specs that contain their own versions that have never been directly related to each other. Therefore, it can't be said "definitively" that this association will always be true. Using such a "hack" should be used with extreme caution and only when there is no other choice. This is the case with the RPC spec version negotiation in the RAI currently. The language of why it's being performed should be clear in describing the possible downfalls. Furthermore, this type of association should **ONLY** ever occur for the `RegisterAppInterface` request sent from the app.

2\. I believe this will require some modifications to the manager layer on how to handle this. By throwing an exception there should be a clear path of what logic to implement next. Developers shouldn't have to check protocol version before setting their HMI types, so how does the author see this happening for developers in the case of the RAI exception?

10\. (This is 3. in the last response) Again I would ask, what are the developers supposed to do with this information? Pushing undefined burdens onto the developers is not a good habit, so having clear actions that they are supposed to take will help not only them but the SDLC when absorbing more boilerplate code into the manager layer.

**Comment by theresalech** [comment]
The Steering Committee voted to keep this proposal in review, so that the author and commenters can continue their discussions on the review issue.

**Comment by JackLivio** [comment]
@IGapchuk 

7. Could the proposal be updated to say that that the negotiated RPC spec version is the version that should be used for determining if a parameter is mandatory or not. mandatory=true/false can change between different rpc spec versions.

General note about the proposal. We agree with the proposed core changes to filter unknown enums, but the project maintainer has a number of issues with how the proxy side filtering is proposed. The main issue we see is that the developer would have no notice that an enum was filtered out from their RPC and this would lead to unintended consequences. We would like to suggest to return this proposal for revisions that remove the proxy side changes and address the other agreed upon revisions for SDL Core. The project maintainer would like to submit our own proposal for how the mobile libraries should handle unknown enums.

**Comment by IGapchuk** [comment]
Hi @joeygrover. Regarding your questions:

1. Unfortunately, in the current implementation, we don't have another choice
for RAI to make versions negotiations between different versions of a mobile
app and the SDL Core and it is a workaround according to the fact that we do not
yet have the RPC spec version at the moment when SDL Core receives the RAI request.
And this logic related only to RAI RPC.

2 and 10:  According to the comment
https://github.com/smartdevicelink/sdl_evolution/issues/989#issuecomment-614880377 we will
revert the part of the proposal related to mobile changes and this proposal will contain only SDL Core changes.
The part related to mobile changes will be provided by the project maintainers.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions.  The author will remove the mobile side changes, and specify that REMOTE_CONTROL was added in RPC spec version 4.5, not 6.0. The proposal will also be updated to say that that the negotiated RPC spec version is the version that should be used for determining if a parameter is mandatory or not, as mandatory=true/false can change between different rpc spec versions.

**Comment by theresalech** [comment]
The author has revised the proposal to include the Steering Committee's requested revisions, and the revised proposal will now be in review until May 19, 2020. The proposal name has been updated to reflect the revisions as well.  The specific changes made to the proposal since its last review can be viewed in this merged PR: https://github.com/smartdevicelink/sdl_evolution/pull/1006.

**Comment by joeljfischer** [comment]
11. In the motivation you give an example that starts:

> A mobile application with a newer version of the Mobile API (5.0) while connecting to SDL Core, which has an older Mobile API version (4.3)

Correct me if I'm wrong, but this proposal would do nothing to solve this case because it will only affect future versions of Core, right? I understand that it's illustrative, but the example should still be something that this proposal can _actually_ fix.

11. I do have an issue with Core processing an RPC that the developer didn't intend. If Core strips an enum and then processes the rest of the RPC, the result could be quite different than the developer's intent. I think that perhaps this should be entirely solved on the mobile device side and Core should continue to reject RPCs with unknown RPCs. Except, perhaps, in certain cases, such as the RAI. Additionally, I think it's a good idea to add the rejected enum values to the info string.

**Comment by mrapitis** [comment]
>Correct me if I'm wrong, but this proposal would do nothing to solve this case because it will only affect future versions of Core, right? I understand that it's illustrative, but the example should still be something that this proposal can actually fix.

Agreed, I believe this text should actually be in the mobile side proposal that the maintainers plan to submit in the future.

>I do have an issue with Core processing an RPC that the developer didn't intend. If Core strips an enum and then processes the rest of the RPC, the result could be quite different than the developer's intent. I think that perhaps this should be entirely solved on the mobile device side and Core should continue to reject RPCs with unknown RPCs. Except, perhaps, in certain cases, such as the RAI. Additionally, I think it's a good idea to add the rejected enum values to the info string.


>General note about the proposal. We agree with the proposed core changes to filter unknown enums, but the project maintainer has a number of issues with how the proxy side filtering is proposed. The main issue we see is that the developer would have no notice that an enum was filtered out from their RPC and this would lead to unintended consequences. We would like to suggest to return this proposal for revisions that remove the proxy side changes and address the other agreed upon revisions for SDL Core. The project maintainer would like to submit our own proposal for how the mobile libraries should handle unknown enums.

Targeting only mobile side changes feels like a work around as core would still have inconsistent parameter validation logic.  Please see @JackLivio  comment above.

As mentioned earlier and recapped in the text below, core currently ignores & strips other unknown & unspecified parameters when processing RPC's today.  This proposal extends that processing to enumerations as well.  If the SDLC chooses to do so, this issue can be solved entirely on the mobile side, however doing so do does feel like a work around due to the inconsistent parameter validation logic in core. 

Add a new parameter to an existing RPC

>A new parameter can be added to an existing RPC and core will simply ignore the parameter in the JSON message. A simple example of this would be to send a Show command and add an arbitrary parameter with an arbitrary value that is not a part of the RPC spec.
SDL core will simply ignore the new parameter and send a success result back to the mobile application. 

Add a new enumeration to an RPC 
> Add a new parameter with a new list of enums to a sdl core 6.1, this parameter does not belong to any version of SDL core prior to version 6.1
In the following version of sdl core 6.2 add an item to the enum list
Similar to the use case presented above regarding the MetaDataTag field, SDL core 6.1 will return back invalid data if the new enum item is utilized.
If Core's validation scheme was updated to consistently ignore enums that it have no definition (similar to how undefined parameters are ignored) mobile side changes would not be required for the step above.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: update the example in the `Motivation` section to use a mobile application and SDL Core instance using future versions of their respective SDL libraries, instead of 5.0 and 4.3.

**Comment by theresalech** [comment]
Hi @IGapchuk and @dboltovskyi, please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the SDL Core repository for implementation.

**Comment by theresalech** [comment]
The author has updated the proposal to include the requested revisions, and an implementation issue (referenced above) has been entered.
